-- Durable payment ledger, cashier traceability and client-level FIFO payments.

create table if not exists public.invoice_payments (
  id bigint generated by default as identity primary key,
  boutique_id text not null references public.boutiques(id) on delete cascade,
  invoice_id text not null,
  amount numeric not null check (amount > 0),
  payment_method text not null,
  paid_at timestamptz not null default now(),
  recorded_at timestamptz not null default now(),
  operator_id uuid references public.platform_users(id) on delete set null,
  operator_name text not null,
  batch_id uuid not null,
  source text not null default 'invoice' check (source in ('invoice', 'client_fifo', 'legacy_backfill')),
  foreign key (boutique_id, invoice_id)
    references public.invoices(boutique_id, id) on delete cascade
);

create unique index if not exists invoice_payments_batch_invoice_uidx
  on public.invoice_payments(batch_id, invoice_id);
create index if not exists invoice_payments_boutique_paid_idx
  on public.invoice_payments(boutique_id, paid_at desc);
create index if not exists invoice_payments_invoice_idx
  on public.invoice_payments(invoice_id, paid_at);

alter table public.invoice_payments enable row level security;

drop policy if exists "invoice_payments: select" on public.invoice_payments;
create policy "invoice_payments: select" on public.invoice_payments
  for select using (
    private.auth_is_assigned_to(boutique_id) or private.auth_is_super_admin()
  );

-- Direct browser writes are intentionally disallowed. Payments go through RPCs.
revoke insert, update, delete on public.invoice_payments from anon, authenticated;
grant select on public.invoice_payments to authenticated;

-- Preserve already migrated balances as dated ledger entries. This is idempotent.
insert into public.invoice_payments (
  boutique_id, invoice_id, amount, payment_method, paid_at, recorded_at,
  operator_id, operator_name, batch_id, source
)
select
  i.boutique_id,
  i.id,
  i.acompte,
  coalesce(i.payment_method, 'Autre'),
  i.invoice_date,
  now(),
  i.operator_id,
  coalesce(pu.nom, 'Migration historique'),
  (
    substr(md5('legacy-payment:' || i.boutique_id || ':' || i.id), 1, 8) || '-' ||
    substr(md5('legacy-payment:' || i.boutique_id || ':' || i.id), 9, 4) || '-' ||
    substr(md5('legacy-payment:' || i.boutique_id || ':' || i.id), 13, 4) || '-' ||
    substr(md5('legacy-payment:' || i.boutique_id || ':' || i.id), 17, 4) || '-' ||
    substr(md5('legacy-payment:' || i.boutique_id || ':' || i.id), 21, 12)
  )::uuid,
  'legacy_backfill'
from public.invoices i
left join public.platform_users pu on pu.id = i.operator_id
where i.acompte > 0
on conflict (batch_id, invoice_id) do nothing;

create or replace function public.record_payment(
  p_boutique_id text,
  p_invoice_id text,
  p_idempotency_key uuid,
  p_amount numeric,
  p_payment_method text
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public, private
as $$
declare
  v_user uuid := auth.uid();
  v_operator_name text;
  v_invoice public.invoices%rowtype;
  v_response jsonb;
  v_applied numeric;
  v_new numeric;
  v_paid_at timestamptz := now();
begin
  if v_user is null or not private.auth_has_write_access(p_boutique_id) then
    raise exception 'forbidden';
  end if;
  if p_amount <= 0 then raise exception 'amount must be positive'; end if;

  select response into v_response
  from private.idempotency_keys
  where user_id = v_user and operation = 'record_payment' and key = p_idempotency_key;
  if v_response is not null then return v_response; end if;

  select * into v_invoice
  from public.invoices
  where boutique_id = p_boutique_id and id = p_invoice_id
  for update;
  if not found then raise exception 'invoice not found'; end if;
  if lower(coalesce(v_invoice.type, '')) = 'retour' then
    raise exception 'cannot collect payment on a return';
  end if;

  v_applied := least(p_amount, greatest(0, v_invoice.montant - v_invoice.acompte));
  if v_applied <= 0 then raise exception 'invoice already paid'; end if;
  v_new := v_invoice.acompte + v_applied;

  select nom into v_operator_name from public.platform_users where id = v_user;
  v_operator_name := coalesce(v_operator_name, 'Utilisateur');

  insert into public.invoice_payments(
    boutique_id, invoice_id, amount, payment_method, paid_at,
    operator_id, operator_name, batch_id, source
  ) values (
    p_boutique_id, p_invoice_id, v_applied, coalesce(nullif(p_payment_method, ''), 'Autre'), v_paid_at,
    v_user, v_operator_name, p_idempotency_key, 'invoice'
  );

  update public.invoices
  set acompte = v_new,
      payment_method = coalesce(nullif(p_payment_method, ''), payment_method),
      status = case when v_new >= montant then 'payée' else 'en_attente' end,
      updated_at = now()
  where boutique_id = p_boutique_id and id = p_invoice_id;

  v_response := jsonb_build_object(
    'invoice_id', p_invoice_id,
    'acompte', v_new,
    'applied_amount', v_applied,
    'status', case when v_new >= v_invoice.montant then 'payée' else 'acompte' end,
    'payment', jsonb_build_object(
      'id', currval(pg_get_serial_sequence('public.invoice_payments', 'id')),
      'amount', v_applied,
      'payment_method', coalesce(nullif(p_payment_method, ''), 'Autre'),
      'paid_at', v_paid_at,
      'operator_id', v_user,
      'operator_name', v_operator_name,
      'batch_id', p_idempotency_key,
      'source', 'invoice'
    )
  );
  insert into private.idempotency_keys(user_id, operation, key, response)
  values(v_user, 'record_payment', p_idempotency_key, v_response);
  return v_response;
end;
$$;

create or replace function public.record_client_payment(
  p_boutique_id text,
  p_client_id bigint,
  p_idempotency_key uuid,
  p_amount numeric,
  p_payment_method text,
  p_payment_date date default current_date
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public, private
as $$
declare
  v_user uuid := auth.uid();
  v_client public.clients%rowtype;
  v_invoice public.invoices%rowtype;
  v_operator_name text;
  v_response jsonb;
  v_remaining numeric;
  v_applied numeric;
  v_total_applied numeric := 0;
  v_total_due numeric := 0;
  v_allocations jsonb := '[]'::jsonb;
  v_paid_at timestamptz;
begin
  if v_user is null or not private.auth_has_write_access(p_boutique_id) then
    raise exception 'forbidden';
  end if;
  if p_amount <= 0 then raise exception 'amount must be positive'; end if;

  select response into v_response
  from private.idempotency_keys
  where user_id = v_user and operation = 'record_client_payment' and key = p_idempotency_key;
  if v_response is not null then return v_response; end if;

  select * into v_client
  from public.clients
  where boutique_id = p_boutique_id and id = p_client_id;
  if not found then raise exception 'client not found'; end if;

  select coalesce(sum(greatest(0, i.montant - i.acompte)), 0)
    into v_total_due
  from public.invoices i
  where i.boutique_id = p_boutique_id
    and lower(coalesce(i.type, '')) <> 'retour'
    and (
      i.client_id = p_client_id
      or (i.client_id is null and nullif(regexp_replace(coalesce(i.client_tel, ''), '\\D', '', 'g'), '') = nullif(regexp_replace(coalesce(v_client.tel, ''), '\\D', '', 'g'), ''))
      or (i.client_id is null and lower(trim(coalesce(i.client_nom, ''))) = lower(trim(v_client.nom)))
    );

  v_remaining := least(p_amount, v_total_due);
  if v_remaining <= 0 then raise exception 'client has no outstanding balance'; end if;

  select nom into v_operator_name from public.platform_users where id = v_user;
  v_operator_name := coalesce(v_operator_name, 'Utilisateur');
  v_paid_at := ((coalesce(p_payment_date, current_date) + (now() at time zone 'Africa/Dakar')::time) at time zone 'Africa/Dakar');

  for v_invoice in
    select i.*
    from public.invoices i
    where i.boutique_id = p_boutique_id
      and lower(coalesce(i.type, '')) <> 'retour'
      and i.montant > i.acompte
      and (
        i.client_id = p_client_id
        or (i.client_id is null and nullif(regexp_replace(coalesce(i.client_tel, ''), '\\D', '', 'g'), '') = nullif(regexp_replace(coalesce(v_client.tel, ''), '\\D', '', 'g'), ''))
        or (i.client_id is null and lower(trim(coalesce(i.client_nom, ''))) = lower(trim(v_client.nom)))
      )
    order by i.invoice_date asc, i.numero asc, i.id asc
    for update
  loop
    exit when v_remaining <= 0;
    v_applied := least(v_remaining, v_invoice.montant - v_invoice.acompte);

    insert into public.invoice_payments(
      boutique_id, invoice_id, amount, payment_method, paid_at,
      operator_id, operator_name, batch_id, source
    ) values (
      p_boutique_id, v_invoice.id, v_applied, coalesce(nullif(p_payment_method, ''), 'Autre'), v_paid_at,
      v_user, v_operator_name, p_idempotency_key, 'client_fifo'
    );

    update public.invoices
    set client_id = coalesce(client_id, p_client_id),
        acompte = acompte + v_applied,
        payment_method = coalesce(nullif(p_payment_method, ''), payment_method),
        status = case when acompte + v_applied >= montant then 'payée' else 'en_attente' end,
        updated_at = now()
    where boutique_id = p_boutique_id and id = v_invoice.id;

    v_allocations := v_allocations || jsonb_build_array(jsonb_build_object(
      'invoice_id', v_invoice.id, 'amount', v_applied
    ));
    v_total_applied := v_total_applied + v_applied;
    v_remaining := v_remaining - v_applied;
  end loop;

  v_response := jsonb_build_object(
    'client_id', p_client_id,
    'requested_amount', p_amount,
    'applied_amount', v_total_applied,
    'remaining_due', greatest(0, v_total_due - v_total_applied),
    'paid_at', v_paid_at,
    'batch_id', p_idempotency_key,
    'operator_id', v_user,
    'operator_name', v_operator_name,
    'allocations', v_allocations
  );
  insert into private.idempotency_keys(user_id, operation, key, response)
  values(v_user, 'record_client_payment', p_idempotency_key, v_response);
  return v_response;
end;
$$;

grant execute on function public.record_payment(text, text, uuid, numeric, text) to authenticated;
grant execute on function public.record_client_payment(text, bigint, uuid, numeric, text, date) to authenticated;

create or replace function public.return_sale(
  p_boutique_id text,
  p_invoice_id text,
  p_idempotency_key uuid,
  p_lines jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public, private
as $$
declare
  v_user uuid := auth.uid();
  v_operator_name text;
  v_existing jsonb;
  v_original public.invoices%rowtype;
  v_line jsonb;
  v_qty numeric;
  v_source public.invoice_lines%rowtype;
  v_return_id text;
  v_numero bigint;
  v_total numeric := 0;
  v_response jsonb;
  v_returned_at timestamptz := now();
begin
  if v_user is null or not private.auth_has_write_access(p_boutique_id) then raise exception 'forbidden'; end if;
  select response into v_existing from private.idempotency_keys
    where user_id=v_user and operation='return_sale' and key=p_idempotency_key;
  if v_existing is not null then return v_existing; end if;

  select * into v_original from public.invoices
    where boutique_id=p_boutique_id and id=p_invoice_id for update;
  if not found then raise exception 'invoice not found'; end if;
  if jsonb_typeof(p_lines)<>'array' or jsonb_array_length(p_lines)=0 then raise exception 'lines required'; end if;

  for v_line in select * from jsonb_array_elements(p_lines) loop
    v_qty:=coalesce((v_line->>'qty')::numeric,0);
    select * into v_source from public.invoice_lines
      where boutique_id=p_boutique_id and invoice_id=p_invoice_id and product_id=(v_line->>'productId')::bigint limit 1;
    if not found or v_qty<=0 or v_qty>v_source.qty then raise exception 'invalid return line'; end if;
    v_total:=v_total+v_qty*v_source.prix_unit;
  end loop;

  v_numero:=private.next_invoice_number(p_boutique_id);
  v_return_id:='R'||to_char(v_returned_at,'YYMMDD')||'-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,8));
  select nom into v_operator_name from public.platform_users where id=v_user;
  v_operator_name:=coalesce(v_operator_name,'Utilisateur');

  insert into public.invoices(id,boutique_id,numero,client_id,client_nom,client_tel,montant,acompte,invoice_date,status,type,payment_method,operator_id)
  values(v_return_id,p_boutique_id,v_numero,v_original.client_id,v_original.client_nom,v_original.client_tel,v_total,v_total,v_returned_at,'retour','Retour',coalesce(v_original.payment_method,'Autre'),v_user);

  insert into public.invoice_payments(boutique_id,invoice_id,amount,payment_method,paid_at,operator_id,operator_name,batch_id,source)
  values(p_boutique_id,v_return_id,v_total,coalesce(v_original.payment_method,'Autre'),v_returned_at,v_user,v_operator_name,p_idempotency_key,'invoice');

  for v_line in select * from jsonb_array_elements(p_lines) loop
    v_qty:=(v_line->>'qty')::numeric;
    select * into v_source from public.invoice_lines
      where boutique_id=p_boutique_id and invoice_id=p_invoice_id and product_id=(v_line->>'productId')::bigint limit 1;
    insert into public.invoice_lines(boutique_id,invoice_id,product_id,nom,qty,unit,prix_unit,sell_unit,sell_qty)
    values(p_boutique_id,v_return_id,v_source.product_id,v_source.nom,v_qty,v_source.unit,v_source.prix_unit,v_source.sell_unit,v_source.sell_qty);
    update public.products set stock=stock+v_qty where boutique_id=p_boutique_id and id=v_source.product_id;
    insert into public.stock_entries(id,boutique_id,product_id,type,qty,prix_unit,entry_date,operator_id,note)
    values(nextval('private.stock_entry_id_seq'),p_boutique_id,v_source.product_id,'Retour',v_qty,v_source.prix_unit,v_returned_at,v_user,'Retour '||p_invoice_id);
  end loop;

  v_response:=jsonb_build_object('return_invoice_id',v_return_id,'total',v_total,'returned_at',v_returned_at);
  insert into private.idempotency_keys(user_id,operation,key,response)
  values(v_user,'return_sale',p_idempotency_key,v_response);
  return v_response;
end;
$$;

grant execute on function public.return_sale(text, text, uuid, jsonb) to authenticated;

do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime')
     and not exists (
       select 1 from pg_publication_tables
       where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'invoice_payments'
     ) then
    alter publication supabase_realtime add table public.invoice_payments;
  end if;
end;
$$;
