import React, { useEffect, useMemo, useState } from "react";
import { Activity, AlertTriangle, ArrowLeft, Building2, CheckCircle2, ChevronRight, ClipboardCheck, Headphones, LayoutDashboard, Plus, RefreshCw, Search, Settings, ShieldCheck, Store, Users, X } from "lucide-react";
import {
  createOpsInteraction, createOpsTask, createOpsTicket, loadOpsWorkspace, updateOpsOnboarding,
  updateOpsTask, updateOpsTicket, upsertOpsStaffProfile,
  type OpsOnboarding, type OpsPriority, type OpsStaffProfile, type OpsTask, type OpsTicket, type OpsWorkspace,
} from "../../lib/ops";

type BoutiqueLike = { id:string; nom:string; ville?:string; tel?:string; email?:string; products?:unknown[]; entries?:Array<{qty?:number;recordedAt?:string;date?:string;movementType?:string}>; invoices?:Array<{dateRaw?:string;date?:string}> };
type UserLike = { id:string; nom:string; phone?:string; isSuperAdmin?:boolean; assignments?:Array<{boutiqueId:string;role?:string}> };
type View = "home"|"clients"|"work"|"activity"|"team"|"system";
const NAV:[View,string,React.ElementType][] = [["home","Accueil",LayoutDashboard],["clients","Clients",Building2],["work","Travail",ClipboardCheck],["activity","Activité",Activity],["team","Équipe",Users],["system","Système",Settings]];
const fmtDate=(value?:string|null)=>value?new Intl.DateTimeFormat("fr-FR",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value)):"—";
const priorityRank:Record<OpsPriority,number>={urgent:0,high:1,normal:2,low:3};
const priorityLabel:Record<OpsPriority,string>={urgent:"Urgent",high:"Haute",normal:"Normale",low:"Basse"};
const teamLabel:Record<string,string>={sales:"Sales",service:"Service",support:"Support",success:"Success",management:"Management"};

function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}) {
  return <div className="fixed inset-0 z-50 bg-black/40 flex items-end sm:items-center justify-center" onClick={onClose}><div className="w-full sm:max-w-lg rounded-t-3xl sm:rounded-3xl bg-white p-5 max-h-[85vh] overflow-y-auto" onClick={e=>e.stopPropagation()}><div className="flex items-center justify-between mb-4"><h2 className="font-black text-lg">{title}</h2><button onClick={onClose} className="h-9 w-9 rounded-xl bg-slate-100 flex items-center justify-center"><X size={17}/></button></div>{children}</div></div>;
}
const input="w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:ring-2 focus:ring-slate-300";

export function TournalOpsWorkspace({boutiques,users,onOpenBoutique,onSystem}:{boutiques:BoutiqueLike[];users:UserLike[];onOpenBoutique:(id:string)=>void;onSystem:()=>void}) {
  const [view,setView]=useState<View>("home");
  const [query,setQuery]=useState("");
  const [workspace,setWorkspace]=useState<OpsWorkspace|null>(null);
  const [loading,setLoading]=useState(true);
  const [error,setError]=useState("");
  const [selectedId,setSelectedId]=useState<string|null>(null);
  const [taskModal,setTaskModal]=useState(false);
  const [ticketModal,setTicketModal]=useState(false);
  const [taskTitle,setTaskTitle]=useState(""); const [taskBoutique,setTaskBoutique]=useState(""); const [taskTeam,setTaskTeam]=useState<"sales"|"service"|"support"|"success"|"management">("service"); const [taskPriority,setTaskPriority]=useState<OpsPriority>("normal"); const [taskDue,setTaskDue]=useState("");
  const [ticketSubject,setTicketSubject]=useState(""); const [ticketBoutique,setTicketBoutique]=useState(""); const [ticketPriority,setTicketPriority]=useState<OpsPriority>("normal"); const [ticketRequester,setTicketRequester]=useState(""); const [ticketPhone,setTicketPhone]=useState("");
  const [saving,setSaving]=useState(false);

  async function refresh() { setLoading(true); setError(""); try { setWorkspace(await loadOpsWorkspace()); } catch(e) { setError(e instanceof Error?e.message:"Chargement Ops impossible"); } finally { setLoading(false); } }
  useEffect(()=>{ void refresh(); },[]);

  const rows=useMemo(()=>boutiques.map(b=>{
    const members=users.filter(u=>u.assignments?.some(a=>a.boutiqueId===b.id));
    const overview=workspace?.overview.find(item=>item.boutique_id===b.id);
    const lastSale=overview?.last_sale_at??(b.invoices??[]).map(i=>i.dateRaw??i.date??"").filter(Boolean).sort().at(-1)??null;
    const firstSale=overview?.first_sale_at??(b.invoices??[]).map(i=>i.dateRaw??i.date??"").filter(Boolean).sort().at(0)??null;
    const receipts=(b.entries??[]).filter(e=>(e.qty??0)>0&&e.movementType==="achat");
    const firstReceipt=overview?.first_receipt_at??receipts.map(e=>e.recordedAt??e.date??"").filter(Boolean).sort().at(0)??null;
    const setup=(overview?.product_count??b.products?.length??0)>0;
    const onboarding=workspace?.onboarding.find(o=>o.boutique_id===b.id);
    const openTasks=workspace?.tasks.filter(t=>t.boutique_id===b.id&&!['done','cancelled'].includes(t.status))??[];
    const openTickets=workspace?.tickets.filter(t=>t.boutique_id===b.id&&!['resolved','closed'].includes(t.status))??[];
    const ownerReady=(overview?.owner_count??0)>0||members.some(m=>m.assignments?.some(a=>a.boutiqueId===b.id&&(a.role==="Propriétaire"||a.role==="owner")));
    const checks=[ownerReady,members.length>0,setup,Boolean(firstReceipt||onboarding?.first_receipt_at),Boolean(firstSale||onboarding?.first_sale_at),Boolean(onboarding?.training_done)];
    const progress=Math.round(checks.filter(Boolean).length/checks.length*100);
    const score=Math.max(0,Math.min(100,progress-(openTickets.some(t=>t.priority==='urgent')?20:0)-(openTasks.filter(t=>t.due_at&&new Date(t.due_at)<new Date()).length*5)));
    return {...b,members,lastSale,firstSale,firstReceipt,setup,onboarding,openTasks,openTickets,ownerReady,progress,score};
  }),[boutiques,users,workspace]);
  const filtered=rows.filter(b=>(b.nom+" "+(b.ville??"")+" "+(b.tel??"")+" "+b.members.map(m=>m.nom+" "+(m.phone??"")).join(" ")).toLowerCase().includes(query.toLowerCase()));
  const attention=rows.filter(b=>b.progress<100||b.openTickets.length>0||b.openTasks.length>0).sort((a,b)=>a.score-b.score);
  const selected=rows.find(b=>b.id===selectedId)??null;
  const activeTasks=(workspace?.tasks??[]).filter(t=>!['done','cancelled'].includes(t.status)).sort((a,b)=>priorityRank[a.priority]-priorityRank[b.priority]||String(a.due_at??'9999').localeCompare(String(b.due_at??'9999')));
  const activeTickets=(workspace?.tickets??[]).filter(t=>!['resolved','closed'].includes(t.status)).sort((a,b)=>priorityRank[a.priority]-priorityRank[b.priority]||b.id-a.id);

  async function submitTask(){if(!taskTitle.trim()||saving)return;setSaving(true);try{const item=await createOpsTask({boutiqueId:taskBoutique||null,title:taskTitle,team:taskTeam,priority:taskPriority,dueAt:taskDue?new Date(taskDue).toISOString():null});setWorkspace(w=>w?{...w,tasks:[item,...w.tasks]}:w);setTaskTitle("");setTaskBoutique("");setTaskDue("");setTaskModal(false);}catch(e){setError(e instanceof Error?e.message:"Création impossible");}finally{setSaving(false)}}
  async function submitTicket(){if(!ticketSubject.trim()||!ticketBoutique||saving)return;setSaving(true);try{const item=await createOpsTicket({boutiqueId:ticketBoutique,subject:ticketSubject,priority:ticketPriority,requesterName:ticketRequester,requesterPhone:ticketPhone});setWorkspace(w=>w?{...w,tickets:[item,...w.tickets]}:w);setTicketSubject("");setTicketBoutique("");setTicketRequester("");setTicketPhone("");setTicketModal(false);void refresh();}catch(e){setError(e instanceof Error?e.message:"Création impossible");}finally{setSaving(false)}}
  async function completeTask(task:OpsTask){const updated=await updateOpsTask(task.id,{status:"done"});setWorkspace(w=>w?{...w,tasks:w.tasks.map(t=>t.id===updated.id?updated:t)}:w)}
  async function resolveTicket(ticket:OpsTicket){const updated=await updateOpsTicket(ticket.id,{status:"resolved"});await createOpsInteraction({boutiqueId:ticket.boutique_id,kind:"support",team:"support",title:`Ticket #${ticket.id} résolu · ${ticket.subject}`,relatedTicketId:ticket.id});setWorkspace(w=>w?{...w,tickets:w.tickets.map(t=>t.id===updated.id?updated:t)}:w);void refresh()}

  if(selected){const ob=selected.onboarding;return <div className="min-h-screen bg-[#f6f7f9] p-4"><div className="mx-auto max-w-4xl space-y-4"><button onClick={()=>setSelectedId(null)} className="flex items-center gap-2 text-sm font-black"><ArrowLeft size={16}/> Clients</button><section className="rounded-3xl bg-white border p-5"><div className="flex items-start gap-3"><div className="h-12 w-12 rounded-2xl bg-slate-950 text-white flex items-center justify-center"><Building2 size={21}/></div><div className="flex-1"><div className="flex gap-2 items-center flex-wrap"><h1 className="text-xl font-black">{selected.nom}</h1><span className="rounded-full bg-emerald-50 text-emerald-700 px-2 py-1 text-[10px] font-black">Santé {selected.score}/100</span></div><p className="text-sm text-slate-500">{selected.ville||"Ville non renseignée"} · {selected.members.length} utilisateur(s)</p></div><button onClick={()=>onOpenBoutique(selected.id)} className="rounded-xl bg-slate-950 text-white px-3 py-2 text-xs font-black">Ouvrir boutique</button></div><div className="mt-5"><div className="flex justify-between text-xs font-bold"><span>Onboarding</span><span>{selected.progress}%</span></div><div className="mt-2 h-2 rounded-full bg-slate-100 overflow-hidden"><div className="h-full bg-emerald-500" style={{width:`${selected.progress}%`}}/></div></div></section>
    <section className="grid md:grid-cols-2 gap-3"><div className="rounded-2xl bg-white border p-4"><p className="font-black text-sm">Checklist automatique</p><div className="mt-3 space-y-2">{[["Propriétaire affecté",selected.ownerReady],["Utilisateurs créés",selected.members.length>0],["Catalogue configuré",selected.setup],["Première réception",Boolean(selected.firstReceipt||ob?.first_receipt_at)],["Première vente",Boolean(selected.firstSale||ob?.first_sale_at)],["Formation terminée",Boolean(ob?.training_done)]].map(([label,ok])=><div key={String(label)} className="flex items-center gap-2 text-sm"><CheckCircle2 size={16} className={ok?"text-emerald-600":"text-slate-300"}/><span className={ok?"font-semibold":"text-slate-500"}>{label}</span></div>)}</div>{!ob?.training_done&&<button onClick={async()=>{const updated=await updateOpsOnboarding(selected.id,{training_done:true,training_done_at:new Date().toISOString(),owner_ready:selected.ownerReady,users_ready:selected.members.length>0,catalogue_ready:selected.setup,first_receipt_at:selected.firstReceipt??ob?.first_receipt_at??null,first_sale_at:selected.firstSale??ob?.first_sale_at??null});setWorkspace(w=>w?{...w,onboarding:w.onboarding.map(x=>x.boutique_id===updated.boutique_id?updated:x)}:w)}} className="mt-4 rounded-xl bg-emerald-50 text-emerald-700 px-3 py-2 text-xs font-black">Valider la formation</button>}</div><div className="rounded-2xl bg-white border p-4"><p className="font-black text-sm">Relation opérationnelle</p><div className="mt-3 grid grid-cols-2 gap-2 text-xs"><div className="rounded-xl bg-slate-50 p-3"><p className="text-slate-500">Tâches ouvertes</p><p className="text-xl font-black">{selected.openTasks.length}</p></div><div className="rounded-xl bg-slate-50 p-3"><p className="text-slate-500">Tickets ouverts</p><p className="text-xl font-black">{selected.openTickets.length}</p></div><div className="rounded-xl bg-slate-50 p-3 col-span-2"><p className="text-slate-500">Dernière activité connue</p><p className="font-black mt-1">{fmtDate(selected.lastSale)}</p></div></div></div></section>
    <section className="rounded-2xl bg-white border p-4"><p className="font-black text-sm">Timeline client</p><div className="mt-3 space-y-3">{(workspace?.interactions??[]).filter(i=>i.boutique_id===selected.id).slice(0,30).map(i=><div key={i.id} className="flex gap-3"><div className="mt-1 h-2.5 w-2.5 rounded-full bg-slate-900"/><div><p className="text-sm font-bold">{i.title}</p><p className="text-xs text-slate-500">{teamLabel[i.team??'']??i.kind} · {fmtDate(i.created_at)}</p>{i.detail&&<p className="text-xs mt-1">{i.detail}</p>}</div></div>)}{!(workspace?.interactions??[]).some(i=>i.boutique_id===selected.id)&&<p className="text-sm text-slate-500">Aucune interaction interne enregistrée.</p>}</div></section></div></div>}

  return <div className="min-h-screen bg-[#f6f7f9] text-slate-900 pb-24" data-screen-source="tournal-ops-workspace"><header className="sticky top-0 z-30 border-b bg-white/95 backdrop-blur"><div className="mx-auto max-w-6xl px-4 py-3 flex items-center gap-3"><div className="h-10 w-10 rounded-2xl bg-slate-950 text-white flex items-center justify-center font-black">T</div><div className="flex-1"><p className="font-black leading-none">Tournal Ops</p><p className="text-[11px] text-slate-500 mt-1">Sales · Service · Support</p></div><button onClick={()=>void refresh()} className="h-9 w-9 rounded-xl bg-slate-100 flex items-center justify-center"><RefreshCw size={15} className={loading?"animate-spin":""}/></button><span className="hidden sm:flex items-center gap-1 rounded-full bg-emerald-50 text-emerald-700 px-3 py-1 text-xs font-bold"><ShieldCheck size={13}/> SuperAdmin</span></div></header><main className="mx-auto max-w-6xl p-4 space-y-4">
    <div className="relative"><Search className="absolute left-3 top-3 text-slate-400" size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Rechercher boutique, utilisateur, téléphone…" className="w-full rounded-2xl border bg-white py-2.5 pl-10 pr-4 text-sm outline-none focus:ring-2 focus:ring-slate-300"/></div>{error&&<div className="rounded-xl bg-red-50 text-red-700 px-3 py-2 text-xs font-bold">{error}</div>}
    <nav className="flex gap-2 overflow-x-auto pb-1">{NAV.map(([id,label,Icon])=><button key={id} onClick={()=>setView(id)} className={`shrink-0 flex items-center gap-1.5 rounded-xl px-3 py-2 text-xs font-black ${view===id?"bg-slate-950 text-white":"bg-white border text-slate-600"}`}><Icon size={14}/>{label}</button>)}</nav>
    {view==="home"&&<><section className="grid grid-cols-2 md:grid-cols-4 gap-3">{[["Boutiques",rows.length],["Tâches actives",activeTasks.length],["Tickets ouverts",activeTickets.length],["Onboarding 100%",rows.filter(b=>b.progress===100).length]].map(([l,v])=><div key={String(l)} className="rounded-2xl bg-white border p-4"><p className="text-xs font-bold text-slate-500">{l}</p><p className="mt-1 text-2xl font-black">{v}</p></div>)}</section><section className="rounded-3xl bg-white border overflow-hidden"><div className="p-4 border-b flex items-center justify-between"><div><p className="font-black">À traiter</p><p className="text-xs text-slate-500">Priorités clients et onboarding</p></div><AlertTriangle className="text-amber-500" size={20}/></div>{attention.slice(0,10).map(b=><button key={b.id} onClick={()=>setSelectedId(b.id)} className="w-full p-4 border-b last:border-0 text-left flex gap-3 items-center hover:bg-slate-50"><div className="h-9 w-9 rounded-xl bg-amber-50 text-amber-700 flex items-center justify-center"><Store size={17}/></div><div className="flex-1"><p className="font-bold">{b.nom}</p><p className="text-xs text-slate-500">Onboarding {b.progress}% · {b.openTasks.length} tâche(s) · {b.openTickets.length} ticket(s)</p></div><ChevronRight size={16}/></button>)}</section></>}
    {view==="clients"&&<section className="space-y-2">{filtered.map(b=><button key={b.id} onClick={()=>setSelectedId(b.id)} className="w-full rounded-2xl bg-white border p-4 text-left"><div className="flex items-start gap-3"><div className="h-11 w-11 rounded-xl bg-slate-100 flex items-center justify-center"><Building2 size={19}/></div><div className="flex-1"><div className="flex items-center gap-2"><p className="font-black">{b.nom}</p><span className="rounded-full bg-emerald-50 text-emerald-700 px-2 py-0.5 text-[10px] font-black">{b.score}/100</span></div><p className="text-xs text-slate-500">{b.ville||"—"} · onboarding {b.progress}% · {b.members.length} utilisateur(s)</p></div><ChevronRight size={16}/></div></button>)}</section>}
    {view==="work"&&<div className="grid lg:grid-cols-2 gap-3"><section className="rounded-3xl bg-white border overflow-hidden"><div className="p-4 border-b flex justify-between items-center"><div><p className="font-black">Tâches</p><p className="text-xs text-slate-500">File commune Sales · Service · Support</p></div><button onClick={()=>setTaskModal(true)} className="h-9 w-9 rounded-xl bg-slate-950 text-white flex items-center justify-center"><Plus size={16}/></button></div>{activeTasks.slice(0,50).map(t=><div key={t.id} className="p-3 border-b last:border-0 flex gap-3"><span className={`mt-1 h-2.5 w-2.5 rounded-full ${t.priority==='urgent'?'bg-red-600':t.priority==='high'?'bg-orange-500':'bg-slate-300'}`}/><div className="flex-1"><p className="text-sm font-bold">{t.title}</p><p className="text-xs text-slate-500">{teamLabel[t.team]} · {rows.find(b=>b.id===t.boutique_id)?.nom??"Global"} · {t.due_at?fmtDate(t.due_at):"sans échéance"}</p></div><button onClick={()=>void completeTask(t)} title="Terminer" className="h-8 w-8 rounded-lg bg-emerald-50 text-emerald-700 flex items-center justify-center"><CheckCircle2 size={15}/></button></div>)}{activeTasks.length===0&&<p className="p-4 text-sm text-slate-500">Aucune tâche active.</p>}</section><section className="rounded-3xl bg-white border overflow-hidden"><div className="p-4 border-b flex justify-between items-center"><div><p className="font-black">Support</p><p className="text-xs text-slate-500">Tickets ouverts</p></div><button onClick={()=>setTicketModal(true)} className="h-9 w-9 rounded-xl bg-slate-950 text-white flex items-center justify-center"><Plus size={16}/></button></div>{activeTickets.slice(0,50).map(t=><div key={t.id} className="p-3 border-b last:border-0 flex gap-3"><Headphones size={16} className="mt-0.5 text-slate-500"/><div className="flex-1"><p className="text-sm font-bold">#{t.id} · {t.subject}</p><p className="text-xs text-slate-500">{rows.find(b=>b.id===t.boutique_id)?.nom??t.boutique_id} · {priorityLabel[t.priority]} · {fmtDate(t.created_at)}</p></div><button onClick={()=>void resolveTicket(t)} className="rounded-lg bg-emerald-50 text-emerald-700 px-2 text-[10px] font-black">Résoudre</button></div>)}{activeTickets.length===0&&<p className="p-4 text-sm text-slate-500">Aucun ticket ouvert.</p>}</section></div>}
    {view==="activity"&&<section className="rounded-3xl bg-white border p-4"><p className="font-black">Timeline Ops</p><div className="mt-4 space-y-4">{(workspace?.interactions??[]).slice(0,100).map(i=><div key={i.id} className="flex gap-3"><div className="mt-1 h-2.5 w-2.5 rounded-full bg-slate-900"/><div><p className="text-sm font-bold">{i.title}</p><p className="text-xs text-slate-500">{rows.find(b=>b.id===i.boutique_id)?.nom??"Global"} · {teamLabel[i.team??'']??i.kind} · {fmtDate(i.created_at)}</p></div></div>)}{!(workspace?.interactions.length)&&<p className="text-sm text-slate-500">La timeline se remplira avec les interactions Sales, Service et Support.</p>}</div></section>}
    {view==="team"&&<section className="rounded-3xl bg-white border overflow-hidden"><div className="p-4 border-b"><p className="font-black">Équipe interne</p><p className="text-xs text-slate-500">Attribuez un rôle Ops sans donner de droits boutique.</p></div>{users.filter(u=>!u.isSuperAdmin).map(u=>{const profile=workspace?.staff.find(s=>s.user_id===u.id);return <div key={u.id} className="p-3 border-b last:border-0 flex items-center gap-3"><div className="h-9 w-9 rounded-full bg-slate-100 flex items-center justify-center font-black text-xs">{u.nom.slice(0,2).toUpperCase()}</div><div className="flex-1"><p className="text-sm font-bold">{u.nom}</p><p className="text-xs text-slate-500">{u.phone??""}</p></div><select value={profile?.role??""} onChange={async e=>{if(!e.target.value)return;const saved=await upsertOpsStaffProfile(u.id,e.target.value as OpsStaffProfile['role']);setWorkspace(w=>w?{...w,staff:[...w.staff.filter(s=>s.user_id!==saved.user_id),saved]}:w)}} className="rounded-lg border px-2 py-1.5 text-xs"><option value="">Aucun rôle Ops</option><option value="sales">Sales</option><option value="service">Service</option><option value="support">Support</option><option value="manager">Manager</option></select></div>})}</section>}
    {view==="system"&&<section className="rounded-3xl bg-white border p-5"><div className="flex gap-3"><div className="h-11 w-11 rounded-xl bg-red-50 text-red-700 flex items-center justify-center"><Settings size={20}/></div><div><p className="font-black">Administration technique</p><p className="text-xs text-slate-500">Boutiques, comptes, groupes et paramètres sensibles restent séparés de Tournal Ops.</p></div></div><button onClick={onSystem} className="mt-5 w-full rounded-xl bg-slate-950 text-white py-3 text-sm font-black">Ouvrir l’administration système</button></section>}
  </main>
  {taskModal&&<Modal title="Nouvelle tâche" onClose={()=>setTaskModal(false)}><div className="space-y-3"><input value={taskTitle} onChange={e=>setTaskTitle(e.target.value)} placeholder="Action à réaliser" className={input}/><select value={taskBoutique} onChange={e=>setTaskBoutique(e.target.value)} className={input}><option value="">Tâche globale</option>{rows.map(b=><option key={b.id} value={b.id}>{b.nom}</option>)}</select><div className="grid grid-cols-2 gap-2"><select value={taskTeam} onChange={e=>setTaskTeam(e.target.value as any)} className={input}><option value="sales">Sales</option><option value="service">Service</option><option value="support">Support</option><option value="success">Success</option><option value="management">Management</option></select><select value={taskPriority} onChange={e=>setTaskPriority(e.target.value as OpsPriority)} className={input}><option value="low">Basse</option><option value="normal">Normale</option><option value="high">Haute</option><option value="urgent">Urgente</option></select></div><input type="datetime-local" value={taskDue} onChange={e=>setTaskDue(e.target.value)} className={input}/><button disabled={saving||!taskTitle.trim()} onClick={()=>void submitTask()} className="w-full rounded-xl bg-slate-950 text-white py-3 text-sm font-black disabled:opacity-50">Créer la tâche</button></div></Modal>}
  {ticketModal&&<Modal title="Nouveau ticket support" onClose={()=>setTicketModal(false)}><div className="space-y-3"><select value={ticketBoutique} onChange={e=>setTicketBoutique(e.target.value)} className={input}><option value="">Choisir la boutique</option>{rows.map(b=><option key={b.id} value={b.id}>{b.nom}</option>)}</select><input value={ticketSubject} onChange={e=>setTicketSubject(e.target.value)} placeholder="Sujet du problème" className={input}/><select value={ticketPriority} onChange={e=>setTicketPriority(e.target.value as OpsPriority)} className={input}><option value="low">Basse</option><option value="normal">Normale</option><option value="high">Haute</option><option value="urgent">Urgente</option></select><input value={ticketRequester} onChange={e=>setTicketRequester(e.target.value)} placeholder="Demandeur" className={input}/><input value={ticketPhone} onChange={e=>setTicketPhone(e.target.value)} placeholder="Téléphone" className={input}/><button disabled={saving||!ticketBoutique||!ticketSubject.trim()} onClick={()=>void submitTicket()} className="w-full rounded-xl bg-slate-950 text-white py-3 text-sm font-black disabled:opacity-50">Ouvrir le ticket</button></div></Modal>}
  </div>;
}
