-- Audit-only reconstruction of the transfer tables that predate the retained
-- Git migration history. Later migrations still add the financial/conditioning
-- columns; this file restores only the earlier structural contract.

alter table public.stock_transfers
  add column if not exists status text not null default 'pending',
  add column if not exists note text,
  add column if not exists created_by uuid,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists accepted_at timestamptz,
  add column if not exists accepted_by uuid;

do $$
begin
  if not exists (select 1 from pg_constraint where conname='stock_transfers_from_boutique_id_fkey' and conrelid='public.stock_transfers'::regclass) then
    alter table public.stock_transfers add constraint stock_transfers_from_boutique_id_fkey foreign key (from_boutique_id) references public.boutiques(id);
  end if;
  if not exists (select 1 from pg_constraint where conname='stock_transfers_to_boutique_id_fkey' and conrelid='public.stock_transfers'::regclass) then
    alter table public.stock_transfers add constraint stock_transfers_to_boutique_id_fkey foreign key (to_boutique_id) references public.boutiques(id);
  end if;
  if not exists (select 1 from pg_constraint where conname='stock_transfers_created_by_fkey' and conrelid='public.stock_transfers'::regclass) then
    alter table public.stock_transfers add constraint stock_transfers_created_by_fkey foreign key (created_by) references auth.users(id);
  end if;
  if not exists (select 1 from pg_constraint where conname='stock_transfers_accepted_by_fkey' and conrelid='public.stock_transfers'::regclass) then
    alter table public.stock_transfers add constraint stock_transfers_accepted_by_fkey foreign key (accepted_by) references auth.users(id);
  end if;
  if not exists (select 1 from pg_constraint where conname='stock_transfers_check' and conrelid='public.stock_transfers'::regclass) then
    alter table public.stock_transfers add constraint stock_transfers_check check (from_boutique_id <> to_boutique_id);
  end if;
  if not exists (select 1 from pg_constraint where conname='stock_transfers_status_check' and conrelid='public.stock_transfers'::regclass) then
    alter table public.stock_transfers add constraint stock_transfers_status_check check (status in ('pending','accepted','rejected','cancelled'));
  end if;
end
$$;

alter table public.stock_transfers alter column created_by set not null;

create table if not exists public.stock_transfer_lines (
  id bigint generated by default as identity primary key,
  transfer_id uuid not null references public.stock_transfers(id) on delete cascade,
  source_boutique_id text not null,
  source_product_id bigint not null,
  product_name text not null,
  unit text not null,
  qty numeric not null check (qty > 0),
  prix_unit numeric not null default 0,
  foreign key (source_boutique_id, source_product_id) references public.products(boutique_id,id)
);
