begin;
drop trigger if exists trg_commit_pos_stock_after_invoice_line on public.invoice_lines;
create or replace function private.commit_client_stock_after_invoice_line() returns trigger language plpgsql security definer set search_path = pg_catalog, public, private as $$ declare v_invoice public.invoices%rowtype; begin select * into v_invoice from public.invoices where boutique_id=new.boutique_id and id=new.invoice_id; if found and lower(coalesce(v_invoice.type,''))<>'retour' and coalesce(v_invoice.origin,'pos')='client_profile' and v_invoice.status<>'annulée' and v_invoice.stock_deducted_at is null then perform private.commit_invoice_stock(new.boutique_id,new.invoice_id,now(),auth.uid(),true); end if; return null; end; $$;
revoke all on function private.commit_client_stock_after_invoice_line() from public,anon,authenticated;
drop trigger if exists trg_commit_client_stock_after_invoice_line on public.invoice_lines;
create constraint trigger trg_commit_client_stock_after_invoice_line after insert on public.invoice_lines deferrable initially deferred for each row execute function private.commit_client_stock_after_invoice_line();
create or replace function private.enforce_pos_full_payment() returns trigger language plpgsql security definer set search_path=pg_catalog,public,private as $$ declare v_invoice public.invoices%rowtype; v_paid_before numeric; begin select * into v_invoice from public.invoices where boutique_id=new.boutique_id and id=new.invoice_id for update; if not found then raise exception 'invoice not found'; end if; if coalesce(v_invoice.origin,'pos')='pos' and lower(coalesce(v_invoice.type,''))<>'retour' then select coalesce(sum(ip.amount),0) into v_paid_before from public.invoice_payments ip where ip.boutique_id=new.boutique_id and ip.invoice_id=new.invoice_id; if abs((v_paid_before+coalesce(new.amount,0))-coalesce(v_invoice.montant,0))>0.01 then raise exception 'counter sale must be paid in full'; end if; end if; return new; end; $$;
revoke all on function private.enforce_pos_full_payment() from public,anon,authenticated;
drop trigger if exists trg_enforce_pos_full_payment on public.invoice_payments;
create trigger trg_enforce_pos_full_payment before insert on public.invoice_payments for each row execute function private.enforce_pos_full_payment();
-- Unpaid POS orders have no stock to release. Remove any stale POS release branch if present.
do $do$ declare v_def text; v_old text; begin select pg_get_functiondef('public.update_pending_sale(text,text,uuid,bigint,text,text,jsonb)'::regprocedure) into v_def; v_old := 'if coalesce(v_invoice.origin,''pos'') = ''pos'' and v_invoice.stock_deducted_at is not null then perform private.release_pending_pos_stock(p_boutique_id,p_invoice_id,v_user,''Modification commande''); end if; '; if position(v_old in v_def)>0 then execute replace(v_def,v_old,''); end if; select pg_get_functiondef('public.cancel_pending_sale(text,text,text,text)'::regprocedure) into v_def; v_old := 'if coalesce(v_invoice.origin,''pos'') = ''pos'' and v_invoice.stock_deducted_at is not null then perform private.release_pending_pos_stock(p_boutique_id,p_invoice_id,v_user,''Annulation commande''); end if; '; if position(v_old in v_def)>0 then execute replace(v_def,v_old,''); end if; end $do$;
commit;
