-- Audit-only reconstruction prerequisite.
-- Mirrors schema structure only; contains no production data.
create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  boutique_id text not null references public.boutiques(id) on delete cascade,
  user_id uuid references public.platform_users(id) on delete set null,
  action text not null,
  detail text,
  icon text,
  created_at timestamptz not null default now(),
  source text
);
