-- Audit-only reconstruction of the structural ledger introduced by production
-- migration 20260814035007 (invoice_payments_fifo). Historical payment backfill
-- rows are intentionally not replayed.

alter table public.invoice_payments
  alter column id add generated by default as identity,
  add column if not exists payment_method text,
  add column if not exists recorded_at timestamptz not null default now(),
  add column if not exists operator_id uuid references public.platform_users(id) on delete set null,
  add column if not exists operator_name text,
  add column if not exists batch_id uuid,
  add column if not exists source text not null default 'invoice';

alter table public.invoice_payments
  alter column payment_method set default 'Autre',
  alter column payment_method set not null,
  alter column operator_name set default 'Utilisateur',
  alter column operator_name set not null,
  alter column batch_id set default gen_random_uuid(),
  alter column batch_id set not null;

alter table public.invoice_payments
  drop constraint if exists invoice_payments_amount_check,
  add constraint invoice_payments_amount_check check (amount > 0),
  drop constraint if exists invoice_payments_source_check,
  add constraint invoice_payments_source_check check (source in ('invoice','client_fifo','legacy_backfill'));

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname='invoice_payments_boutique_id_fkey' and conrelid='public.invoice_payments'::regclass
  ) then
    alter table public.invoice_payments
      add constraint invoice_payments_boutique_id_fkey foreign key (boutique_id) references public.boutiques(id) on delete cascade;
  end if;
  if not exists (
    select 1 from pg_constraint where conname='invoice_payments_boutique_id_invoice_id_fkey' and conrelid='public.invoice_payments'::regclass
  ) then
    alter table public.invoice_payments
      add constraint invoice_payments_boutique_id_invoice_id_fkey foreign key (boutique_id,invoice_id) references public.invoices(boutique_id,id) on delete cascade;
  end if;
end
$$;

create unique index if not exists invoice_payments_batch_invoice_uidx on public.invoice_payments(batch_id,invoice_id);
create index if not exists invoice_payments_boutique_paid_idx on public.invoice_payments(boutique_id,paid_at desc);
create index if not exists invoice_payments_invoice_idx on public.invoice_payments(invoice_id,paid_at);
