import React, { useEffect, useMemo, useState } from "react";
import { BarChart3, Boxes, ChevronDown, Download, PackageSearch, ReceiptText, Users, WalletCards } from "lucide-react";
import type { Boutique, DashPeriod } from "../types";
import { inputCls } from "../constants";
import { fmt } from "../utils/formatting";
import { loadFinancialMetrics, type FinancialMetrics } from "../../lib/dashboardApi";
import { loadClientReport, loadEmployeePerformanceReport, loadSalesProductReport, loadStockInventoryReport, type ClientReport, type EmployeePerformanceReport, type SalesProductReport, type StockInventoryReport } from "../../lib/reportApi";
import { ReportKpiBand } from "./ReportKpiBand";
import { FinancialDeepReportSection } from "./FinancialDeepReportSection";
import { SalesReportSection } from "./SalesReportSection";

type Section = "sales" | "team" | "stock" | "clients" | "finance";
type SortKey = "invoiced_revenue" | "quantity" | "product_name";

function periodBounds(period: DashPeriod, customFrom: string, customTo: string) {
  const now = new Date(); let from = new Date(now); let to = new Date(now.getTime() + 1000);
  if (period === "jour") from.setHours(0, 0, 0, 0); else if (period === "semaine") from.setDate(from.getDate() - 7); else if (period === "mois") from = new Date(now.getFullYear(), now.getMonth(), 1); else if (period === "annee") from = new Date(now.getFullYear(), 0, 1); else { from = customFrom ? new Date(`${customFrom}T00:00:00`) : new Date(now); if (customTo) { to = new Date(`${customTo}T00:00:00`); to.setDate(to.getDate() + 1); } }
  return { from: from.toISOString(), to: to.toISOString() };
}
function previousBounds(bounds: { from: string; to: string }) { const a = +new Date(bounds.from), b = +new Date(bounds.to), d = Math.max(1000, b - a); return { from: new Date(a - d).toISOString(), to: new Date(a).toISOString() }; }

export function ComptabiliteView({ boutique, canSeeMargin = false }: { boutique: Boutique; canSeeMargin?: boolean }) {
  const RC = boutique.color; const [period, setPeriod] = useState<DashPeriod>("jour"); const [customFrom, setCustomFrom] = useState(""); const [customTo, setCustomTo] = useState("");
  const [metrics, setMetrics] = useState<FinancialMetrics | null>(null); const [previous, setPrevious] = useState<FinancialMetrics | null>(null); const [error, setError] = useState(""); const [open, setOpen] = useState<Section | null>(null);
  const [sales, setSales] = useState<SalesProductReport | null>(null); const [team, setTeam] = useState<EmployeePerformanceReport | null>(null); const [stock, setStock] = useState<StockInventoryReport | null>(null); const [clients, setClients] = useState<ClientReport | null>(null); const [sectionLoading, setSectionLoading] = useState<Section | null>(null); const [dormantDays, setDormantDays] = useState(60); const [category, setCategory] = useState("all"); const [sort, setSort] = useState<SortKey>("invoiced_revenue");
  const bounds = useMemo(() => periodBounds(period, customFrom, customTo), [period, customFrom, customTo]); const prevBounds = useMemo(() => previousBounds(bounds), [bounds.from, bounds.to]);

  useEffect(() => { let cancelled = false; setError(""); setOpen(null); setSales(null); setTeam(null); setStock(null); setClients(null); Promise.all([loadFinancialMetrics({ boutiqueId: boutique.id, ...bounds }), loadFinancialMetrics({ boutiqueId: boutique.id, ...prevBounds })]).then(([a,b]) => { if (!cancelled) { setMetrics(a); setPrevious(b); } }).catch(e => { if (!cancelled) setError(e instanceof Error ? e.message : "Rapport indisponible"); }); return () => { cancelled = true; }; }, [boutique.id, bounds.from, bounds.to, prevBounds.from, prevBounds.to]);

  async function toggle(section: Section) {
    if (open === section) { setOpen(null); return; } setOpen(section);
    try { setSectionLoading(section); setError("");
      if (section === "sales" && !sales) setSales(await loadSalesProductReport({ boutiqueId: boutique.id, ...bounds }));
      if (section === "team" && !team) setTeam(await loadEmployeePerformanceReport({ boutiqueId: boutique.id, ...bounds }));
      if (section === "stock" && !stock) setStock(await loadStockInventoryReport({ boutiqueId: boutique.id, ...bounds, dormantDays }));
      if (section === "clients" && !clients) setClients(await loadClientReport({ boutiqueId: boutique.id, ...bounds }));
      if (section === "finance" && !sales) setSales(await loadSalesProductReport({ boutiqueId: boutique.id, ...bounds }));
    } catch (e) { setError(e instanceof Error ? e.message : "Détail indisponible"); } finally { setSectionLoading(null); }
  }
  async function refreshStock(days: number) { setDormantDays(days); if (open !== "stock") return; setSectionLoading("stock"); try { setStock(await loadStockInventoryReport({ boutiqueId: boutique.id, ...bounds, dormantDays: days })); } finally { setSectionLoading(null); } }

  const rows = useMemo(() => (sales?.products ?? []).filter(r => category === "all" || (r.category_id || "") === category).sort((a,b) => sort === "product_name" ? a.product_name.localeCompare(b.product_name) : Number(b[sort]) - Number(a[sort])), [sales, category, sort]);
  const maxProduct = Math.max(1, ...rows.slice(0,5).map(r => r.invoiced_revenue)); const maxEmployee = Math.max(1, ...(team?.employees ?? []).slice(0,5).map(r => r.invoiced_revenue));
  const dormant = (stock?.products ?? []).filter(r => r.dormant && r.current_stock > 0); const lowRotation = (stock?.products ?? []).filter(r => r.rotation_class === "lente" || r.rotation_class === "dormant"); const overdue = (clients?.clients ?? []).filter(r => r.overdue_global > 0);
  const periodBtns: Array<{id: DashPeriod; label: string}> = [{id:"jour",label:"Aujourd'hui"},{id:"semaine",label:"7 jours"},{id:"mois",label:"Mois"},{id:"custom",label:"Personnalisé"}];

  return <div data-screen-source="canonical-report-v7-ui" className="space-y-4 pb-24">
    <header className="sticky top-2 z-20 rounded-2xl border border-border bg-background/95 p-3 shadow-sm backdrop-blur"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex items-center gap-2"><h1 className="text-xl font-black tracking-tight">Rapport</h1><span className="rounded-full bg-muted px-2.5 py-1 text-[11px] font-bold text-muted-foreground">{boutique.nom}</span></div><p className="mt-1 text-xs text-muted-foreground">Résumé d'abord · détails chargés à la demande</p></div><div className="flex gap-1 overflow-x-auto rounded-xl bg-muted/70 p-1">{periodBtns.map(x => <button key={x.id} onClick={() => setPeriod(x.id)} className="shrink-0 rounded-lg px-3 py-2 text-xs font-bold" style={{background:period===x.id?RC:"transparent",color:period===x.id?"#fff":"#6b7280"}}>{x.label}</button>)}</div></div>{period === "custom" && <div className="mt-3 grid grid-cols-2 gap-2 border-t border-border pt-3"><input aria-label="Date de début" type="date" value={customFrom} onChange={e=>setCustomFrom(e.target.value)} className={inputCls}/><input aria-label="Date de fin" type="date" value={customTo} onChange={e=>setCustomTo(e.target.value)} className={inputCls}/></div>}</header>
    {error && <div className="rounded-xl border border-red-200 bg-red-50 px-3 py-2 text-xs font-semibold text-red-700">{error}</div>}
    <ReportKpiBand metrics={metrics} previous={previous} canSeeMargin={canSeeMargin}/>
    <div className="flex items-center justify-between rounded-xl border border-border bg-card px-4 py-3"><div><p className="text-xs font-bold text-muted-foreground">Impayé sur la période</p><p className="text-[11px] text-muted-foreground">Créances des factures sélectionnées</p></div><p className={`text-base font-black ${(metrics?.period_outstanding ?? 0)>0.005?"text-red-600":"text-muted-foreground"}`}>{fmt(metrics?.period_outstanding ?? 0)}</p></div>

    <div className="space-y-2">
      <Accordion title="Ventes" subtitle="Quels produits portent mon chiffre d’affaires ?" icon={<ReceiptText size={17}/>} active={open==="sales"} onClick={()=>void toggle("sales")} color={RC}>{sectionLoading==="sales"?<Loading/>:<SalesReportSection report={sales} metrics={metrics} canSeeMargin={canSeeMargin}/>}</Accordion>
      {canSeeMargin && <Accordion title="Équipe" subtitle="Qui contribue le plus aux ventes ?" icon={<Users size={17}/>} active={open==="team"} onClick={()=>void toggle("team")} color={RC}>{sectionLoading==="team"?<Loading/>:<TeamSection report={team} max={maxEmployee}/>}</Accordion>}
      <Accordion title="Stock" subtitle="Où mon capital est-il immobilisé ?" icon={<Boxes size={17}/>} active={open==="stock"} onClick={()=>void toggle("stock")} color={RC}>{sectionLoading==="stock"?<Loading/>:<StockSection report={stock} dormant={dormant} lowRotation={lowRotation} days={dormantDays} onDays={d=>void refreshStock(d)} canSeeMargin={canSeeMargin}/>}</Accordion>
      <Accordion title="Clients" subtitle="Qui achète le plus et qui me doit de l’argent ?" icon={<WalletCards size={17}/>} active={open==="clients"} onClick={()=>void toggle("clients")} color={RC}>{sectionLoading==="clients"?<Loading/>:<ClientSection report={clients} overdue={overdue}/>}</Accordion>
      <Accordion title="Financier" subtitle="La période crée-t-elle de la marge et de la trésorerie ?" icon={<BarChart3 size={17}/>} active={open==="finance"} onClick={()=>void toggle("finance")} color={RC}>{sectionLoading==="finance"?<Loading/>:<FinancialDeepReportSection metrics={metrics} salesReport={sales} canSeeMargin={canSeeMargin} color={RC}/>}</Accordion>
    </div>
    <div className="rounded-2xl border border-border bg-card p-4"><div className="flex items-center gap-2"><Download size={16} style={{color:RC}}/><div><p className="text-sm font-bold">Exports</p><p className="text-xs text-muted-foreground">Les exports PDF/CSV seront regroupés ici au jalon Export, séparés de l’analyse.</p></div></div></div>
  </div>;
}

function Accordion({title,subtitle,icon,active,onClick,color,children}:{title:string;subtitle:string;icon:React.ReactNode;active:boolean;onClick:()=>void;color:string;children:React.ReactNode}) { return <section className="overflow-hidden rounded-2xl border border-border bg-card"><button type="button" aria-expanded={active} onClick={onClick} className="flex w-full items-center justify-between gap-3 p-4 text-left"><div className="flex items-center gap-3"><span style={{color}}>{icon}</span><div><p className="text-sm font-black">{title}</p><p className="text-xs text-muted-foreground">{subtitle}</p></div></div><ChevronDown size={17} className={`text-muted-foreground transition-transform ${active?"rotate-180":""}`}/></button>{active&&<div className="border-t border-border p-4">{children}</div>}</section>; }
function Loading(){return <div className="py-8 text-center text-xs font-semibold text-muted-foreground">Chargement du détail…</div>}
function Mini({label,value,tone=""}:{label:string;value:string;tone?:string}){return <div className="rounded-xl bg-muted/35 p-3"><p className="text-[10px] font-bold uppercase text-muted-foreground">{label}</p><p className={`mt-1 text-lg font-black ${tone}`}>{value}</p></div>}
function Bars({items,max}:{items:Array<{name:string;value:number}>;max:number}){return <div className="space-y-3 rounded-xl border border-border p-3">{items.map(x=><div key={x.name}><div className="mb-1 flex justify-between gap-3 text-xs"><span className="truncate font-bold">{x.name}</span><span className="font-black">{fmt(x.value)}</span></div><div className="h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-foreground/70" style={{width:`${Math.max(2,x.value/max*100)}%`}}/></div></div>)}</div>}
function SalesSection({report,rows,category,setCategory,sort,setSort,max,canSeeMargin}:{report:SalesProductReport|null;rows:SalesProductReport["products"];category:string;setCategory:(v:string)=>void;sort:SortKey;setSort:(v:SortKey)=>void;max:number;canSeeMargin:boolean}){if(!report)return <Loading/>; const top=rows.slice(0,5);return <div className="space-y-4"><div className="grid grid-cols-2 gap-2 md:grid-cols-4"><Mini label="CA produits" value={fmt(report.invoiced_revenue)}/><Mini label="Produits vendus" value={`${rows.length}`}/><Mini label="Top produit" value={top[0]?.product_name??"—"}/>{canSeeMargin&&<Mini label="Marge top produit" value={top[0]?.realized_margin_fifo==null?"—":fmt(top[0].realized_margin_fifo)}/>}</div><Bars max={max} items={top.map(r=>({name:r.product_name,value:r.invoiced_revenue}))}/><div className="flex justify-end"><select value={category} onChange={e=>setCategory(e.target.value)} className="rounded-lg border border-border bg-background px-2 py-1.5 text-xs font-bold"><option value="all">Toutes catégories</option>{report.categories.map(c=><option key={c.id||"none"} value={c.id}>{c.name}</option>)}</select></div><div className="max-h-[420px] overflow-auto rounded-xl border border-border"><table className="w-full text-xs"><thead className="sticky top-0 bg-muted"><tr><th className="px-3 py-2 text-left"><button onClick={()=>setSort("product_name")}>Produit {sort==="product_name"?"↓":""}</button></th><th className="px-3 py-2 text-right"><button onClick={()=>setSort("quantity")}>Qté {sort==="quantity"?"↓":""}</button></th><th className="px-3 py-2 text-right"><button onClick={()=>setSort("invoiced_revenue")}>CA {sort==="invoiced_revenue"?"↓":""}</button></th>{canSeeMargin&&<th className="px-3 py-2 text-right">Marge</th>}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.product_id} className={i%2?"bg-muted/20":""}><td className="px-3 py-2.5 font-bold">{r.product_name}<div className="text-[10px] font-normal text-muted-foreground">{r.category_name}</div></td><td className="px-3 py-2.5 text-right">{r.quantity}</td><td className="px-3 py-2.5 text-right font-black">{fmt(r.invoiced_revenue)}</td>{canSeeMargin&&<td className="px-3 py-2.5 text-right">{r.realized_margin_fifo==null?"—":fmt(r.realized_margin_fifo)}</td>}</tr>)}</tbody></table></div></div>}
function TeamSection({report,max}:{report:EmployeePerformanceReport|null;max:number}){if(!report)return <Loading/>; const rows=[...report.employees].sort((a,b)=>b.invoiced_revenue-a.invoiced_revenue); const sales=rows.reduce((s,r)=>s+r.sales_count,0);return <div className="space-y-4"><div className="grid grid-cols-2 gap-2 md:grid-cols-3"><Mini label="Équipe active" value={`${rows.length}`}/><Mini label="Ventes attribuées" value={`${sales}`}/><Mini label="Leader CA" value={rows[0]?.operator_name??"—"}/></div><Bars max={max} items={rows.slice(0,5).map(r=>({name:r.operator_name,value:r.invoiced_revenue}))}/><div className="overflow-auto rounded-xl border border-border"><table className="w-full text-xs"><thead className="bg-muted"><tr><th className="px-3 py-2 text-left">Employé</th><th className="px-3 py-2 text-right">CA</th><th className="px-3 py-2 text-right">Ventes</th><th className="px-3 py-2 text-right">Panier</th></tr></thead><tbody>{rows.map((r,i)=><tr key={r.operator_id??"none"} className={i%2?"bg-muted/20":""}><td className="px-3 py-2.5 font-bold">{r.operator_name}</td><td className="px-3 py-2.5 text-right font-black">{fmt(r.invoiced_revenue)}</td><td className="px-3 py-2.5 text-right">{r.sales_count}</td><td className="px-3 py-2.5 text-right">{fmt(r.average_basket)}</td></tr>)}</tbody></table></div></div>}
function StockSection({report,dormant,lowRotation,days,onDays,canSeeMargin}:{report:StockInventoryReport|null;dormant:StockInventoryReport["products"];lowRotation:StockInventoryReport["products"];days:number;onDays:(n:number)=>void;canSeeMargin:boolean}){if(!report)return <Loading/>;return <div className="space-y-4"><div className="grid grid-cols-2 gap-2 md:grid-cols-4"><Mini label="Produits dormants" value={`${dormant.length}`} tone={dormant.length?"text-amber-600":""}/><Mini label="Rotation lente" value={`${lowRotation.length}`}/>{canSeeMargin&&<Mini label="Valeur stock FIFO" value={fmt(report.stock_value_fifo??0)}/>}<div className="rounded-xl bg-muted/35 p-3"><p className="text-[10px] font-bold uppercase text-muted-foreground">Seuil dormant</p><input aria-label="Seuil produits dormants" type="number" inputMode="numeric" min={1} max={3650} value={days} onChange={e=>onDays(Math.max(1,Math.min(3650,+e.target.value||60)))} className="mt-1 w-20 rounded-lg border border-border bg-background px-2 py-1 text-sm font-black"/></div></div><div className="rounded-xl border border-border p-3"><div className="mb-3 flex items-center gap-2"><PackageSearch size={15} className="text-amber-600"/><p className="text-xs font-black">Stock dormant à traiter</p></div>{dormant.length===0?<p className="text-xs text-muted-foreground">Aucun stock dormant.</p>:dormant.slice(0,8).map(r=><div key={r.product_id} className="flex justify-between border-t border-border py-2 text-xs first:border-0"><span className="font-bold">{r.product_name}</span><span>Stock <b>{r.current_stock}</b></span></div>)}</div></div>}
function ClientSection({report,overdue}:{report:ClientReport|null;overdue:ClientReport["clients"]}){if(!report)return <Loading/>; const rows=[...report.clients].sort((a,b)=>b.invoiced_revenue-a.invoiced_revenue); const max=Math.max(1,...rows.slice(0,5).map(r=>r.invoiced_revenue));return <div className="space-y-4"><div className="grid grid-cols-2 gap-2 md:grid-cols-4"><Mini label="Clients actifs" value={`${report.active_clients_period}`}/><Mini label="Encours global" value={fmt(report.customer_outstanding_global)} tone={report.customer_outstanding_global>0?"text-red-600":""}/><Mini label="Clients en retard" value={`${report.clients_overdue}`} tone={report.clients_overdue>0?"text-red-600":""}/><Mini label="Retard total" value={fmt(report.overdue_global)} tone={report.overdue_global>0?"text-red-600":""}/></div><Bars max={max} items={rows.slice(0,5).map(r=>({name:r.client_name,value:r.invoiced_revenue}))}/>{overdue.length>0&&<div className="rounded-xl border border-red-200 bg-red-50 p-3"><p className="mb-2 text-xs font-black text-red-700">Créances en retard</p>{overdue.slice(0,8).map(r=><div key={r.client_id} className="flex justify-between border-t border-red-100 py-2 text-xs first:border-0"><span className="font-bold">{r.client_name}</span><span className="font-black text-red-700">{fmt(r.overdue_global)}</span></div>)}</div>}</div>}
