import React, { useEffect, useState } from "react";
import { ArrowRightLeft, Check, Loader2 } from "lucide-react";
import { toast } from "sonner";
import type { Boutique } from "../types";
import { acceptStockTransfer, createStockTransfer, getStockTransfers, type RelationalTransfer } from "../../lib/api";
import { productQty } from "../utils/inventory";

export function TransfersView({ boutique, allBoutiques }: { boutique: Boutique; allBoutiques: Boutique[] }) {
  const [destination, setDestination] = useState("");
  const [productId, setProductId] = useState("");
  const [qty, setQty] = useState("");
  const [note, setNote] = useState("");
  const [items, setItems] = useState<Array<{ productId:number; qty:number }>>([]);
  const [transfers, setTransfers] = useState<RelationalTransfer[]>([]);
  const [saving, setSaving] = useState(false);
  const products = boutique.products.filter((product) => productQty(product.id, boutique.entries) > 0);
  const destinations = allBoutiques.filter((item) => item.id !== boutique.id);
  const load = async () => { try { setTransfers(await getStockTransfers(boutique.id)); } catch (error) { toast.error(error instanceof Error ? error.message : "Transferts indisponibles"); } };
  useEffect(() => { void load(); }, [boutique.id]);
  const add = () => { const id = Number(productId), amount = Number(qty), product = products.find((item) => item.id === id); if (!product || !Number.isFinite(amount) || amount <= 0 || amount > productQty(id, boutique.entries)) return; setItems((previous) => [...previous.filter((item) => item.productId !== id), { productId:id, qty:amount }]); setProductId(""); setQty(""); };
  async function create() { if (!destination || !items.length || saving) return; setSaving(true); try { await createStockTransfer({ fromBoutiqueId:boutique.id, toBoutiqueId:destination, lines:items, note }); toast.success("Demande de transfert créée"); setItems([]); setDestination(""); setNote(""); await load(); } catch (error) { toast.error(error instanceof Error ? error.message : "Transfert impossible"); } finally { setSaving(false); } }
  async function accept(transferId: string) { if (saving) return; setSaving(true); try { await acceptStockTransfer(transferId); toast.success("Transfert accepté et stock mis à jour"); await load(); } catch (error) { toast.error(error instanceof Error ? error.message : "Acceptation impossible"); } finally { setSaving(false); } }
  return <div className="max-w-xl mx-auto space-y-5" data-screen-source="relational-transfers">
    <div className="rounded-3xl p-5 border border-border bg-card"><div className="flex gap-3 items-center"><ArrowRightLeft className="text-orange-600"/><div><h2 className="text-xl font-black">Transferts inter-boutiques</h2><p className="text-sm text-muted-foreground">Acceptation atomique : les deux stocks changent ensemble.</p></div></div></div>
    <div className="rounded-3xl p-5 border border-border bg-card space-y-3"><h3 className="font-black">Nouvelle demande</h3><select value={destination} onChange={(event)=>setDestination(event.target.value)} className="w-full rounded-xl border border-border bg-background p-3"><option value="">Boutique destinataire</option>{destinations.map((item)=><option key={item.id} value={item.id}>{item.nom}</option>)}</select><div className="grid grid-cols-[1fr_100px] gap-2"><select value={productId} onChange={(event)=>setProductId(event.target.value)} className="rounded-xl border border-border bg-background p-3"><option value="">Produit</option>{products.map((item)=><option key={item.id} value={item.id}>{item.nom} ({productQty(item.id,boutique.entries)} {item.unit})</option>)}</select><input type="number" min="0" step="any" value={qty} onChange={(event)=>setQty(event.target.value)} placeholder="Qté" className="rounded-xl border border-border bg-background p-3"/></div><button onClick={add} className="w-full rounded-xl border border-orange-300 py-2 font-bold text-orange-700">Ajouter</button>{items.map((item)=>{const product=boutique.products.find((p)=>p.id===item.productId);return <div key={item.productId} className="flex justify-between text-sm"><span>{product?.nom}</span><button onClick={()=>setItems((previous)=>previous.filter((line)=>line.productId!==item.productId))} className="font-bold text-red-600">Retirer</button><span>{item.qty} {product?.unit}</span></div>;})}<input value={note} onChange={(event)=>setNote(event.target.value)} placeholder="Note (facultative)" className="w-full rounded-xl border border-border bg-background p-3"/><button onClick={create} disabled={saving || !destination || !items.length} className="w-full rounded-2xl bg-orange-600 py-4 font-black text-white disabled:opacity-50">{saving ? "Enregistrement…" : "Envoyer la demande"}</button></div>
    <div className="rounded-3xl p-5 border border-border bg-card space-y-3"><h3 className="font-black">Historique</h3>{transfers.length===0?<p className="text-sm text-muted-foreground">Aucun transfert.</p>:transfers.map((transfer)=>{const incoming=transfer.to_boutique_id===boutique.id;return <div key={transfer.id} className="rounded-2xl border border-border p-3 text-sm"><div className="flex justify-between font-bold"><span>{incoming?"Reçu":"Envoyé"}</span><span>{transfer.status}</span></div><p>{transfer.lines.map((line)=>`${line.product_name} · ${line.qty} ${line.unit}`).join(", ")}</p>{incoming&&transfer.status==="pending"&&<button onClick={()=>void accept(transfer.id)} disabled={saving} className="mt-2 flex items-center gap-2 rounded-xl bg-emerald-600 px-3 py-2 font-bold text-white"><Check size={16}/>{saving?<Loader2 className="animate-spin" size={16}/>:"Accepter"}</button>}</div>;})}</div>
  </div>;
}
