from pathlib import Path


def replace_once(text: str, old: str, new: str, label: str) -> str:
    if old not in text:
        raise RuntimeError(f"anchor missing: {label}")
    return text.replace(old, new, 1)

# API wrapper for atomic FIFO consumption of existing client credit.
path = Path("src/lib/api.ts")
s = path.read_text()
anchor = '''export async function recordClientPayment(params: { boutiqueId:string; clientId:number; amount:number; paymentMethod:string; paymentDate:string }) {\n'''
wrapper = '''export async function applyClientAdvanceFifo(params: { boutiqueId:string; clientId:number; amount?:number }) {\n  return dataRequest<{\n    client_id:number; requested_amount:number; applied_amount:number; remaining_due:number; remaining_advance:number;\n    allocations:Array<{ invoice_id:string; amount:number; acompte:number; status:string; stock_deducted:boolean; payment:{ id:number; amount:number; payment_method:string; paid_at:string; operator_id:string; operator_name:string; batch_id:string; source:\"client_advance\" }; advance_allocations:Array<{advance_id:number;amount:number}> }>;\n  }>(\"rpc/apply_client_advance_fifo\", {\n    method:\"POST\", headers:{ Prefer:\"return=representation\" },\n    body:JSON.stringify({ p_boutique_id:params.boutiqueId, p_client_id:params.clientId, p_idempotency_key:crypto.randomUUID(), p_amount:params.amount ?? null }),\n  });\n}\n\n'''
if "export async function applyClientAdvanceFifo(" not in s:
    s = replace_once(s, anchor, wrapper + anchor, "api credit fifo wrapper")
path.write_text(s)

# Client workspace payment modal: offer existing credit as an explicit non-cash payment mode.
path = Path("src/app/screens/ClientsView.tsx")
s = path.read_text()
old_import = 'import { applyClientAdvanceToInvoice, cancelPendingInvoice, createClient, deleteClientIfUnused, recordClientPayment, updateClientContact, updateClientPaymentTerms, updateClientProfile, WHOLESALE_MARKER } from "../../lib/api";'
new_import = 'import { applyClientAdvanceFifo, applyClientAdvanceToInvoice, cancelPendingInvoice, createClient, deleteClientIfUnused, recordClientPayment, updateClientContact, updateClientPaymentTerms, updateClientProfile, WHOLESALE_MARKER } from "../../lib/api";'
if "applyClientAdvanceFifo" not in s:
    s = replace_once(s, old_import, new_import, "client api import")

submit_anchor = '''      setSubmittingPayment(true);\n      try {\n        const result = await recordClientPayment({\n          boutiqueId:boutique.id,\n          clientId:c.id,\n          amount:requested,\n          paymentMethod,\n          paymentDate,\n        });\n'''
submit_new = '''      setSubmittingPayment(true);\n      try {\n        if (paymentMethod === "Avoir client") {\n          if (totalAvoir <= 0) throw new Error("Aucun avoir client disponible");\n          if (requested > totalAvoir + 0.01) throw new Error(`Avoir disponible insuffisant : ${fmt(totalAvoir)}`);\n          if (requested > totalImpayé + 0.01) throw new Error(`Le montant dépasse le solde dû : ${fmt(totalImpayé)}`);\n          const creditResult = await applyClientAdvanceFifo({ boutiqueId:boutique.id, clientId:c.id, amount:requested });\n          const invoiceAllocation = new Map(creditResult.allocations.map(allocation => [allocation.invoice_id, allocation]));\n          const advanceAllocation = new Map<number, number>();\n          creditResult.allocations.forEach(allocation => allocation.advance_allocations.forEach(item => advanceAllocation.set(item.advance_id, (advanceAllocation.get(item.advance_id) ?? 0) + item.amount)));\n          const updatedInvoices = boutique.invoices.map((invoice): Invoice => {\n            const allocation = invoiceAllocation.get(invoice.id);\n            if (!allocation) return invoice;\n            return {\n              ...invoice,\n              clientId:c.id,\n              acompte:allocation.acompte,\n              status:allocation.status === "payée" ? "payé" : "acompte",\n              paymentMethod:"Avoir client",\n              payments:[...(invoice.payments ?? []), {\n                id:allocation.payment.id, amount:allocation.payment.amount, paymentMethod:"Avoir client", paidAt:allocation.payment.paid_at,\n                operatorId:allocation.payment.operator_id, operatorName:allocation.payment.operator_name, batchId:allocation.payment.batch_id, source:"client_advance",\n              }],\n            };\n          });\n          onUpdate({\n            invoices:updatedInvoices,\n            clientAdvances:(boutique.clientAdvances ?? []).map(advance => ({ ...advance, allocatedAmount:(advance.allocatedAmount ?? 0) + (advanceAllocation.get(advance.id) ?? 0) })),\n          });\n          logAction("Avoir utilisé", `${c.nom} · ${fmt(creditResult.applied_amount)} · ${creditResult.allocations.length} facture(s)`, "🎟️");\n          setPaymentSummary({ applied:creditResult.applied_amount, advance:0 });\n          setPaymentDone(true);\n          setTimeout(() => {\n            setPaymentModal(false); setPaymentAmount(""); setPaymentMethod("Espèces"); setPaymentDone(false); setPaymentSummary(null); setSubmittingPayment(false);\n          }, 1000);\n          return;\n        }\n        const result = await recordClientPayment({\n          boutiqueId:boutique.id,\n          clientId:c.id,\n          amount:requested,\n          paymentMethod,\n          paymentDate,\n        });\n'''
if "const creditResult = await applyClientAdvanceFifo" not in s:
    s = replace_once(s, submit_anchor, submit_new, "client credit submit branch")

payment_methods_anchor = '''          <Field label="MODE DE PAIEMENT">\n            <div className="grid grid-cols-2 gap-2">{PAYMENT_METHODS.map(method=><button key={method} onClick={()=>setPaymentMethod(method)} className="py-2.5 rounded-xl text-xs font-bold" style={{background:paymentMethod===method?CC:"#EEE9D8",color:paymentMethod===method?"#fff":"#6b7280"}}>{PM_ICON[method]} {method}</button>)}</div>\n          </Field>\n          <Field label="DATE DU PAIEMENT"><input type="date" value={paymentDate} onChange={e=>setPaymentDate(e.target.value)} className={inputCls}/></Field>\n'''
payment_methods_new = '''          <Field label="MODE DE PAIEMENT">\n            <div className="grid grid-cols-2 gap-2">\n              {PAYMENT_METHODS.map(method=><button key={method} onClick={()=>setPaymentMethod(method)} className="py-2.5 rounded-xl text-xs font-bold" style={{background:paymentMethod===method?CC:"#EEE9D8",color:paymentMethod===method?"#fff":"#6b7280"}}>{PM_ICON[method]} {method}</button>)}\n              {totalAvoir>0&&<button type="button" onClick={()=>{setPaymentMethod("Avoir client");setPaymentAmount(String(Math.min(totalAvoir,totalImpayé)));}} className="py-2.5 rounded-xl text-xs font-bold" style={{background:paymentMethod==="Avoir client"?SEM.success.accent:SEM.success.bg,color:paymentMethod==="Avoir client"?"#fff":SEM.success.accent}}>🎟️ Avoir client · {fmt(totalAvoir)}</button>}\n            </div>\n            {paymentMethod==="Avoir client"&&<p className="mt-2 rounded-xl px-3 py-2 text-xs font-semibold" style={{background:SEM.success.bg,color:SEM.success.accent}}>Cet avoir a déjà été encaissé auparavant. Son utilisation règle les factures les plus anciennes sans créer une nouvelle entrée de caisse. Maximum utilisable : {fmt(Math.min(totalAvoir,totalImpayé))}.</p>}\n          </Field>\n          {paymentMethod!=="Avoir client"&&<Field label="DATE DU PAIEMENT"><input type="date" value={paymentDate} onChange={e=>setPaymentDate(e.target.value)} className={inputCls}/></Field>}\n'''
if "Avoir client · {fmt(totalAvoir)}" not in s:
    s = replace_once(s, payment_methods_anchor, payment_methods_new, "client payment methods")

invoice_payment_anchor = '''          {canCollectPayment && invoiceRemainingAmount(viewedInvoice)>0 && <button type="button" onClick={()=>{setPaymentAmount(String(invoiceRemainingAmount(viewedInvoice)));setViewedInvoice(null);setPaymentSummary(null);setPaymentModal(true);}} className="w-full rounded-xl bg-emerald-600 py-3 text-sm font-black text-white">Enregistrer un versement</button>}\n'''
invoice_payment_new = '''          {canCollectPayment && invoiceRemainingAmount(viewedInvoice)>0 && totalAvoir>0 && <button type="button" onClick={()=>void applyAdvanceToInvoice(viewedInvoice)} disabled={!!applyingAdvanceInvoiceId} className="w-full rounded-xl py-3 text-sm font-black disabled:opacity-50" style={{background:SEM.success.bg,color:SEM.success.accent}}>🎟️ Utiliser l'avoir disponible ({fmt(Math.min(totalAvoir,invoiceRemainingAmount(viewedInvoice)))})</button>}\n          {canCollectPayment && invoiceRemainingAmount(viewedInvoice)>0 && <button type="button" onClick={()=>{setPaymentMethod("Espèces");setPaymentAmount(String(invoiceRemainingAmount(viewedInvoice)));setViewedInvoice(null);setPaymentSummary(null);setPaymentModal(true);}} className="w-full rounded-xl bg-emerald-600 py-3 text-sm font-black text-white">Enregistrer un versement</button>}\n'''
if "Utiliser l'avoir disponible" not in s:
    s = replace_once(s, invoice_payment_anchor, invoice_payment_new, "invoice credit action")
path.write_text(s)

# CI: forbid future explicit anonymous execution grants on RPCs/migrations.
path = Path(".github/workflows/ci.yml")
s = path.read_text()
ci_anchor = '''      - name: Verify hardened session storage\n        shell: bash\n'''
ci_step = '''      - name: Prevent anonymous privileged RPC grants\n        shell: bash\n        run: |\n          set -euo pipefail\n          if grep -RIniE 'grant[[:space:]]+execute.*to[[:space:]]+(public|anon)' supabase/migrations; then\n            echo 'A migration grants RPC execution to PUBLIC/anon. Privileged RPCs must default-deny anonymous callers.' >&2\n            exit 1\n          fi\n\n'''
if "Prevent anonymous privileged RPC grants" not in s:
    s = replace_once(s, ci_anchor, ci_step + ci_anchor, "CI anonymous RPC guard")
path.write_text(s)
