from pathlib import Path
p=Path('src/app/screens/ClientsView.tsx')
s=p.read_text()
s=s.replace("const remaining = invoiceRemainingAmount(inv);", "const remaining = isReturn ? 0 : invoiceRemainingAmount(inv);")
s=s.replace(
'''<div className="text-right flex-shrink-0"><p className="font-black text-sm" style={{ fontFamily:"'Nunito',sans-serif" }}>{fmt(inv.montant)}</p>{paid>0&&<p className="text-xs font-semibold" style={{ color:SEM.success.accent }}>✓ {fmt(paid)}</p>}{remaining>0&&<p className="text-xs font-semibold" style={{ color:SEM.warning.accent }}>⏳ {fmt(remaining)}</p>}</div>''',
'''<div className="text-right flex-shrink-0"><p className="font-black text-sm" style={{ fontFamily:"'Nunito',sans-serif" }}>{fmt(inv.montant)}</p>{isReturn?<>{Number(inv.returnReceivableReduction??0)>0&&<p className="text-[11px] font-semibold text-amber-700">Créance −{fmt(Number(inv.returnReceivableReduction))}</p>}{Number(inv.returnCreditRestore??0)>0&&<p className="text-[11px] font-semibold" style={{color:SEM.success.accent}}>Avoir +{fmt(Number(inv.returnCreditRestore))}</p>}{Number(inv.returnRefundAmount??0)>0&&<p className="text-[11px] font-semibold text-red-700">Remboursé {fmt(Number(inv.returnRefundAmount))}</p>}</>:<>{paid>0&&<p className="text-xs font-semibold" style={{ color:SEM.success.accent }}>✓ {fmt(paid)}</p>}{remaining>0&&<p className="text-xs font-semibold" style={{ color:SEM.warning.accent }}>⏳ {fmt(remaining)}</p>}</>}</div>''')
s=s.replace(
'''<div className="rounded-xl bg-red-50 px-3 py-2 text-xs font-semibold text-red-700">Sélectionnez les quantités dans l'unité vendue. L'avoir, le stock, la créance et le remboursement sont enregistrés dans une seule transaction.</div>''',
'''<div className="rounded-xl bg-red-50 px-3 py-2 text-xs font-semibold text-red-700">Sélectionnez les quantités dans l'unité vendue. Le retour remet le stock à jour et crée l'avoir de retour. Pour un client enregistré, aucune sortie d'argent n'est faite automatiquement.</div>''')
old='''<div className="mt-3 grid grid-cols-3 gap-2 text-center"><div className="rounded-xl bg-muted p-2"><p className="text-[10px] text-muted-foreground">TOTAL</p><p className="text-sm font-black">{fmt(viewedInvoice.montant)}</p></div><div className="rounded-xl bg-green-50 p-2"><p className="text-[10px] text-green-700">PAYÉ</p><p className="text-sm font-black text-green-700">{fmt(invoicePaidAmount(viewedInvoice))}</p></div><div className="rounded-xl bg-red-50 p-2"><p className="text-[10px] text-red-700">RESTE</p><p className="text-sm font-black text-red-700">{fmt(invoiceRemainingAmount(viewedInvoice))}</p></div></div>'''
new='''{viewedInvoice.type.toLowerCase()==="retour" ? <div className="mt-3 grid grid-cols-3 gap-2 text-center"><div className="rounded-xl bg-muted p-2"><p className="text-[10px] text-muted-foreground">AVOIR RETOUR</p><p className="text-sm font-black">{fmt(viewedInvoice.montant)}</p></div><div className="rounded-xl bg-amber-50 p-2"><p className="text-[10px] text-amber-700">CRÉANCE ANNULÉE</p><p className="text-sm font-black text-amber-700">{fmt(Number(viewedInvoice.returnReceivableReduction??0))}</p></div><div className="rounded-xl bg-green-50 p-2"><p className="text-[10px] text-green-700">AVOIR CLIENT</p><p className="text-sm font-black text-green-700">{fmt(Number(viewedInvoice.returnCreditRestore??0))}</p></div>{Number(viewedInvoice.returnRefundAmount??0)>0&&<div className="col-span-3 rounded-xl bg-red-50 p-2"><p className="text-[10px] text-red-700">REMBOURSÉ IMMÉDIATEMENT</p><p className="text-sm font-black text-red-700">{fmt(Number(viewedInvoice.returnRefundAmount))}</p></div>}</div> : <div className="mt-3 grid grid-cols-3 gap-2 text-center"><div className="rounded-xl bg-muted p-2"><p className="text-[10px] text-muted-foreground">TOTAL</p><p className="text-sm font-black">{fmt(viewedInvoice.montant)}</p></div><div className="rounded-xl bg-green-50 p-2"><p className="text-[10px] text-green-700">PAYÉ</p><p className="text-sm font-black text-green-700">{fmt(invoicePaidAmount(viewedInvoice))}</p></div><div className="rounded-xl bg-red-50 p-2"><p className="text-[10px] text-red-700">RESTE</p><p className="text-sm font-black text-red-700">{fmt(invoiceRemainingAmount(viewedInvoice))}</p></div></div>}'''
if old not in s: raise SystemExit('viewed return summary marker missing')
s=s.replace(old,new,1)
s=s.replace('🧾 {viewedInvoice.type.toLowerCase()==="retour" ? "Justificatif remboursement" : "Ticket caisse"}', '🧾 {viewedInvoice.type.toLowerCase()==="retour" ? (Number(viewedInvoice.returnRefundAmount??0)>0 ? "Justificatif remboursement" : "Justificatif avoir") : "Ticket caisse"}')
s=s.replace('{canCollectPayment && invoiceRemainingAmount(viewedInvoice)>0 && totalAvoir>0 && <button', '{canCollectPayment && viewedInvoice.type.toLowerCase() !== "retour" && invoiceRemainingAmount(viewedInvoice)>0 && totalAvoir>0 && <button')
s=s.replace('{canCollectPayment && invoiceRemainingAmount(viewedInvoice)>0 && <button', '{canCollectPayment && viewedInvoice.type.toLowerCase() !== "retour" && invoiceRemainingAmount(viewedInvoice)>0 && <button')
p.write_text(s)
