from pathlib import Path

# Factures: make returns a first-class visible document/filter, including client returns.
p=Path('src/app/screens/FacturesView.tsx'); s=p.read_text()
s=s.replace('''  const isClientRecordOnlyInvoice = (invoice: Invoice) => {\n    if (invoice.clientId == null) return false;''','''  const isClientRecordOnlyInvoice = (invoice: Invoice) => {\n    // Credit notes/returns are accounting documents and stay visible in Factures,\n    // even when the source sale belongs to a registered client.\n    if (invoice.type.toLowerCase() === "retour") return false;\n    if (invoice.clientId == null) return false;''',1)
s=s.replace('useState<InvoiceStatus|"all"|"impayé">(initialStatus ?? "all")','useState<InvoiceStatus|"all"|"impayé"|"retours">(initialStatus ?? "all")',1)
s=s.replace('''  const dayActive = dayFilterActive && !invSearch.trim();\n  const filtered = [...invoices]\n    .sort((a,b)=>(b.dateRaw??b.date).localeCompare(a.dateRaw??a.date))\n    .filter(i => !isClientRecordOnlyInvoice(i))\n    .filter(i => (statusFilter==="all"||statusFilter==="impayé"?statusFilter==="impayé"?UNPAID.includes(effectiveStatus(i)):true:effectiveStatus(i)===statusFilter)\n      && (i.client.toLowerCase().includes(invSearch.toLowerCase())||i.id.toLowerCase().includes(invSearch.toLowerCase()))\n      && (!dayActive||(i.dateRaw??"").slice(0,10)===selectedDay));\n  const pills: Array<{id:InvoiceStatus|"all"|"impayé";label:string;color:string}> = [''','''  const dayActive = dayFilterActive && !invSearch.trim() && statusFilter !== "retours";\n  const filtered = [...invoices]\n    .sort((a,b)=>(b.dateRaw??b.date).localeCompare(a.dateRaw??a.date))\n    .filter(i => !isClientRecordOnlyInvoice(i))\n    .filter(i => {\n      const matchesStatus = statusFilter === "all"\n        ? true\n        : statusFilter === "impayé"\n          ? UNPAID.includes(effectiveStatus(i))\n          : statusFilter === "retours"\n            ? i.type.toLowerCase() === "retour"\n            : effectiveStatus(i) === statusFilter;\n      return matchesStatus\n        && (i.client.toLowerCase().includes(invSearch.toLowerCase())||i.id.toLowerCase().includes(invSearch.toLowerCase()))\n        && (!dayActive||(i.dateRaw??"").slice(0,10)===selectedDay);\n    });\n  const pills: Array<{id:InvoiceStatus|"all"|"impayé"|"retours";label:string;color:string}> = [''',1)
s=s.replace('''    {id:"all",      label:"Tout",     color:SEM.neutral.accent},\n    {id:"impayé",   label:"Impayés",  color:SEM.danger.accent},''','''    {id:"all",      label:"Tout",     color:SEM.neutral.accent},\n    {id:"retours",  label:"↩ Retours / avoirs", color:"#dc2626"},\n    {id:"impayé",   label:"Impayés",  color:SEM.danger.accent},''',1)
s=s.replace('''onClick={()=>{setStatusFilter(s.id as InvoiceStatus|"all"|"impayé"); if (s.id==="impayé" || s.id==="en retard") setDayFilterActive(false);}}''','''onClick={()=>{setStatusFilter(s.id as InvoiceStatus|"all"|"impayé"|"retours"); if (s.id==="impayé" || s.id==="en retard" || s.id==="retours") setDayFilterActive(false);}}''',1)
s=s.replace('''{detailInv&&<Modal title={detailInv.id} color="#374151" onClose={()=>setDetailInv(null)}>''','''{detailInv&&<Modal title={detailInv.type === "Retour" ? `Avoir de retour ${detailInv.id}` : detailInv.id} color={detailInv.type === "Retour" ? "#dc2626" : "#374151"} onClose={()=>setDetailInv(null)}>''',1)
needle='''        {detailInv.lines&&detailInv.lines.length>0&&(\n          <div>'''
insert='''        {detailInv.type === "Retour" && detailInv.returnOfInvoiceId && (\n          <div className="rounded-xl px-3 py-2 text-xs font-black flex items-center gap-2" style={{background:"#fef2f2",color:"#b91c1c"}}>\n            <RotateCcw size={14}/> Retour sur facture {detailInv.returnOfInvoiceId}\n          </div>\n        )}\n        {detailInv.type !== "Retour" && (() => {\n          const linkedReturns = invoices.filter(item => item.returnOfInvoiceId === detailInv.id);\n          if (!linkedReturns.length) return null;\n          const returnedAmount = linkedReturns.reduce((sum,item)=>sum+item.montant,0);\n          return <div className="rounded-xl px-3 py-2 text-xs font-black flex items-center justify-between gap-2" style={{background:"#fef2f2",color:"#b91c1c"}}>\n            <span className="flex items-center gap-2"><RotateCcw size={14}/> {linkedReturns.length} retour{linkedReturns.length>1?"s":""} enregistré{linkedReturns.length>1?"s":""}</span>\n            <span>{fmt(returnedAmount)}</span>\n          </div>;\n        })()}\n        {detailInv.lines&&detailInv.lines.length>0&&(\n          <div>'''
if needle not in s: raise SystemExit('Factures detail insertion point not found')
s=s.replace(needle,insert,1)
p.write_text(s)

# Clients: visibly expose the return action and route into the existing transactional return flow.
p=Path('src/app/screens/ClientsView.tsx'); s=p.read_text()
s=s.replace('FilePlus, Wallet, CheckCircle, CalendarClock, Edit2, Trash2, FileText','FilePlus, Wallet, CheckCircle, CalendarClock, Edit2, Trash2, FileText, RotateCcw',1)
s=s.replace('''  const canSeeMargin = currentUser.isSuperAdmin || !!marginAssignment?.droits?.marges;''','''  const canSeeMargin = currentUser.isSuperAdmin || !!marginAssignment?.droits?.marges;\n  const canReturn = currentUser.isSuperAdmin || !!marginAssignment?.droits?.remboursement;''',1)
s=s.replace('''<div><p className="text-xs font-black tracking-wider text-muted-foreground">FACTURES & COMMANDES</p><p className="text-xs text-muted-foreground mt-0.5">Les plus récentes sont affichées en premier.</p></div>''','''<div><p className="text-xs font-black tracking-wider text-muted-foreground">FACTURES, COMMANDES & RETOURS</p><p className="text-xs text-muted-foreground mt-0.5">Ventes, avoirs de retour et commandes, du plus récent au plus ancien.</p></div>''',1)
s=s.replace('''              const canEdit = canCreateOrder && (canManageAnyPendingOrder || inv.operatorId === currentUser.id) && inv.origin === "client_profile" && inv.status === "en attente" && paid <= 0;''','''              const canEdit = canCreateOrder && (canManageAnyPendingOrder || inv.operatorId === currentUser.id) && inv.origin === "client_profile" && inv.status === "en attente" && paid <= 0;\n              const canReturnInvoice = canReturn && !isReturn && inv.status !== "annulée" && paid > 0 && (inv.lines?.length ?? 0) > 0;''',1)
s=s.replace('''{isReturn&&<span className="text-xs px-1.5 py-0.5 rounded font-bold" style={{ background:"#ef444415",color:"#ef4444" }}>Retour</span>}''','''{isReturn&&<span className="text-xs px-1.5 py-0.5 rounded font-bold inline-flex items-center gap-1" style={{ background:"#ef444415",color:"#ef4444" }}><RotateCcw size={10}/> Avoir de retour</span>}''',1)
s=s.replace('''                  {canEdit&&<button type="button" onClick={()=>{setEditingClientInvoice(inv);setOrderClient(c);}} className="rounded-lg px-2 py-2 text-[11px] font-black" style={{background:"#eff6ff",color:"#1d4ed8"}}>Modifier</button>}''','''                  {canReturnInvoice&&<button type="button" onClick={()=>onOpenInvoice(inv.id)} className="rounded-lg px-2 py-2 text-[11px] font-black inline-flex items-center gap-1" style={{background:"#fef2f2",color:"#dc2626"}} title="Retourner des articles"><RotateCcw size={12}/> Retour</button>}\n                  {canEdit&&<button type="button" onClick={()=>{setEditingClientInvoice(inv);setOrderClient(c);}} className="rounded-lg px-2 py-2 text-[11px] font-black" style={{background:"#eff6ff",color:"#1d4ed8"}}>Modifier</button>}''',1)
s=s.replace('''        {viewedInvoice&&<Modal title={`Facture ${viewedInvoice.id}`} color={CC} onClose={()=>setViewedInvoice(null)}>''','''        {viewedInvoice&&<Modal title={viewedInvoice.type.toLowerCase() === "retour" ? `Avoir de retour ${viewedInvoice.id}` : `Facture ${viewedInvoice.id}`} color={viewedInvoice.type.toLowerCase() === "retour" ? "#dc2626" : CC} onClose={()=>setViewedInvoice(null)}>''',1)
modal_action='''          {canCreateOrder && viewedInvoice.origin === "client_profile" && viewedInvoice.status === "en attente" && invoicePaidAmount(viewedInvoice) <= 0 && (canManageAnyPendingOrder || viewedInvoice.operatorId === currentUser.id) && <button type="button" onClick={()=>{setViewedInvoice(null);setEditingClientInvoice(viewedInvoice);setOrderClient(c);}} className="w-full rounded-xl bg-blue-50 py-3 text-sm font-black text-blue-700">Modifier la commande</button>}'''
modal_insert='''          {viewedInvoice.type.toLowerCase() === "retour" && viewedInvoice.returnOfInvoiceId && <div className="rounded-xl bg-red-50 px-3 py-2 text-xs font-black text-red-700 inline-flex items-center gap-2"><RotateCcw size={14}/> Retour sur facture {viewedInvoice.returnOfInvoiceId}</div>}\n          {canReturn && viewedInvoice.type.toLowerCase() !== "retour" && viewedInvoice.status !== "annulée" && invoicePaidAmount(viewedInvoice) > 0 && (viewedInvoice.lines?.length ?? 0) > 0 && <button type="button" onClick={()=>{const id=viewedInvoice.id;setViewedInvoice(null);onOpenInvoice(id);}} className="w-full rounded-xl bg-red-50 py-3 text-sm font-black text-red-700 inline-flex items-center justify-center gap-2"><RotateCcw size={16}/> Retourner des articles</button>}\n'''+modal_action
if modal_action not in s: raise SystemExit('Clients modal action insertion point not found')
s=s.replace(modal_action,modal_insert,1)
p.write_text(s)
