from pathlib import Path

# TYPES
p=Path('src/app/types.ts'); s=p.read_text()
s=s.replace('''export type ClientAdvance = {\n  id: number;\n  clientId: number;\n  amount: number;\n  allocatedAmount?: number;\n  paymentMethod: PaymentMethod;\n  paidAt: string;\n  recordedAt?: string;\n  operatorId?: string;\n  operatorName: string;\n  note?: string;\n};''','''export type ClientAdvance = {\n  id: number;\n  clientId: number;\n  amount: number;\n  allocatedAmount?: number;\n  paymentMethod: PaymentMethod;\n  paidAt: string;\n  recordedAt?: string;\n  operatorId?: string;\n  operatorName: string;\n  note?: string;\n};\n\nexport type ClientCreditRefund = {\n  id: number;\n  clientId: number;\n  amount: number;\n  paymentMethod: Exclude<PaymentMethod, "Avoir client">;\n  refundedAt: string;\n  date: string;\n  dateRaw: string;\n  operatorId?: string;\n  operatorName: string;\n  note?: string;\n};''')
s=s.replace('''  returnRefundAmount?: number; returnReceivableReduction?: number; returnCreditRestore?: number;''','''  returnRefundAmount?: number; returnReceivableReduction?: number; returnCreditRestore?: number; returnClientCreditAmount?: number;''')
s=s.replace('''  clientAdvances?: ClientAdvance[];''','''  clientAdvances?: ClientAdvance[];\n  clientCreditRefunds?: ClientCreditRefund[];''')
p.write_text(s)

# API
p=Path('src/lib/api.ts'); s=p.read_text()
s=s.replace('''      products:[], entries:[], suppliers:[], clients:[], clientAdvances:[], invoices:[], auditLog:[], charges:[], categories:[], productParams:[], caisseHistory:[],''','''      products:[], entries:[], suppliers:[], clients:[], clientAdvances:[], clientCreditRefunds:[], invoices:[], auditLog:[], charges:[], categories:[], productParams:[], caisseHistory:[],''')
s=s.replace('''    const [boutiques, categories, products, entries, clients, suppliers, invoices, payments, advances, charges, sessions, auditLogs, userScope] = await Promise.all([''','''    const [boutiques, categories, products, entries, clients, suppliers, invoices, payments, advances, creditRefunds, charges, sessions, auditLogs, userScope] = await Promise.all([''')
s=s.replace('''      dataRequest<any[]>(`invoice_payments?select=*${scoped()}&order=paid_at.asc`), dataRequest<any[]>(`client_advances?select=*${scoped()}&order=paid_at.desc,id.desc`), dataRequest<any[]>(`charges?select=*${scoped()}`),''','''      dataRequest<any[]>(`invoice_payments?select=*${scoped()}&order=paid_at.asc`), dataRequest<any[]>(`client_advances?select=*${scoped()}&order=paid_at.desc,id.desc`),\n      dataRequest<any[]>(`client_credit_refunds?select=*${scoped()}&order=refunded_at.desc,id.desc`), dataRequest<any[]>(`charges?select=*${scoped()}`),''')
anchor='''      clientAdvances: advances.filter(a => a.boutique_id === b.id).map(a => ({\n        id:Number(a.id), clientId:Number(a.client_id), amount:Number(a.amount),\n        allocatedAmount:Number(a.allocated_amount ?? 0),\n        paymentMethod:a.payment_method, paidAt:a.paid_at, recordedAt:a.recorded_at,\n        operatorId:a.operator_id ?? undefined, operatorName:a.operator_name, note:a.note ?? undefined,\n      })),'''
if anchor not in s: raise SystemExit('api clientAdvances anchor missing')
s=s.replace(anchor,anchor+'''\n      clientCreditRefunds: creditRefunds.filter(r => r.boutique_id === b.id).map(r => ({\n        id:Number(r.id), clientId:Number(r.client_id), amount:Number(r.amount), paymentMethod:r.payment_method,\n        refundedAt:r.refunded_at, date:day(r.refunded_at), dateRaw:r.refunded_at, recordedAt:r.recorded_at,\n        operatorId:r.operator_id ?? undefined, operatorName:r.operator_name, note:r.note ?? undefined,\n      })),''')
s=s.replace('''          returnCreditRestore:Number(i.return_credit_restore ?? 0),''','''          returnCreditRestore:Number(i.return_credit_restore ?? 0),\n          returnClientCreditAmount:Number(i.return_client_credit_amount ?? i.return_credit_restore ?? 0),''')
old='''export async function returnSale(params: { boutiqueId:string; invoiceId:string; lines:Array<{sourceLineId?:number;productId:number;qty:number}>; refundMethod:string }) {\n  return dataRequest<{\n    return_invoice_id:string; credit_note_number:number; source_invoice_id:string; total:number; returned_at:string; refund_method:string|null;\n    refund_amount:number; receivable_reduction:number; credit_restore:number; restored_advance_id:number|null;\n    payment:{ id:number; amount:number; payment_method:string; paid_at:string; operator_id:string; operator_name:string; batch_id:string; source:"invoice" } | null;\n  }>("rpc/return_sale", {\n    method:"POST", headers:{ Prefer:"return=representation" },\n    body:JSON.stringify({\n      p_boutique_id:params.boutiqueId,\n      p_invoice_id:params.invoiceId,\n      p_idempotency_key:crypto.randomUUID(),\n      p_lines:params.lines.map(line=>({ sourceLineId:line.sourceLineId ?? null, productId:line.productId, qty:line.qty })),\n      p_refund_method:params.refundMethod,\n    }),\n  });\n}'''
new='''export async function returnSale(params: { boutiqueId:string; invoiceId:string; lines:Array<{sourceLineId?:number;productId:number;qty:number}>; refundMethod?:string }) {\n  return dataRequest<{\n    return_invoice_id:string; credit_note_number:number; source_invoice_id:string; total:number; returned_at:string; registered_client:boolean; refund_method:string|null;\n    refund_amount:number; receivable_reduction:number; client_credit_amount:number; credit_restore:number; restored_advance_id:number|null;\n    payment:{ id:number; amount:number; payment_method:string; paid_at:string; operator_id:string; operator_name:string; batch_id:string; source:"invoice" } | null;\n  }>("rpc/return_sale", {\n    method:"POST", headers:{ Prefer:"return=representation" },\n    body:JSON.stringify({\n      p_boutique_id:params.boutiqueId,\n      p_invoice_id:params.invoiceId,\n      p_idempotency_key:crypto.randomUUID(),\n      p_lines:params.lines.map(line=>({ sourceLineId:line.sourceLineId ?? null, productId:line.productId, qty:line.qty })),\n      p_refund_method:params.refundMethod ?? null,\n    }),\n  });\n}\n\nexport async function refundClientCredit(params:{ boutiqueId:string; clientId:number; amount:number; paymentMethod:string; note?:string }) {\n  return dataRequest<{\n    refund_id:number; client_id:number; amount:number; payment_method:string; refunded_at:string; operator_id:string; operator_name:string; remaining_credit:number;\n    allocations:Array<{advance_id:number;amount:number}>;\n  }>("rpc/refund_client_credit_fifo", {\n    method:"POST", headers:{ Prefer:"return=representation" },\n    body:JSON.stringify({\n      p_boutique_id:params.boutiqueId, p_client_id:params.clientId, p_amount:normalizeMoney(params.amount),\n      p_payment_method:params.paymentMethod, p_idempotency_key:crypto.randomUUID(), p_note:params.note?.trim() || null,\n    }),\n  });\n}'''
if old not in s: raise SystemExit('api returnSale block missing')
s=s.replace(old,new)
p.write_text(s)

# CLIENTS
p=Path('src/app/screens/ClientsView.tsx'); s=p.read_text()
s=s.replace('''import { applyClientAdvanceFifo, applyClientAdvanceToInvoice, cancelPendingInvoice, createClient, deleteClientIfUnused, recordClientPayment, returnSale, updateClientContact, updateClientPaymentTerms, updateClientProfile, WHOLESALE_MARKER } from "../../lib/api";''','''import { applyClientAdvanceFifo, applyClientAdvanceToInvoice, cancelPendingInvoice, createClient, deleteClientIfUnused, recordClientPayment, refundClientCredit, returnSale, updateClientContact, updateClientPaymentTerms, updateClientProfile, WHOLESALE_MARKER } from "../../lib/api";''')
s=s.replace('''  const [clientReturnMethod, setClientReturnMethod] = useState<PaymentMethod>("Espèces");\n  const [clientReturnBusy, setClientReturnBusy] = useState(false);''','''  const [clientReturnBusy, setClientReturnBusy] = useState(false);\n  const [creditRefundOpen, setCreditRefundOpen] = useState(false);\n  const [creditRefundAmount, setCreditRefundAmount] = useState("");\n  const [creditRefundMethod, setCreditRefundMethod] = useState<PaymentMethod>("Espèces");\n  const [creditRefundBusy, setCreditRefundBusy] = useState(false);\n  const [creditRefundDone, setCreditRefundDone] = useState(false);''')
s=s.replace('''      setClientReturnQtys(quantities); setClientReturnMethod("Espèces"); setClientReturnDone(false); setClientReturnInv(invoice); setViewedInvoice(null);''','''      setClientReturnQtys(quantities); setClientReturnDone(false); setClientReturnInv(invoice); setViewedInvoice(null);''')
s=s.replace('''const persisted=await returnSale({boutiqueId:boutique.id,invoiceId:clientReturnInv.id,refundMethod:clientReturnMethod,lines:returnLines.map(line=>({sourceLineId:line.id,productId:line.productId,qty:line.qty}))});''','''const persisted=await returnSale({boutiqueId:boutique.id,invoiceId:clientReturnInv.id,lines:returnLines.map(line=>({sourceLineId:line.id,productId:line.productId,qty:line.qty}))});''')
s=s.replace('''          creditNoteNumber:persisted.credit_note_number,returnRefundAmount:Number(persisted.refund_amount??0),returnReceivableReduction:Number(persisted.receivable_reduction??0),returnCreditRestore:Number(persisted.credit_restore??0),''','''          creditNoteNumber:persisted.credit_note_number,returnRefundAmount:Number(persisted.refund_amount??0),returnReceivableReduction:Number(persisted.receivable_reduction??0),returnCreditRestore:Number(persisted.credit_restore??0),returnClientCreditAmount:Number(persisted.client_credit_amount??persisted.credit_restore??0),''')
s=s.replace('''        const restoredAdvance=persisted.credit_restore>0&&persisted.restored_advance_id&&clientReturnInv.clientId!=null?{\n          id:Number(persisted.restored_advance_id),clientId:clientReturnInv.clientId,amount:Number(persisted.credit_restore),allocatedAmount:0,paymentMethod:"Autre" as PaymentMethod,\n          paidAt:persisted.returned_at,recordedAt:persisted.returned_at,operatorId:currentUser.id,operatorName:currentUser.nom,note:`Avoir restauré par ${persisted.return_invoice_id} sur ${clientReturnInv.id}`,\n        }:null;''','''        const creditAmount=Number(persisted.client_credit_amount??persisted.credit_restore??0);\n        const restoredAdvance=creditAmount>0&&persisted.restored_advance_id&&clientReturnInv.clientId!=null?{\n          id:Number(persisted.restored_advance_id),clientId:clientReturnInv.clientId,amount:creditAmount,allocatedAmount:0,paymentMethod:"Autre" as PaymentMethod,\n          paidAt:persisted.returned_at,recordedAt:persisted.returned_at,operatorId:currentUser.id,operatorName:currentUser.nom,note:`Avoir créé par ${persisted.return_invoice_id} sur ${clientReturnInv.id}`,\n        }:null;''')
s=s.replace('''    const clientAdvances = (boutique.clientAdvances ?? []).filter(advance => advance.clientId === c.id)\n      .sort((a,b)=>b.paidAt.localeCompare(a.paidAt));''','''    const clientAdvances = (boutique.clientAdvances ?? []).filter(advance => advance.clientId === c.id)\n      .sort((a,b)=>b.paidAt.localeCompare(a.paidAt));\n    const clientCreditRefunds = (boutique.clientCreditRefunds ?? []).filter(refund => refund.clientId === c.id)\n      .sort((a,b)=>b.refundedAt.localeCompare(a.refundedAt));''')
s=s.replace('''    const totalEncaissé = ventes.reduce((s,i)=>s+invoicePaidAmount(i),0)-retours.reduce((s,i)=>s+invoicePaidAmount(i),0);''','''    const totalEncaissé = ventes.reduce((s,i)=>s+invoicePaidAmount(i),0)-retours.reduce((s,i)=>s+invoicePaidAmount(i),0)-clientCreditRefunds.reduce((s,r)=>s+r.amount,0);''')
s=s.replace('''    const paymentHistoryCount = clientPayments.length + clientAdvances.length;''','''    const paymentHistoryCount = clientPayments.length + clientAdvances.length + clientCreditRefunds.length;''')
insert_after='''    async function submitClientReturn() {'''
# refund helper inserted before submitClientPayment, where totalAvoir is already defined
anchor='''    async function submitClientPayment() {'''
refund_fn='''    async function submitCreditRefund() {\n      if (creditRefundBusy) return;\n      const amount=Number(creditRefundAmount)||0;\n      if (amount<=0 || amount>totalAvoir+0.01) return;\n      if (creditRefundMethod==="Avoir client") return;\n      setCreditRefundBusy(true);\n      try {\n        const result=await refundClientCredit({boutiqueId:boutique.id,clientId:c.id,amount,paymentMethod:creditRefundMethod,note:`Remboursement avoir client · ${c.nom}`});\n        const byAdvance=new Map<number,number>();\n        result.allocations.forEach(item=>byAdvance.set(item.advance_id,(byAdvance.get(item.advance_id)??0)+item.amount));\n        onUpdate({\n          clientAdvances:(boutique.clientAdvances??[]).map(advance=>({...advance,allocatedAmount:(advance.allocatedAmount??0)+(byAdvance.get(advance.id)??0)})),\n          clientCreditRefunds:[...(boutique.clientCreditRefunds??[]),{id:result.refund_id,clientId:c.id,amount:result.amount,paymentMethod:result.payment_method as Exclude<PaymentMethod,"Avoir client">,refundedAt:result.refunded_at,date:today(),dateRaw:result.refunded_at,operatorId:result.operator_id,operatorName:result.operator_name,note:`Remboursement avoir client · ${c.nom}`}],\n        });\n        logAction("Remboursement avoir client",`${c.nom} · ${fmt(result.amount)} · ${result.payment_method}`,"💸");\n        setCreditRefundDone(true);\n        setTimeout(()=>{setCreditRefundOpen(false);setCreditRefundDone(false);setCreditRefundBusy(false);setCreditRefundAmount("");setCreditRefundMethod("Espèces");},1200);\n      } catch(error) { setCreditRefundBusy(false); alert(error instanceof Error?error.message:"Remboursement impossible"); }\n    }\n\n'''
if anchor not in s: raise SystemExit('Clients payment helper anchor missing')
s=s.replace(anchor,refund_fn+anchor,1)
# Replace return modal refund method section with credit explanation.
old='''          {!clientReturnDone&&<div className="space-y-2"><p className="text-xs font-black text-muted-foreground">MODE DE REMBOURSEMENT SI UN REMBOURSEMENT EST DÛ</p><div className="grid grid-cols-2 gap-2">{PAYMENT_METHODS.map(method=><button key={method} type="button" onClick={()=>setClientReturnMethod(method)} className="rounded-xl px-3 py-3 text-sm font-bold" style={{background:clientReturnMethod===method?(PM_COLOR[method]??"#6b7280")+"18":"#f9fafb",color:clientReturnMethod===method?(PM_COLOR[method]??"#374151"):"#6b7280",border:clientReturnMethod===method?`2px solid ${(PM_COLOR[method]??"#6b7280")}55`:"2px solid transparent"}}>{PM_ICON[method]} {method}</button>)}</div><p className="text-xs text-muted-foreground">Le serveur annule d'abord la créance non encaissée, restaure ensuite un éventuel avoir client, puis rembourse seulement l'argent réellement encaissé.</p></div>}'''
new='''          {!clientReturnDone&&<div className="rounded-xl bg-emerald-50 px-3 py-2 text-xs font-semibold text-emerald-800">Pour un client enregistré, aucun moyen de remboursement n'est demandé ici. Le retour annule d'abord la créance éventuelle puis crédite le solde en avoir client. Un remboursement de cet avoir se fait ensuite séparément depuis la fiche client.</div>}'''
if old not in s: raise SystemExit('Clients return payment UI block missing')
s=s.replace(old,new,1)
# Add refund button to available credit card.
old='''            <p className="text-xl font-black" style={{color:SEM.success.accent,fontFamily:"'Nunito',sans-serif"}}>{fmt(totalAvoir)}</p>\n          </div>\n        </section>}'''
new='''            <div className="text-right"><p className="text-xl font-black" style={{color:SEM.success.accent,fontFamily:"'Nunito',sans-serif"}}>{fmt(totalAvoir)}</p>{canReturn&&<button type="button" onClick={()=>{setCreditRefundAmount(String(totalAvoir));setCreditRefundMethod("Espèces");setCreditRefundDone(false);setCreditRefundOpen(true);}} className="mt-2 rounded-lg bg-white px-3 py-1.5 text-xs font-black" style={{color:SEM.success.accent}}>Rembourser l'avoir</button>}</div>\n          </div>\n        </section>}'''
if old not in s: raise SystemExit('Clients credit card anchor missing')
s=s.replace(old,new,1)
# Add credit refund history block after advances.
needle='''          {clientAdvances.length>0&&<div className="mt-4 border-t border-border pt-4">'''
# We'll append a standalone refund block just before history closing marker.
marker='''          </>}\n        </section>}'''
refund_hist='''          {clientCreditRefunds.length>0&&<div className="mt-4 border-t border-border pt-4">\n            <p className="mb-3 text-xs font-black tracking-wider text-muted-foreground">REMBOURSEMENTS D'AVOIR</p>\n            <div className="space-y-2">{clientCreditRefunds.slice(0,20).map(refund=><div key={refund.id} className="flex items-center justify-between gap-3 text-xs"><div><p className="font-bold">💸 {refund.paymentMethod}</p><p className="text-muted-foreground">{formatPreciseDateTime(refund.refundedAt)} · {refund.operatorName}</p></div><p className="font-black text-red-600">− {fmt(refund.amount)}</p></div>)}</div>\n          </div>}\n'''
if marker not in s: raise SystemExit('Clients payment history close marker missing')
s=s.replace(marker,refund_hist+marker,1)
# Add refund modal before payment modal.
modal_anchor='''        {paymentModal&&<Modal title="Versement client"'''
refund_modal='''        {creditRefundOpen&&<Modal title="Rembourser l'avoir client" color={SEM.danger.accent} onClose={()=>{if(!creditRefundBusy)setCreditRefundOpen(false);}}>\n          <div className="rounded-xl bg-red-50 px-3 py-2 text-xs font-semibold text-red-700">Ce remboursement consomme l'avoir disponible du client. Il ne modifie pas l'avoir de retour d'origine.</div>\n          <Field label="MONTANT À REMBOURSER"><input value={creditRefundAmount} onChange={e=>setCreditRefundAmount(e.target.value)} type="number" min="0" max={totalAvoir} className={inputCls}/><p className="mt-1 text-xs text-muted-foreground">Disponible : {fmt(totalAvoir)}</p></Field>\n          <Field label="MOYEN DE REMBOURSEMENT"><div className="grid grid-cols-2 gap-2">{PAYMENT_METHODS.filter(method=>method!=="Avoir client").map(method=><button key={method} type="button" onClick={()=>setCreditRefundMethod(method)} className="rounded-xl px-3 py-3 text-sm font-bold" style={{background:creditRefundMethod===method?(PM_COLOR[method]??"#6b7280")+"18":"#f9fafb",color:creditRefundMethod===method?(PM_COLOR[method]??"#374151"):"#6b7280",border:creditRefundMethod===method?`2px solid ${(PM_COLOR[method]??"#6b7280")}55`:"2px solid transparent"}}>{PM_ICON[method]} {method}</button>)}</div></Field>\n          {creditRefundDone?<div className="rounded-xl bg-green-50 p-4 text-center text-sm font-black text-green-700">Remboursement enregistré ✓</div>:<SubmitBtn color={SEM.danger.accent} label={creditRefundBusy?"Remboursement…":"Confirmer le remboursement"} onClick={()=>void submitCreditRefund()} disabled={creditRefundBusy||Number(creditRefundAmount)<=0||Number(creditRefundAmount)>totalAvoir+0.01}/>}\n        </Modal>}\n        {paymentModal&&<Modal title="Versement client"'''
if modal_anchor not in s: raise SystemExit('Clients refund modal anchor missing')
s=s.replace(modal_anchor,refund_modal,1)
p.write_text(s)

# FACTURES
p=Path('src/app/screens/FacturesView.tsx'); s=p.read_text()
# Caisse includes client credit refunds as negative flows.
s=s.replace('''  const caissePaymentEvents = [...sessionEvents, ...sessionAdvanceEvents];''','''  const sessionCreditRefundEvents = isCaisseOpen && caisseSession\n    ? (boutique.clientCreditRefunds ?? []).filter(refund=>refund.refundedAt>=caisseSession.openedAt).map(refund=>({paidAt:refund.refundedAt,paymentMethod:refund.paymentMethod,signedAmount:-refund.amount}))\n    : [];\n  const caissePaymentEvents = [...sessionEvents, ...sessionAdvanceEvents, ...sessionCreditRefundEvents];''')
s=s.replace('''    setReturnMethod("Espèces");''','''    if (inv.clientId == null) setReturnMethod("Espèces");''')
s=s.replace('''persisted = await returnSale({ boutiqueId:boutique.id, invoiceId:returnInv.id, refundMethod:returnMethod, lines:returnLines.map(l=>({ sourceLineId:l.id, productId:l.productId, qty:l.qty })) });''','''persisted = await returnSale({ boutiqueId:boutique.id, invoiceId:returnInv.id, ...(returnInv.clientId==null?{refundMethod:returnMethod}:{}), lines:returnLines.map(l=>({ sourceLineId:l.id, productId:l.productId, qty:l.qty })) });''')
s=s.replace('''      creditNoteNumber:persisted.credit_note_number, returnRefundAmount:Number(persisted.refund_amount ?? 0), returnReceivableReduction:Number(persisted.receivable_reduction ?? 0), returnCreditRestore:Number(persisted.credit_restore ?? 0),''','''      creditNoteNumber:persisted.credit_note_number, returnRefundAmount:Number(persisted.refund_amount ?? 0), returnReceivableReduction:Number(persisted.receivable_reduction ?? 0), returnCreditRestore:Number(persisted.credit_restore ?? 0), returnClientCreditAmount:Number(persisted.client_credit_amount ?? persisted.credit_restore ?? 0),''')
s=s.replace('''    const restoredAdvance = persisted.credit_restore > 0 && persisted.restored_advance_id && returnInv.clientId != null ? {\n      id:Number(persisted.restored_advance_id), clientId:returnInv.clientId, amount:Number(persisted.credit_restore), allocatedAmount:0,\n      paymentMethod:"Autre" as PaymentMethod, paidAt:persisted.returned_at, recordedAt:persisted.returned_at,\n      operatorId:currentUser.id, operatorName:currentUser.nom, note:`Avoir restauré par ${retId} sur ${returnInv.id}`,\n    } : null;''','''    const clientCreditAmount=Number(persisted.client_credit_amount ?? persisted.credit_restore ?? 0);\n    const restoredAdvance = clientCreditAmount > 0 && persisted.restored_advance_id && returnInv.clientId != null ? {\n      id:Number(persisted.restored_advance_id), clientId:returnInv.clientId, amount:clientCreditAmount, allocatedAmount:0,\n      paymentMethod:"Autre" as PaymentMethod, paidAt:persisted.returned_at, recordedAt:persisted.returned_at,\n      operatorId:currentUser.id, operatorName:currentUser.nom, note:`Avoir créé par ${retId} sur ${returnInv.id}`,\n    } : null;''')
old='''          {!returnDone && (\n            <div className="space-y-2">\n              <p className="text-xs font-black tracking-wider text-muted-foreground">MODE DE REMBOURSEMENT</p>\n              <div className="grid grid-cols-2 gap-2">\n                {PAYMENT_METHODS.map(method => (\n                  <button key={method} type="button" onClick={()=>setReturnMethod(method)} className="flex items-center gap-2 rounded-xl px-3 py-3 text-sm font-bold" style={{ background:returnMethod===method?(PM_COLOR[method]??"#6b7280")+"18":"#f9fafb", border:returnMethod===method?`2px solid ${(PM_COLOR[method]??"#6b7280")}55`:"2px solid transparent", color:returnMethod===method?(PM_COLOR[method]??"#374151"):"#6b7280" }}>\n                    <span>{PM_ICON[method]}</span><span>{method}</span>\n                  </button>\n                ))}\n              </div>\n              <p className="text-xs text-muted-foreground">Le serveur réduit d'abord une éventuelle créance impayée, restaure ensuite l'avoir client utilisé, puis rembourse uniquement le solde réellement encaissé. Le mode ci-dessus ne s'applique qu'à la partie effectivement remboursée.</p>\n            </div>\n          )}'''
new='''          {!returnDone && (returnInv.clientId==null ? (\n            <div className="space-y-2">\n              <p className="text-xs font-black tracking-wider text-muted-foreground">MODE DE REMBOURSEMENT</p>\n              <div className="grid grid-cols-2 gap-2">\n                {PAYMENT_METHODS.map(method => (\n                  <button key={method} type="button" onClick={()=>setReturnMethod(method)} className="flex items-center gap-2 rounded-xl px-3 py-3 text-sm font-bold" style={{ background:returnMethod===method?(PM_COLOR[method]??"#6b7280")+"18":"#f9fafb", border:returnMethod===method?`2px solid ${(PM_COLOR[method]??"#6b7280")}55`:"2px solid transparent", color:returnMethod===method?(PM_COLOR[method]??"#374151"):"#6b7280" }}>\n                    <span>{PM_ICON[method]}</span><span>{method}</span>\n                  </button>\n                ))}\n              </div>\n              <p className="text-xs text-muted-foreground">Client comptoir : le solde réellement encaissé est remboursé immédiatement avec le moyen choisi.</p>\n            </div>\n          ) : <div className="rounded-xl bg-emerald-50 px-3 py-2 text-xs font-semibold text-emerald-800">Client enregistré : aucun remboursement immédiat. Après annulation d'une éventuelle créance, le solde du retour devient un avoir client remboursable séparément depuis Clients.</div>)}'''
if old not in s: raise SystemExit('Factures return UI block missing')
s=s.replace(old,new,1)
p.write_text(s)

# REPORTS
p=Path('src/app/screens/RapportView.tsx'); s=p.read_text()
s=s.replace('''  const filtPayments = filterPaymentEventsByPeriod(invoices, period, customFrom, customTo);\n  const filtCh  = filterByPeriod(charges, period, customFrom, customTo);''','''  const filtPayments = filterPaymentEventsByPeriod(invoices, period, customFrom, customTo);\n  const filtCreditRefunds = filterByPeriod(boutique.clientCreditRefunds ?? [], period, customFrom, customTo);\n  const filtCh  = filterByPeriod(charges, period, customFrom, customTo);''')
s=s.replace('''  const ca           = filtPayments.reduce((sum,payment)=>sum + payment.signedAmount,0);''','''  const ca           = filtPayments.reduce((sum,payment)=>sum + payment.signedAmount,0) - filtCreditRefunds.reduce((sum,refund)=>sum+refund.amount,0);''')
old='''  const byMethode = reportPaymentMethods.map(m => ({\n    m, total: filtPayments.filter(payment=>payment.paymentMethod===m).reduce((sum,payment)=>sum + payment.signedAmount,0),\n    count: filtPayments.filter(payment=>payment.paymentMethod===m).length,\n  })).filter(r=>r.count>0);'''
new='''  const byMethode = reportPaymentMethods.map(m => {\n    const payments=filtPayments.filter(payment=>payment.paymentMethod===m);\n    const refunds=filtCreditRefunds.filter(refund=>refund.paymentMethod===m);\n    return {m,total:payments.reduce((sum,payment)=>sum+payment.signedAmount,0)-refunds.reduce((sum,refund)=>sum+refund.amount,0),count:payments.length+refunds.length};\n  }).filter(r=>r.count>0);'''
if old not in s: raise SystemExit('Rapport byMethode anchor missing')
s=s.replace(old,new,1)
p.write_text(s)

# DOCUMENT WORDING
p=Path('src/app/utils/invoice.ts'); s=p.read_text()
s=s.replace('''const restored=Number(inv.returnCreditRestore ?? 0);''','''const restored=Number(inv.returnClientCreditAmount ?? inv.returnCreditRestore ?? 0);''')
s=s.replace('''🎟️ Avoir client restauré:''','''🎟️ Avoir client créé:''')
s=s.replace('''const returnCredit = isReturn ? Number(inv.returnCreditRestore ?? 0) : 0;''','''const returnCredit = isReturn ? Number(inv.returnClientCreditAmount ?? inv.returnCreditRestore ?? 0) : 0;''')
s=s.replace('''<span>Avoir client restauré</span>''','''<span>Avoir client créé</span>''')
p.write_text(s)

# Static verification of the intended behavior.
checks={
 'src/app/screens/ClientsView.tsx':["Rembourser l'avoir client","aucun moyen de remboursement n'est demandé ici","refundClientCredit"],
 'src/app/screens/FacturesView.tsx':["returnInv.clientId==null","sessionCreditRefundEvents","Client enregistré : aucun remboursement immédiat"],
 'src/lib/api.ts':["rpc/refund_client_credit_fifo","client_credit_refunds?select=*","client_credit_amount:number"],
 'src/app/screens/RapportView.tsx':["filtCreditRefunds","refunds.reduce"],
}
for path,needles in checks.items():
    text=Path(path).read_text()
    for needle in needles:
        if needle not in text: raise SystemExit(f'missing verification marker {needle!r} in {path}')
print('registered-client credit return patch verified')
