from pathlib import Path

# inventoryApi.ts
p=Path('src/lib/inventoryApi.ts')
s=p.read_text()
s=s.replace('''export type FifoRealizedMarginProduct = {\n  productId: number;\n  productName: string;\n  qty: number;\n  revenue: number;\n  fifoCost: number;\n  realizedMargin: number;\n  unmatchedLines: number;\n};''','''export type FifoRealizedMarginProduct = {\n  productId: number;\n  productName: string;\n  qty: number;\n  grossRevenue: number;\n  revenue: number;\n  fifoCost: number;\n  realizedMargin: number;\n  marginRate: number;\n  markupRate: number;\n  coverageRate: number;\n  unmatchedLines: number;\n};''')
s=s.replace('''export type FifoRealizedMarginReport = {\n  fromAt: string;\n  toAt: string;\n  revenue: number;\n  fifoCost: number;\n  realizedMargin: number;\n  marginRate: number;\n  lineCount: number;\n  unmatchedLines: number;\n  products: FifoRealizedMarginProduct[];\n};''','''export type FifoRealizedMarginReport = {\n  fromAt: string;\n  toAt: string;\n  grossRevenue: number;\n  revenue: number;\n  fifoCost: number;\n  realizedMargin: number;\n  marginRate: number;\n  markupRate: number;\n  coverageRate: number;\n  lineCount: number;\n  unmatchedLines: number;\n  products: FifoRealizedMarginProduct[];\n};''')
s=s.replace('''    revenue: Number(report?.revenue ?? 0),\n    fifoCost: Number(report?.fifoCost ?? 0),\n    realizedMargin: Number(report?.realizedMargin ?? 0),\n    marginRate: Number(report?.marginRate ?? 0),''','''    grossRevenue: Number(report?.grossRevenue ?? report?.revenue ?? 0),\n    revenue: Number(report?.revenue ?? 0),\n    fifoCost: Number(report?.fifoCost ?? 0),\n    realizedMargin: Number(report?.realizedMargin ?? 0),\n    marginRate: Number(report?.marginRate ?? 0),\n    markupRate: Number(report?.markupRate ?? 0),\n    coverageRate: Number(report?.coverageRate ?? 100),''')
s=s.replace('''      qty: Number(row?.qty ?? 0),\n      revenue: Number(row?.revenue ?? 0),\n      fifoCost: Number(row?.fifoCost ?? 0),\n      realizedMargin: Number(row?.realizedMargin ?? 0),\n      unmatchedLines: Number(row?.unmatchedLines ?? 0),''','''      qty: Number(row?.qty ?? 0),\n      grossRevenue: Number(row?.grossRevenue ?? row?.revenue ?? 0),\n      revenue: Number(row?.revenue ?? 0),\n      fifoCost: Number(row?.fifoCost ?? 0),\n      realizedMargin: Number(row?.realizedMargin ?? 0),\n      marginRate: Number(row?.marginRate ?? 0),\n      markupRate: Number(row?.markupRate ?? 0),\n      coverageRate: Number(row?.coverageRate ?? 100),\n      unmatchedLines: Number(row?.unmatchedLines ?? 0),''')
p.write_text(s)

# InventoryView.tsx
p=Path('src/app/screens/InventoryView.tsx')
s=p.read_text()
start=s.index('function ReportCards(')
end=s.index('\nexport function InventoryView', start)
s=s[:start]+'''function ReportCards({ report, margin, loading, periodLabel }: { report: InventoryReport; margin: FifoRealizedMarginReport | null; loading: boolean; periodLabel: string }) {\n  const variancePositive = report.varianceCost >= 0;\n  const marginPositive = Number(margin?.realizedMargin ?? 0) >= 0;\n  return <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">\n    <div className="rounded-2xl border border-border bg-card p-4"><p className="text-xs font-bold text-muted-foreground">Valeur du stock théorique (FIFO)</p><p className="mt-1 text-lg font-black">{money(report.theoreticalCost)}</p></div>\n    <div className="rounded-2xl border border-border bg-card p-4"><p className="text-xs font-bold text-muted-foreground">Valeur du stock compté (FIFO)</p><p className="mt-1 text-lg font-black">{money(report.countedCost)}</p></div>\n    <div className="rounded-2xl border border-border bg-card p-4"><p className="text-xs font-bold text-muted-foreground">Écart de valorisation du stock</p><p className={`mt-1 text-lg font-black ${variancePositive ? "text-emerald-700" : "text-red-700"}`}>{report.varianceCost > 0 ? "+" : ""}{money(report.varianceCost)}</p><p className="text-[11px] text-muted-foreground mt-1">Écart physique valorisé selon les couches FIFO</p></div>\n    <div className="rounded-2xl border border-border bg-card p-4"><p className="text-xs font-bold text-muted-foreground">CA valorisé · {periodLabel}</p><p className="mt-1 text-lg font-black">{loading ? "…" : money(Number(margin?.revenue ?? 0))}</p><p className="text-[11px] text-muted-foreground mt-1">{loading ? "Calcul en cours" : `Couverture des coûts : ${number(Number(margin?.coverageRate ?? 0))} %`}</p></div>\n    <div className="rounded-2xl border border-border bg-card p-4"><p className="text-xs font-bold text-muted-foreground">Marge brute réalisée (FIFO)</p><p className={`mt-1 text-lg font-black ${marginPositive ? "text-emerald-700" : "text-red-700"}`}>{loading ? "…" : money(Number(margin?.realizedMargin ?? 0))}</p><p className="text-[11px] text-muted-foreground mt-1">CA valorisé − coût FIFO des ventes</p></div>\n    <div className="rounded-2xl border border-border bg-card p-4"><p className="text-xs font-bold text-muted-foreground">Taux de marque</p><p className={`mt-1 text-lg font-black ${marginPositive ? "text-emerald-700" : "text-red-700"}`}>{loading ? "…" : `${number(Number(margin?.marginRate ?? 0))} %`}</p><p className="text-[11px] text-muted-foreground mt-1">Marge / CA · Taux de marge sur coût : {loading ? "…" : `${number(Number(margin?.markupRate ?? 0))} %`}</p>{!loading && Number(margin?.unmatchedLines ?? 0) > 0 && <p className="text-[11px] text-amber-700 mt-1">{margin!.unmatchedLines} ligne(s) non valorisée(s)</p>}</div>\n  </div>;\n}\n'''+s[end:]
s=s.replace('Date et heure de situation','Date de référence du stock')
s=s.replace("Période d'analyse de la marge","Période d'analyse des ventes et de la marge")
s=s.replace("Période d'analyse de la marge FIFO","Période d'analyse des ventes et de la marge FIFO")
s=s.replace('Situation au {new Date(session.asOfAt).toLocaleString("fr-FR")} · démarré le','Stock de référence au {new Date(session.asOfAt).toLocaleString("fr-FR")} · inventaire démarré le')
s=s.replace('Théorique : <strong>{number(theoretical)} {line.unit}</strong> · Coût FIFO moyen {money(theoretical > 0 ? line.fifoTheoreticalCost / theoretical : line.fifoUnitCost)}','Stock théorique : <strong>{number(theoretical)} {line.unit}</strong> · Coût moyen du stock restant (FIFO) {money(theoretical > 0 ? line.fifoTheoreticalCost / theoretical : line.fifoUnitCost)}')
s=s.replace('Marge réalisée FIFO · {marginPeriodLabel} :','Marge brute réalisée (FIFO) · {marginPeriodLabel} :')
s=s.replace(' · CA ${money(productMargin.revenue)} · coût FIFO ${money(productMargin.fifoCost)}',' · CA valorisé ${money(productMargin.revenue)} · coût des ventes FIFO ${money(productMargin.fifoCost)} · couverture ${number(productMargin.coverageRate)} %')
s=s.replace('<p className="text-xs text-muted-foreground">Compté</p>','<p className="text-xs text-muted-foreground">Stock compté</p>')
s=s.replace('<p className="text-xs text-muted-foreground">Écart</p>','<p className="text-xs text-muted-foreground">Écart de stock</p>')
old='''    const revenue = products.reduce((sum, row) => sum + row.revenue, 0);\n    const fifoCost = products.reduce((sum, row) => sum + row.fifoCost, 0);\n    const realizedMargin = revenue - fifoCost;\n    const unmatchedLines = products.reduce((sum, row) => sum + row.unmatchedLines, 0);\n    return { ...marginReport, products, revenue, fifoCost, realizedMargin, unmatchedLines, marginRate: revenue !== 0 ? realizedMargin / revenue * 100 : 0 };'''
new='''    const grossRevenue = products.reduce((sum, row) => sum + row.grossRevenue, 0);\n    const revenue = products.reduce((sum, row) => sum + row.revenue, 0);\n    const fifoCost = products.reduce((sum, row) => sum + row.fifoCost, 0);\n    const realizedMargin = revenue - fifoCost;\n    const unmatchedLines = products.reduce((sum, row) => sum + row.unmatchedLines, 0);\n    return { ...marginReport, products, grossRevenue, revenue, fifoCost, realizedMargin, unmatchedLines, marginRate: revenue !== 0 ? realizedMargin / revenue * 100 : 0, markupRate: fifoCost !== 0 ? realizedMargin / fifoCost * 100 : 0, coverageRate: grossRevenue !== 0 ? revenue / grossRevenue * 100 : 100 };'''
if old not in s: raise SystemExit('scoped margin block not found')
s=s.replace(old,new,1)
p.write_text(s)
