-- Registered-client returns: keep paid value as client credit first.
-- Counter sales continue to refund immediately. A registered client's credit can
-- later be refunded explicitly and is consumed FIFO with an immutable refund ledger.

create table if not exists public.client_advance_refunds (
  id bigint generated by default as identity primary key,
  boutique_id text not null references public.boutiques(id) on delete restrict,
  client_id bigint not null,
  amount numeric(12,2) not null check (amount > 0),
  payment_method text not null check (payment_method in ('Espèces','Wave','Orange Money','Autre')),
  refunded_at timestamptz not null default now(),
  operator_id uuid not null,
  operator_name text not null,
  idempotency_key uuid not null,
  allocations jsonb not null default '[]'::jsonb,
  note text,
  unique (boutique_id,idempotency_key),
  foreign key (boutique_id,client_id) references public.clients(boutique_id,id) on delete restrict
);
alter table public.client_advance_refunds enable row level security;
revoke all on public.client_advance_refunds from anon, authenticated;
grant select on public.client_advance_refunds to authenticated;
drop policy if exists client_advance_refunds_select on public.client_advance_refunds;
create policy client_advance_refunds_select on public.client_advance_refunds for select to authenticated using (private.auth_has_boutique_access(boutique_id));
create index if not exists client_advance_refunds_client_idx on public.client_advance_refunds(boutique_id,client_id,refunded_at desc,id desc);

do $patch$
declare v_def text; v_old text; v_new text;
begin
  select pg_get_functiondef('public.return_sale(text,text,uuid,jsonb,text)'::regprocedure) into v_def;
  if position('registered client: keep paid value as client credit' in v_def)=0 then
    v_old := $old$  v_refund_method := coalesce(nullif(btrim(p_refund_method),''), nullif(btrim(v_original.payment_method),''), 'Autre');
  if v_refund_method not in ('Espèces','Wave','Orange Money','Autre') then raise exception 'invalid refund payment method'; end if;$old$;
    v_new := $new$  if v_original.client_id is null then
    v_refund_method := coalesce(nullif(btrim(p_refund_method),''), nullif(btrim(v_original.payment_method),''), 'Autre');
    if v_refund_method not in ('Espèces','Wave','Orange Money','Autre') then raise exception 'invalid refund payment method'; end if;
  else
    -- registered client: keep paid value as client credit; refund only via refund_client_advance.
    v_refund_method := null;
  end if;$new$;
    if v_def=replace(v_def,v_old,v_new) then raise exception 'return_sale refund-method patch marker not found'; end if;
    v_def:=replace(v_def,v_old,v_new);
    v_old := $old$  v_remaining_unpaid := greatest(0,v_original.montant-v_paid_total-v_prior_receivable);
  v_remaining_advance := greatest(0,v_advance_paid-v_prior_credit);
  v_remaining_external := greatest(0,v_external_paid-v_prior_refund);
  v_remaining_value := v_total;
  v_receivable_reduction := least(v_remaining_value,v_remaining_unpaid);
  v_remaining_value := round(v_remaining_value-v_receivable_reduction,2);
  v_credit_restore := least(v_remaining_value,v_remaining_advance);
  v_remaining_value := round(v_remaining_value-v_credit_restore,2);
  v_refund_amount := least(v_remaining_value,v_remaining_external);
  v_remaining_value := round(v_remaining_value-v_refund_amount,2);
  if v_remaining_value>v_epsilon then raise exception 'return amount exceeds remaining financial basis'; end if;$old$;
    v_new := $new$  v_remaining_unpaid := greatest(0,v_original.montant-v_paid_total-v_prior_receivable);
  v_remaining_value := v_total;
  v_receivable_reduction := least(v_remaining_value,v_remaining_unpaid);
  v_remaining_value := round(v_remaining_value-v_receivable_reduction,2);
  if v_original.client_id is not null then
    v_remaining_external := greatest(0,v_paid_total-v_prior_credit-v_prior_refund);
    v_credit_restore := least(v_remaining_value,v_remaining_external);
    v_remaining_value := round(v_remaining_value-v_credit_restore,2);
    v_refund_amount := 0;
  else
    v_remaining_advance := greatest(0,v_advance_paid-v_prior_credit);
    v_remaining_external := greatest(0,v_external_paid-v_prior_refund);
    v_credit_restore := least(v_remaining_value,v_remaining_advance);
    v_remaining_value := round(v_remaining_value-v_credit_restore,2);
    v_refund_amount := least(v_remaining_value,v_remaining_external);
    v_remaining_value := round(v_remaining_value-v_refund_amount,2);
  end if;
  if v_remaining_value>v_epsilon then raise exception 'return amount exceeds remaining financial basis'; end if;$new$;
    if v_def=replace(v_def,v_old,v_new) then raise exception 'return_sale settlement patch marker not found'; end if;
    v_def:=replace(v_def,v_old,v_new);
    execute v_def;
  end if;
end $patch$;
revoke all on function public.return_sale(text,text,uuid,jsonb,text) from public,anon;
grant execute on function public.return_sale(text,text,uuid,jsonb,text) to authenticated,service_role;

create or replace function public.refund_client_advance(p_boutique_id text,p_client_id bigint,p_amount numeric,p_payment_method text,p_idempotency_key uuid)
returns jsonb language plpgsql security definer set search_path='pg_catalog','public','private'
as $$
declare
  v_user uuid:=auth.uid(); v_amount numeric:=round(coalesce(p_amount,0),2); v_available numeric; v_remaining numeric; v_take numeric;
  v_operator_name text; v_refunded_at timestamptz:=now(); v_refund_id bigint; v_allocations jsonb:='[]'::jsonb; v_existing jsonb; v_advance record;
  v_caisse_enabled boolean:=false; v_caisse_open boolean:=false; v_response jsonb;
begin
  if v_user is null or not private.auth_has_permission(p_boutique_id,'remboursement') then raise exception 'forbidden'; end if;
  if v_amount<=0 then raise exception 'invalid refund amount'; end if;
  if p_payment_method not in ('Espèces','Wave','Orange Money','Autre') then raise exception 'invalid refund payment method'; end if;
  select response into v_existing from private.idempotency_keys where user_id=v_user and operation='refund_client_advance' and key=p_idempotency_key;
  if v_existing is not null then return v_existing; end if;
  perform 1 from public.clients where boutique_id=p_boutique_id and id=p_client_id;
  if not found then raise exception 'client not found'; end if;
  if p_payment_method='Espèces' then
    select coalesce(caisse_daily_control_enabled,false) into v_caisse_enabled from public.auth_settings where boutique_id=p_boutique_id;
    if coalesce(v_caisse_enabled,false) then
      select exists(select 1 from public.caisse_sessions where boutique_id=p_boutique_id and closed_at is null and (opened_at at time zone 'Africa/Dakar')::date=(now() at time zone 'Africa/Dakar')::date) into v_caisse_open;
      if not v_caisse_open then raise exception 'caisse_opening_required' using hint='Ouvrez la caisse du jour avant tout remboursement en espèces.'; end if;
    end if;
  end if;
  perform pg_advisory_xact_lock(hashtext('client-credit-refund:'||p_boutique_id||':'||p_client_id::text));
  select coalesce(sum(greatest(0,amount-allocated_amount)),0) into v_available from public.client_advances where boutique_id=p_boutique_id and client_id=p_client_id;
  if v_amount>v_available+0.01 then raise exception 'client credit insufficient'; end if;
  v_remaining:=v_amount;
  for v_advance in select id,amount,allocated_amount from public.client_advances where boutique_id=p_boutique_id and client_id=p_client_id and amount-allocated_amount>0.005 order by paid_at,id for update loop
    exit when v_remaining<=0.005;
    v_take:=least(v_remaining,greatest(0,v_advance.amount-v_advance.allocated_amount));
    if v_take<=0 then continue; end if;
    update public.client_advances set allocated_amount=round(allocated_amount+v_take,2) where boutique_id=p_boutique_id and id=v_advance.id;
    v_allocations:=v_allocations||jsonb_build_array(jsonb_build_object('advance_id',v_advance.id,'amount',v_take));
    v_remaining:=round(v_remaining-v_take,2);
  end loop;
  if v_remaining>0.01 then raise exception 'client credit allocation incomplete'; end if;
  select nom into v_operator_name from public.platform_users where id=v_user; v_operator_name:=coalesce(v_operator_name,'Utilisateur');
  insert into public.client_advance_refunds(boutique_id,client_id,amount,payment_method,refunded_at,operator_id,operator_name,idempotency_key,allocations,note)
  values(p_boutique_id,p_client_id,v_amount,p_payment_method,v_refunded_at,v_user,v_operator_name,p_idempotency_key,v_allocations,'Remboursement avoir client') returning id into v_refund_id;
  v_response:=jsonb_build_object('refund_id',v_refund_id,'client_id',p_client_id,'amount',v_amount,'payment_method',p_payment_method,'refunded_at',v_refunded_at,'operator_id',v_user,'operator_name',v_operator_name,'allocations',v_allocations,'remaining_credit',round(v_available-v_amount,2));
  insert into private.idempotency_keys(user_id,operation,key,response) values(v_user,'refund_client_advance',p_idempotency_key,v_response);
  return v_response;
end $$;
revoke all on function public.refund_client_advance(text,bigint,numeric,text,uuid) from public,anon;
grant execute on function public.refund_client_advance(text,bigint,numeric,text,uuid) to authenticated,service_role;
