-- Persistent in-app notifications + standards-based Web Push.
--
-- IMPORTANT: VAPID private material is intentionally NOT source-controlled.
-- Provision these three secret names in Supabase Vault before enabling Web Push:
--   tournal_vapid_public_key
--   tournal_vapid_private_key
--   tournal_push_dispatch_secret
-- The production project already has them provisioned.

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  boutique_id text references public.boutiques(id) on delete cascade,
  category text not null default 'general',
  title text not null,
  body text not null default '',
  icon text not null default '🔔',
  action_tab text,
  action_filter jsonb,
  source_audit_id bigint references public.audit_log(id) on delete set null,
  created_at timestamptz not null default now(),
  read_at timestamptz,
  dismissed_at timestamptz,
  push_dispatched_at timestamptz,
  constraint notifications_category_check check (category in ('sale','payment','refund','stock','transfer','charge','client','supplier','security','caisse','general')),
  constraint notifications_source_user_unique unique (source_audit_id,user_id)
);
create index if not exists notifications_user_created_idx on public.notifications(user_id,created_at desc);
create index if not exists notifications_user_unread_idx on public.notifications(user_id,created_at desc) where read_at is null and dismissed_at is null;
alter table public.notifications enable row level security;
revoke all on public.notifications from public,anon;
grant select on public.notifications to authenticated;
drop policy if exists "notifications: own select" on public.notifications;
create policy "notifications: own select" on public.notifications for select to authenticated using (user_id=auth.uid());

create table if not exists public.push_subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  user_agent text,
  device_label text,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  constraint push_subscriptions_endpoint_len check (length(endpoint) between 20 and 4096),
  constraint push_subscriptions_p256dh_len check (length(p256dh) between 20 and 512),
  constraint push_subscriptions_auth_len check (length(auth) between 8 and 256)
);
create index if not exists push_subscriptions_user_idx on public.push_subscriptions(user_id,enabled);
alter table public.push_subscriptions enable row level security;
revoke all on public.push_subscriptions from public,anon,authenticated;
grant select on public.push_subscriptions to authenticated;
drop policy if exists "push subscriptions: own select" on public.push_subscriptions;
create policy "push subscriptions: own select" on public.push_subscriptions for select to authenticated using (user_id=auth.uid());

create or replace function private.notification_category(p_action text)
returns text language sql immutable set search_path='' as $$
  select case
    when coalesce(p_action,'') ~* 'permission|rôle|role|compte|auth' then 'security'
    when coalesce(p_action,'') ~* 'caisse' then 'caisse'
    when coalesce(p_action,'') ~* 'retour|rembours' then 'refund'
    when coalesce(p_action,'') ~* 'encaissement|solde|versement|paiement' then 'payment'
    when coalesce(p_action,'') ~* 'transfert|partenaire' then 'transfer'
    when coalesce(p_action,'') ~* 'charge' then 'charge'
    when coalesce(p_action,'') ~* 'client' then 'client'
    when coalesce(p_action,'') ~* 'fournisseur' then 'supplier'
    when coalesce(p_action,'') ~* 'stock|produit|catégorie|categorie|inventaire' then 'stock'
    when coalesce(p_action,'') ~* 'commande|vente|facture' then 'sale'
    else 'general' end;
$$;
revoke all on function private.notification_category(text) from public,anon,authenticated;

create or replace function private.notification_tab(p_category text)
returns text language sql immutable set search_path='' as $$
  select case p_category
    when 'sale' then 'factures'
    when 'payment' then 'factures'
    when 'refund' then 'factures'
    when 'stock' then 'stock'
    when 'transfer' then 'transferts'
    when 'charge' then 'charges'
    when 'client' then 'clients'
    when 'supplier' then 'fournisseurs'
    when 'caisse' then 'dashboard'
    when 'security' then 'admin'
    else 'dashboard' end;
$$;
revoke all on function private.notification_tab(text) from public,anon,authenticated;

create or replace function private.emit_audit_notification()
returns trigger language plpgsql security definer set search_path='' as $$
declare v_category text;
begin
  v_category:=private.notification_category(new.action);
  insert into public.notifications(user_id,boutique_id,category,title,body,icon,action_tab,source_audit_id)
  select distinct a.user_id,new.boutique_id,v_category,new.action,coalesce(new.detail,''),coalesce(nullif(new.icon,''),'🔔'),private.notification_tab(v_category),new.id
  from public.boutique_assignments a
  join public.platform_users u on u.id=a.user_id and not coalesce(u.is_suspended,false)
  where a.boutique_id=new.boutique_id
    and (
      a.role='owner'
      or v_category='general'
      or (v_category='sale' and (coalesce((a.droits->>'factures')::boolean,false) or coalesce((a.droits->>'vente')::boolean,false)))
      or (v_category='payment' and (coalesce((a.droits->>'factures')::boolean,false) or coalesce((a.droits->>'encaissement_vente')::boolean,false)))
      or (v_category='refund' and (coalesce((a.droits->>'factures')::boolean,false) or coalesce((a.droits->>'remboursement')::boolean,false)))
      or (v_category in ('stock','transfer') and (coalesce((a.droits->>'stock')::boolean,false) or coalesce((a.droits->>'inventaire')::boolean,false)))
      or (v_category='charge' and coalesce((a.droits->>'charges')::boolean,false))
      or (v_category='client' and coalesce((a.droits->>'clients')::boolean,false))
      or (v_category='supplier' and coalesce((a.droits->>'fournisseurs')::boolean,false))
      or (v_category='caisse' and (coalesce((a.droits->>'vente')::boolean,false) or coalesce((a.droits->>'encaissement_vente')::boolean,false)))
    )
  on conflict (source_audit_id,user_id) do nothing;

  if v_category='security' then
    insert into public.notifications(user_id,boutique_id,category,title,body,icon,action_tab,source_audit_id)
    select u.id,new.boutique_id,v_category,new.action,coalesce(new.detail,''),coalesce(nullif(new.icon,''),'🛡️'),'admin',new.id
    from public.platform_users u
    where u.is_super_admin=true and not coalesce(u.is_suspended,false)
    on conflict (source_audit_id,user_id) do nothing;
  end if;
  return new;
end;
$$;
revoke all on function private.emit_audit_notification() from public,anon,authenticated;
drop trigger if exists audit_log_emit_notification on public.audit_log;
create trigger audit_log_emit_notification after insert on public.audit_log for each row execute function private.emit_audit_notification();

create or replace function private.emit_low_stock_notification()
returns trigger language plpgsql security definer set search_path='' as $$
begin
  if new.low_stock_threshold is not null
     and new.low_stock_threshold>0
     and new.stock<=new.low_stock_threshold
     and (old.stock>old.low_stock_threshold or old.low_stock_threshold is null or old.low_stock_threshold<=0) then
    insert into public.notifications(user_id,boutique_id,category,title,body,icon,action_tab)
    select distinct a.user_id,new.boutique_id,'stock','Stock faible',new.nom||' : '||new.stock||' '||coalesce(new.unit,''),'⚠️','stock'
    from public.boutique_assignments a
    join public.platform_users u on u.id=a.user_id and not coalesce(u.is_suspended,false)
    where a.boutique_id=new.boutique_id
      and (a.role='owner' or coalesce((a.droits->>'stock')::boolean,false) or coalesce((a.droits->>'inventaire')::boolean,false));
  end if;
  return new;
end;
$$;
revoke all on function private.emit_low_stock_notification() from public,anon,authenticated;
drop trigger if exists products_low_stock_notification on public.products;
create trigger products_low_stock_notification after update of stock,low_stock_threshold on public.products for each row execute function private.emit_low_stock_notification();

create or replace function public.get_push_public_key()
returns text language sql stable security definer set search_path='' as $$
  select secret from vault.decrypted_secrets where name='tournal_vapid_public_key' limit 1;
$$;
revoke all on function public.get_push_public_key() from public,anon;
grant execute on function public.get_push_public_key() to authenticated;

create or replace function public.get_internal_push_config()
returns jsonb language sql stable security definer set search_path='' as $$
  select jsonb_build_object(
    'publicKey',(select secret from vault.decrypted_secrets where name='tournal_vapid_public_key' limit 1),
    'privateKey',(select secret from vault.decrypted_secrets where name='tournal_vapid_private_key' limit 1),
    'dispatchSecret',(select secret from vault.decrypted_secrets where name='tournal_push_dispatch_secret' limit 1)
  );
$$;
revoke all on function public.get_internal_push_config() from public,anon,authenticated;
grant execute on function public.get_internal_push_config() to service_role;

create or replace function private.dispatch_notification_push()
returns trigger language plpgsql security definer set search_path='' as $$
declare v_secret text;
begin
  if not exists(select 1 from public.push_subscriptions s where s.user_id=new.user_id and s.enabled=true) then return new; end if;
  select secret into v_secret from vault.decrypted_secrets where name='tournal_push_dispatch_secret' limit 1;
  if v_secret is null then return new; end if;
  begin
    perform net.http_post(
      url:='https://cnxtylngddwmhugxkzju.supabase.co/functions/v1/web-push-dispatch',
      headers:=jsonb_build_object('Content-Type','application/json','x-tournal-push-secret',v_secret),
      body:=jsonb_build_object('notificationId',new.id),
      timeout_milliseconds:=5000
    );
  exception when others then null;
  end;
  return new;
end;
$$;
revoke all on function private.dispatch_notification_push() from public,anon,authenticated;
drop trigger if exists notifications_dispatch_web_push on public.notifications;
create trigger notifications_dispatch_web_push after insert on public.notifications for each row execute function private.dispatch_notification_push();

create or replace function public.claim_push_subscription(
  p_endpoint text,p_p256dh text,p_auth text,p_user_agent text default null,p_device_label text default null
)
returns uuid language plpgsql security definer set search_path='' as $$
declare v_uid uuid:=auth.uid(); v_id uuid;
begin
  if v_uid is null then raise exception 'Connexion requise'; end if;
  if not exists(select 1 from public.platform_users u where u.id=v_uid and not coalesce(u.is_suspended,false)) then raise exception 'Compte inactif'; end if;
  if p_endpoint is null or length(p_endpoint)<20 or length(p_endpoint)>4096 then raise exception 'Abonnement Push invalide'; end if;
  if p_p256dh is null or length(p_p256dh)<20 or p_auth is null or length(p_auth)<8 then raise exception 'Clés Push invalides'; end if;
  insert into public.push_subscriptions(user_id,endpoint,p256dh,auth,user_agent,device_label,enabled,last_seen_at)
  values(v_uid,p_endpoint,p_p256dh,p_auth,left(p_user_agent,1000),left(p_device_label,200),true,now())
  on conflict(endpoint) do update set user_id=excluded.user_id,p256dh=excluded.p256dh,auth=excluded.auth,user_agent=excluded.user_agent,device_label=excluded.device_label,enabled=true,last_seen_at=now()
  returning id into v_id;
  return v_id;
end;
$$;
revoke all on function public.claim_push_subscription(text,text,text,text,text) from public,anon;
grant execute on function public.claim_push_subscription(text,text,text,text,text) to authenticated;

create or replace function public.remove_push_subscription(p_endpoint text)
returns void language plpgsql security definer set search_path='' as $$
begin
  if auth.uid() is null then raise exception 'Connexion requise'; end if;
  delete from public.push_subscriptions where endpoint=p_endpoint and user_id=auth.uid();
end;
$$;
revoke all on function public.remove_push_subscription(text) from public,anon;
grant execute on function public.remove_push_subscription(text) to authenticated;

create or replace function public.mark_notification_read(p_id bigint)
returns void language plpgsql security definer set search_path='' as $$
begin
  if auth.uid() is null then raise exception 'Connexion requise'; end if;
  update public.notifications set read_at=coalesce(read_at,now()) where id=p_id and user_id=auth.uid() and dismissed_at is null;
end;
$$;
revoke all on function public.mark_notification_read(bigint) from public,anon;
grant execute on function public.mark_notification_read(bigint) to authenticated;

create or replace function public.mark_all_notifications_read()
returns void language plpgsql security definer set search_path='' as $$
begin
  if auth.uid() is null then raise exception 'Connexion requise'; end if;
  update public.notifications set read_at=coalesce(read_at,now()) where user_id=auth.uid() and dismissed_at is null;
end;
$$;
revoke all on function public.mark_all_notifications_read() from public,anon;
grant execute on function public.mark_all_notifications_read() to authenticated;

create or replace function public.dismiss_all_notifications()
returns void language plpgsql security definer set search_path='' as $$
begin
  if auth.uid() is null then raise exception 'Connexion requise'; end if;
  update public.notifications set dismissed_at=coalesce(dismissed_at,now()),read_at=coalesce(read_at,now()) where user_id=auth.uid() and dismissed_at is null;
end;
$$;
revoke all on function public.dismiss_all_notifications() from public,anon;
grant execute on function public.dismiss_all_notifications() to authenticated;

do $$ begin
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='notifications') then
    alter publication supabase_realtime add table public.notifications;
  end if;
end $$;
