create table if not exists public.ops_staff_profiles (
  user_id uuid primary key references public.platform_users(id) on delete cascade,
  role text not null check (role in ('sales','service','support','manager')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function private.auth_is_ops_staff()
returns boolean
language sql
stable
security definer
set search_path = pg_catalog, public, private
as $$
  select exists (
    select 1 from public.ops_staff_profiles p
    where p.user_id = auth.uid() and p.active
  );
$$;

create table if not exists public.ops_tasks (
  id bigint generated by default as identity primary key,
  boutique_id text references public.boutiques(id) on delete cascade,
  title text not null,
  description text,
  team text not null default 'service' check (team in ('sales','service','support','success','management')),
  status text not null default 'open' check (status in ('open','in_progress','waiting','done','cancelled')),
  priority text not null default 'normal' check (priority in ('low','normal','high','urgent')),
  assignee_id uuid references public.platform_users(id) on delete set null,
  due_at timestamptz,
  source text not null default 'manual' check (source in ('manual','onboarding','support','system','handoff')),
  created_by uuid references public.platform_users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_at timestamptz
);
create index if not exists ops_tasks_status_due_idx on public.ops_tasks(status, due_at);
create index if not exists ops_tasks_boutique_idx on public.ops_tasks(boutique_id, created_at desc);
create index if not exists ops_tasks_assignee_idx on public.ops_tasks(assignee_id, status, due_at);

create table if not exists public.ops_tickets (
  id bigint generated by default as identity primary key,
  boutique_id text not null references public.boutiques(id) on delete cascade,
  subject text not null,
  description text,
  status text not null default 'new' check (status in ('new','in_progress','waiting_customer','resolved','closed')),
  priority text not null default 'normal' check (priority in ('low','normal','high','urgent')),
  assignee_id uuid references public.platform_users(id) on delete set null,
  requester_name text,
  requester_phone text,
  created_by uuid references public.platform_users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  resolved_at timestamptz
);
create index if not exists ops_tickets_queue_idx on public.ops_tickets(status, priority, created_at desc);
create index if not exists ops_tickets_boutique_idx on public.ops_tickets(boutique_id, created_at desc);

create table if not exists public.ops_interactions (
  id bigint generated by default as identity primary key,
  boutique_id text references public.boutiques(id) on delete cascade,
  kind text not null check (kind in ('note','call','meeting','handoff','support','onboarding','system')),
  team text check (team is null or team in ('sales','service','support','success','management','system')),
  title text not null,
  detail text,
  actor_id uuid references public.platform_users(id) on delete set null,
  related_task_id bigint references public.ops_tasks(id) on delete set null,
  related_ticket_id bigint references public.ops_tickets(id) on delete set null,
  created_at timestamptz not null default now()
);
create index if not exists ops_interactions_boutique_idx on public.ops_interactions(boutique_id, created_at desc);
create index if not exists ops_interactions_created_idx on public.ops_interactions(created_at desc);

create table if not exists public.ops_onboarding (
  boutique_id text primary key references public.boutiques(id) on delete cascade,
  owner_ready boolean not null default false,
  users_ready boolean not null default false,
  catalogue_ready boolean not null default false,
  first_receipt_at timestamptz,
  first_sale_at timestamptz,
  training_done boolean not null default false,
  training_done_at timestamptz,
  service_owner_id uuid references public.platform_users(id) on delete set null,
  target_go_live_at timestamptz,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
insert into public.ops_onboarding (boutique_id)
select b.id from public.boutiques b
on conflict (boutique_id) do nothing;

alter table public.ops_staff_profiles enable row level security;
alter table public.ops_tasks enable row level security;
alter table public.ops_tickets enable row level security;
alter table public.ops_interactions enable row level security;
alter table public.ops_onboarding enable row level security;

drop policy if exists ops_staff_access on public.ops_staff_profiles;
create policy ops_staff_access on public.ops_staff_profiles for all to authenticated
using ((select private.auth_is_super_admin()) or (select private.auth_is_ops_staff()))
with check ((select private.auth_is_super_admin()));

drop policy if exists ops_tasks_access on public.ops_tasks;
create policy ops_tasks_access on public.ops_tasks for all to authenticated
using ((select private.auth_is_super_admin()) or (select private.auth_is_ops_staff()))
with check ((select private.auth_is_super_admin()) or (select private.auth_is_ops_staff()));

drop policy if exists ops_tickets_access on public.ops_tickets;
create policy ops_tickets_access on public.ops_tickets for all to authenticated
using ((select private.auth_is_super_admin()) or (select private.auth_is_ops_staff()))
with check ((select private.auth_is_super_admin()) or (select private.auth_is_ops_staff()));

drop policy if exists ops_interactions_access on public.ops_interactions;
create policy ops_interactions_access on public.ops_interactions for all to authenticated
using ((select private.auth_is_super_admin()) or (select private.auth_is_ops_staff()))
with check ((select private.auth_is_super_admin()) or (select private.auth_is_ops_staff()));

drop policy if exists ops_onboarding_access on public.ops_onboarding;
create policy ops_onboarding_access on public.ops_onboarding for all to authenticated
using ((select private.auth_is_super_admin()) or (select private.auth_is_ops_staff()))
with check ((select private.auth_is_super_admin()) or (select private.auth_is_ops_staff()));

grant select, insert, update, delete on public.ops_staff_profiles to authenticated;
grant select, insert, update, delete on public.ops_tasks to authenticated;
grant select, insert, update, delete on public.ops_tickets to authenticated;
grant select, insert, update, delete on public.ops_interactions to authenticated;
grant select, insert, update, delete on public.ops_onboarding to authenticated;
grant usage, select on all sequences in schema public to authenticated;
