-- Make client advances usable on later invoices without treating the allocation
-- as a new cash receipt.  The public ledger keeps the remaining balance for
-- fast, targeted Realtime updates; the private allocation journal is the
-- immutable audit trail linking every used amount to an invoice.
begin;

set local lock_timeout = '10s';
set local statement_timeout = '30s';

alter table public.client_advances
  add column if not exists allocated_amount numeric not null default 0;

alter table public.client_advances
  drop constraint if exists client_advances_allocated_amount_check;

alter table public.client_advances
  add constraint client_advances_allocated_amount_check
  check (allocated_amount >= 0 and allocated_amount <= amount) not valid;

alter table public.client_advances
  validate constraint client_advances_allocated_amount_check;

create table if not exists private.client_advance_allocations (
  id bigint generated by default as identity primary key,
  boutique_id text not null,
  client_advance_id bigint not null,
  client_id bigint not null,
  invoice_id text not null,
  amount numeric not null check (amount > 0),
  allocated_at timestamptz not null default now(),
  operator_id uuid not null references public.platform_users(id) on delete restrict,
  operator_name text not null,
  idempotency_key uuid not null,
  constraint client_advance_allocations_advance_fkey
    foreign key (client_advance_id)
    references public.client_advances(id)
    on delete restrict,
  constraint client_advance_allocations_client_fkey
    foreign key (boutique_id, client_id)
    references public.clients(boutique_id, id)
    on delete restrict,
  constraint client_advance_allocations_invoice_fkey
    foreign key (boutique_id, invoice_id)
    references public.invoices(boutique_id, id)
    on delete restrict,
  constraint client_advance_allocations_idempotency_key
    unique (boutique_id, invoice_id, client_advance_id, idempotency_key)
);

create index if not exists client_advance_allocations_advance_idx
  on private.client_advance_allocations (client_advance_id, allocated_at desc, id desc);

create index if not exists client_advance_allocations_invoice_idx
  on private.client_advance_allocations (boutique_id, invoice_id, allocated_at desc, id desc);

revoke all on table private.client_advance_allocations from public, anon, authenticated;

alter table public.invoice_payments
  drop constraint if exists invoice_payments_source_check;

alter table public.invoice_payments
  add constraint invoice_payments_source_check
  check (source in ('invoice', 'client_fifo', 'legacy_backfill', 'transfer', 'client_advance')) not valid;

alter table public.invoice_payments
  validate constraint invoice_payments_source_check;

create or replace function public.apply_client_advance_to_invoice(
  p_boutique_id text,
  p_invoice_id text,
  p_idempotency_key uuid,
  p_amount numeric default null
)
returns jsonb
language plpgsql
security definer
set search_path = 'pg_catalog', 'public', 'private'
as $$
declare
  v_user uuid := auth.uid();
  v_existing jsonb;
  v_invoice public.invoices%rowtype;
  v_advance public.client_advances%rowtype;
  v_operator_name text;
  v_due numeric;
  v_available numeric;
  v_total_available numeric := 0;
  v_applied numeric;
  v_remaining_to_allocate numeric;
  v_from_advance numeric;
  v_payment_key uuid;
  v_payment_result jsonb;
  v_payment_id bigint;
  v_allocations jsonb := '[]'::jsonb;
  v_response jsonb;
begin
  if v_user is null or not private.auth_can_collect_payment(p_boutique_id) then
    raise exception 'payment access denied';
  end if;

  if p_amount is not null and p_amount <= 0 then
    raise exception 'amount must be positive';
  end if;

  select response into v_existing
  from private.idempotency_keys
  where user_id = v_user
    and operation = 'apply_client_advance_to_invoice'
    and key = p_idempotency_key;
  if v_existing is not null then
    return v_existing;
  end if;

  select * into v_invoice
  from public.invoices
  where boutique_id = p_boutique_id
    and id = p_invoice_id
  for update;

  if not found then
    raise exception 'invoice not found';
  end if;
  if lower(coalesce(v_invoice.type, '')) = 'retour' then
    raise exception 'cannot apply an advance to a return';
  end if;
  if v_invoice.client_id is null then
    raise exception 'invoice has no registered client';
  end if;

  v_due := greatest(0, v_invoice.montant - v_invoice.acompte);
  if v_due <= 0 then
    raise exception 'invoice already paid';
  end if;

  -- Lock the available ledger rows in a stable order.  Two simultaneous
  -- allocations for the same client therefore cannot spend one advance twice.
  for v_advance in
    select *
    from public.client_advances
    where boutique_id = p_boutique_id
      and client_id = v_invoice.client_id
      and amount > allocated_amount
    order by paid_at asc, id asc
    for update
  loop
    v_total_available := v_total_available + (v_advance.amount - v_advance.allocated_amount);
  end loop;

  if v_total_available <= 0 then
    raise exception 'no client advance available';
  end if;

  if p_amount is null then
    v_applied := least(v_due, v_total_available);
  else
    if p_amount > v_due then
      raise exception 'advance amount exceeds invoice balance';
    end if;
    if p_amount > v_total_available then
      raise exception 'client advance balance is insufficient';
    end if;
    v_applied := p_amount;
  end if;

  select nom into v_operator_name
  from public.platform_users
  where id = v_user;
  v_operator_name := coalesce(v_operator_name, 'Utilisateur');

  -- Reuse the established payment path so the first payment still performs
  -- the exact same FIFO stock deduction and invoice-state transition.
  v_payment_key := md5(p_idempotency_key::text || ':client-advance-payment')::uuid;
  v_payment_result := public.record_payment(
    p_boutique_id,
    p_invoice_id,
    v_payment_key,
    v_applied,
    'Avoir client'
  );
  v_applied := (v_payment_result->>'applied_amount')::numeric;

  update public.invoice_payments
  set source = 'client_advance'
  where boutique_id = p_boutique_id
    and invoice_id = p_invoice_id
    and batch_id = v_payment_key
  returning id into v_payment_id;

  if not found then
    raise exception 'advance payment record not found';
  end if;

  v_remaining_to_allocate := v_applied;
  for v_advance in
    select *
    from public.client_advances
    where boutique_id = p_boutique_id
      and client_id = v_invoice.client_id
      and amount > allocated_amount
    order by paid_at asc, id asc
    for update
  loop
    exit when v_remaining_to_allocate <= 0;
    v_available := v_advance.amount - v_advance.allocated_amount;
    v_from_advance := least(v_remaining_to_allocate, v_available);
    if v_from_advance <= 0 then
      continue;
    end if;

    update public.client_advances
    set allocated_amount = allocated_amount + v_from_advance
    where id = v_advance.id
      and boutique_id = p_boutique_id
      and allocated_amount + v_from_advance <= amount;
    if not found then
      raise exception 'client advance balance changed';
    end if;

    insert into private.client_advance_allocations (
      boutique_id, client_advance_id, client_id, invoice_id, amount,
      operator_id, operator_name, idempotency_key
    ) values (
      p_boutique_id, v_advance.id, v_invoice.client_id, p_invoice_id, v_from_advance,
      v_user, v_operator_name, p_idempotency_key
    );

    v_allocations := v_allocations || jsonb_build_array(jsonb_build_object(
      'advance_id', v_advance.id,
      'amount', v_from_advance
    ));
    v_remaining_to_allocate := v_remaining_to_allocate - v_from_advance;
  end loop;

  if v_remaining_to_allocate <> 0 then
    raise exception 'could not allocate the full client advance payment';
  end if;

  v_payment_result := jsonb_set(
    v_payment_result,
    '{payment,source}',
    to_jsonb('client_advance'::text),
    true
  );

  v_response := jsonb_build_object(
    'invoice_id', p_invoice_id,
    'client_id', v_invoice.client_id,
    'acompte', (v_payment_result->>'acompte')::numeric,
    'applied_amount', v_applied,
    'status', v_payment_result->>'status',
    'stock_deducted', coalesce((v_payment_result->>'stock_deducted')::boolean, false),
    'payment', v_payment_result->'payment',
    'allocations', v_allocations,
    'remaining_advance', v_total_available - v_applied
  );

  insert into private.idempotency_keys (user_id, operation, key, response)
  values (v_user, 'apply_client_advance_to_invoice', p_idempotency_key, v_response)
  on conflict (user_id, operation, key) do nothing;

  return v_response;
end;
$$;

revoke all on function public.apply_client_advance_to_invoice(text, text, uuid, numeric) from public, anon;
grant execute on function public.apply_client_advance_to_invoice(text, text, uuid, numeric) to authenticated;

create or replace function public.record_multi_payment(
  p_boutique_id text,
  p_invoice_id text,
  p_idempotency_key uuid,
  p_payments jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = 'pg_catalog', 'public', 'private'
as $$
declare
  v_user uuid := auth.uid();
  v_existing jsonb;
  v_invoice public.invoices%rowtype;
  v_item jsonb;
  v_index integer := 0;
  v_amount numeric;
  v_method text;
  v_total numeric := 0;
  v_line_key uuid;
  v_line_result jsonb;
  v_payments_result jsonb := '[]'::jsonb;
  v_advance_allocations jsonb := '[]'::jsonb;
  v_last_result jsonb;
  v_stock_deducted boolean := false;
  v_response jsonb;
begin
  if v_user is null or not private.auth_can_collect_payment(p_boutique_id) then
    raise exception 'payment access denied';
  end if;

  select response into v_existing
  from private.idempotency_keys
  where user_id = v_user and operation = 'record_multi_payment' and key = p_idempotency_key;
  if v_existing is not null then return v_existing; end if;

  if jsonb_typeof(p_payments) <> 'array' or jsonb_array_length(p_payments) = 0 then
    raise exception 'payments required';
  end if;

  select * into v_invoice
  from public.invoices
  where boutique_id = p_boutique_id and id = p_invoice_id
  for update;
  if not found then raise exception 'invoice not found'; end if;
  if lower(coalesce(v_invoice.type, '')) = 'retour' then
    raise exception 'cannot collect payment on a return';
  end if;

  for v_item in select * from jsonb_array_elements(p_payments) loop
    v_amount := coalesce((v_item->>'amount')::numeric, 0);
    v_method := coalesce(nullif(trim(v_item->>'paymentMethod'), ''), nullif(trim(v_item->>'method'), ''), 'Autre');
    if v_amount <= 0 then raise exception 'payment amount must be positive'; end if;
    if v_method not in ('Espèces', 'Wave', 'Orange Money', 'Autre', 'Avoir client') then
      raise exception 'invalid payment method';
    end if;
    if v_method = 'Avoir client' and v_invoice.client_id is null then
      raise exception 'invoice has no registered client';
    end if;
    v_total := v_total + v_amount;
  end loop;

  if v_total > greatest(0, v_invoice.montant - v_invoice.acompte) then
    raise exception 'payment total exceeds remaining amount';
  end if;

  for v_item in select * from jsonb_array_elements(p_payments) loop
    v_index := v_index + 1;
    v_amount := (v_item->>'amount')::numeric;
    v_method := coalesce(nullif(trim(v_item->>'paymentMethod'), ''), nullif(trim(v_item->>'method'), ''), 'Autre');
    v_line_key := md5(p_idempotency_key::text || ':' || v_index::text)::uuid;

    if v_method = 'Avoir client' then
      v_line_result := public.apply_client_advance_to_invoice(
        p_boutique_id,
        p_invoice_id,
        v_line_key,
        v_amount
      );
      v_advance_allocations := v_advance_allocations || coalesce(v_line_result->'allocations', '[]'::jsonb);
    else
      v_line_result := public.record_payment(
        p_boutique_id,
        p_invoice_id,
        v_line_key,
        v_amount,
        v_method
      );
    end if;

    v_payments_result := v_payments_result || jsonb_build_array(v_line_result->'payment');
    v_last_result := v_line_result;
    v_stock_deducted := v_stock_deducted or coalesce((v_line_result->>'stock_deducted')::boolean, false);
  end loop;

  v_response := jsonb_build_object(
    'invoice_id', p_invoice_id,
    'acompte', (v_last_result->>'acompte')::numeric,
    'applied_amount', v_total,
    'status', v_last_result->>'status',
    'stock_deducted', v_stock_deducted,
    'payments', v_payments_result,
    'advance_allocations', v_advance_allocations,
    'batch_id', p_idempotency_key
  );

  insert into private.idempotency_keys(user_id, operation, key, response)
  values (v_user, 'record_multi_payment', p_idempotency_key, v_response);

  return v_response;
end;
$$;

revoke all on function public.record_multi_payment(text, text, uuid, jsonb) from public, anon;
grant execute on function public.record_multi_payment(text, text, uuid, jsonb) to authenticated;

commit;
