-- Client advances are a separate, append-only cash ledger.  They are never
-- represented as a fictitious sale and they are not applied to an invoice
-- until a future, explicit allocation feature is introduced.
begin;

set local lock_timeout = '10s';
set local statement_timeout = '30s';

create table if not exists public.client_advances (
  id bigint generated by default as identity primary key,
  boutique_id text not null references public.boutiques(id) on delete cascade,
  client_id bigint not null,
  amount numeric not null check (amount > 0),
  payment_method text not null check (payment_method in ('Espèces', 'Wave', 'Orange Money', 'Autre')),
  paid_at timestamptz not null default now(),
  recorded_at timestamptz not null default now(),
  operator_id uuid not null references public.platform_users(id) on delete restrict,
  operator_name text not null,
  idempotency_key uuid not null,
  note text,
  constraint client_advances_client_fk
    foreign key (boutique_id, client_id)
    references public.clients (boutique_id, id)
    on delete restrict,
  constraint client_advances_operator_idempotency_key
    unique (boutique_id, operator_id, idempotency_key)
);

create index if not exists client_advances_client_ledger_idx
  on public.client_advances (boutique_id, client_id, paid_at desc, id desc);

create index if not exists client_advances_operator_id_idx
  on public.client_advances (operator_id);

alter table public.client_advances enable row level security;
revoke all on table public.client_advances from public, anon, authenticated;
grant select on table public.client_advances to authenticated;

drop policy if exists "client_advances: select" on public.client_advances;
create policy "client_advances: select"
  on public.client_advances for select to authenticated
  using (private.auth_is_assigned_to(boutique_id) or private.auth_is_super_admin());

create or replace function public.record_client_advance(
  p_boutique_id text,
  p_client_id bigint,
  p_idempotency_key uuid,
  p_amount numeric,
  p_payment_method text,
  p_payment_date date default current_date,
  p_note text default null
)
returns jsonb
language plpgsql
security definer
set search_path = 'pg_catalog', 'public', 'private'
as $$
declare
  v_user uuid := auth.uid();
  v_client public.clients%rowtype;
  v_advance public.client_advances%rowtype;
  v_existing jsonb;
  v_response jsonb;
  v_operator_name text;
  v_paid_at timestamptz;
begin
  if v_user is null or not private.auth_can_collect_payment(p_boutique_id) then
    raise exception 'payment access denied';
  end if;

  if p_amount is null or p_amount <= 0 then
    raise exception 'amount must be positive';
  end if;

  if coalesce(p_payment_method, '') not in ('Espèces', 'Wave', 'Orange Money', 'Autre') then
    raise exception 'invalid payment method';
  end if;

  select response into v_existing
  from private.idempotency_keys
  where user_id = v_user
    and operation = 'record_client_advance'
    and key = p_idempotency_key;
  if v_existing is not null then
    return v_existing;
  end if;

  select * into v_client
  from public.clients
  where boutique_id = p_boutique_id
    and id = p_client_id;
  if not found then
    raise exception 'client not found';
  end if;

  select nom into v_operator_name
  from public.platform_users
  where id = v_user;
  v_operator_name := coalesce(v_operator_name, 'Utilisateur');
  v_paid_at := ((coalesce(p_payment_date, current_date) + (now() at time zone 'Africa/Dakar')::time) at time zone 'Africa/Dakar');

  insert into public.client_advances (
    boutique_id, client_id, amount, payment_method, paid_at,
    operator_id, operator_name, idempotency_key, note
  ) values (
    p_boutique_id, p_client_id, p_amount, p_payment_method, v_paid_at,
    v_user, v_operator_name, p_idempotency_key, nullif(trim(p_note), '')
  )
  on conflict (boutique_id, operator_id, idempotency_key) do nothing
  returning * into v_advance;

  if not found then
    select * into v_advance
    from public.client_advances
    where boutique_id = p_boutique_id
      and operator_id = v_user
      and idempotency_key = p_idempotency_key;
  end if;

  v_response := jsonb_build_object(
    'advance_id', v_advance.id,
    'client_id', v_advance.client_id,
    'amount', v_advance.amount,
    'payment_method', v_advance.payment_method,
    'paid_at', v_advance.paid_at,
    'recorded_at', v_advance.recorded_at,
    'operator_id', v_advance.operator_id,
    'operator_name', v_advance.operator_name,
    'note', v_advance.note
  );

  insert into private.idempotency_keys (user_id, operation, key, response)
  values (v_user, 'record_client_advance', p_idempotency_key, v_response)
  on conflict (user_id, operation, key) do nothing;

  return v_response;
end;
$$;

revoke all on function public.record_client_advance(text, bigint, uuid, numeric, text, date, text) from public, anon;
grant execute on function public.record_client_advance(text, bigint, uuid, numeric, text, date, text) to authenticated;

-- The application listens to this table in both Realtime protocols.  V2 emits
-- a targeted client aggregate event; V1 will safely reconcile its snapshot.
do $sync_trigger$
begin
  if to_regprocedure('private.emit_boutique_row_sync()') is not null then
    execute 'drop trigger if exists tournal_sync_client_advances on public.client_advances';
    execute $trigger_sql$create trigger tournal_sync_client_advances
      after insert or update or delete on public.client_advances
      for each row execute function private.emit_boutique_row_sync(
        'boutique_id', 'client_id', 'client_id', 'id', 'clients', 'client_advance'
      )$trigger_sql$;
  end if;
end;
$sync_trigger$;

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'client_advances'
  ) then
    alter publication supabase_realtime add table public.client_advances;
  end if;
end;
$$;

-- The owner may cancel any pending order.  Every other seller is restricted to
-- a sale they created themselves; a Factures permission alone is insufficient.
create or replace function public.cancel_pending_sale(
  p_boutique_id text,
  p_invoice_id text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user uuid := auth.uid();
  v_invoice public.invoices%rowtype;
  v_can_cancel_any boolean;
  v_can_cancel_own boolean;
begin
  if v_user is null then
    raise exception 'forbidden';
  end if;

  v_can_cancel_any := private.auth_is_owner_of(p_boutique_id)
    and private.auth_has_active_app_session(p_boutique_id);
  v_can_cancel_own := private.auth_has_permission(p_boutique_id, 'vente');

  if not (v_can_cancel_any or v_can_cancel_own) then
    raise exception 'forbidden';
  end if;

  select *
  into v_invoice
  from public.invoices
  where id = p_invoice_id
    and boutique_id = p_boutique_id
  for update;

  if not found then
    raise exception 'invoice not found';
  end if;

  if v_invoice.type <> 'vente'
     or v_invoice.status <> 'en_attente'
     or coalesce(v_invoice.acompte, 0) <> 0
     or v_invoice.stock_deducted_at is not null then
    raise exception 'only an unpaid pending sale can be cancelled';
  end if;

  if not v_can_cancel_any and v_invoice.operator_id is distinct from v_user then
    raise exception 'forbidden';
  end if;

  delete from public.invoice_lines
  where boutique_id = p_boutique_id
    and invoice_id = p_invoice_id;

  delete from public.invoices
  where boutique_id = p_boutique_id
    and id = p_invoice_id;

  return jsonb_build_object('invoice_id', p_invoice_id, 'deleted', true);
end;
$$;

drop policy if exists "invoices: delete pending only" on public.invoices;
create policy "invoices: delete pending only"
  on public.invoices for delete to authenticated
  using (
    private.auth_is_owner_of(boutique_id)
    and private.auth_has_active_app_session(boutique_id)
    and type = 'vente'
    and status = 'en_attente'
    and acompte = 0
    and stock_deducted_at is null
  );

commit;
