create table if not exists public.ops_accounts (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  stage text not null default 'active' check (stage in ('prospect','sales','onboarding','active','at_risk','inactive')),
  health_status text not null default 'unknown' check (health_status in ('unknown','healthy','watch','at_risk')),
  sales_owner_id uuid references public.platform_users(id) on delete set null,
  service_owner_id uuid references public.platform_users(id) on delete set null,
  support_owner_id uuid references public.platform_users(id) on delete set null,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.ops_account_boutiques (
  account_id uuid not null references public.ops_accounts(id) on delete cascade,
  boutique_id text not null references public.boutiques(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (account_id, boutique_id), unique (boutique_id)
);
create index if not exists ops_account_boutiques_account_idx on public.ops_account_boutiques(account_id);
create table if not exists public.ops_contacts (
  id bigint generated by default as identity primary key,
  account_id uuid not null references public.ops_accounts(id) on delete cascade,
  boutique_id text references public.boutiques(id) on delete set null,
  name text not null, phone text, email text, role_label text,
  is_primary boolean not null default false, notes text,
  created_by uuid references public.platform_users(id) on delete set null,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index if not exists ops_contacts_account_idx on public.ops_contacts(account_id, created_at desc);
create index if not exists ops_contacts_phone_idx on public.ops_contacts(phone) where phone is not null;
alter table public.ops_tasks add column if not exists account_id uuid references public.ops_accounts(id) on delete set null;
create index if not exists ops_tasks_account_idx on public.ops_tasks(account_id, status, due_at);
alter table public.ops_tickets add column if not exists account_id uuid references public.ops_accounts(id) on delete set null,
  add column if not exists first_response_at timestamptz,
  add column if not exists sla_due_at timestamptz,
  add column if not exists escalated_at timestamptz;
create index if not exists ops_tickets_account_idx on public.ops_tickets(account_id, status, created_at desc);
create index if not exists ops_tickets_sla_idx on public.ops_tickets(status, sla_due_at) where status not in ('resolved','closed');
alter table public.ops_interactions add column if not exists account_id uuid references public.ops_accounts(id) on delete set null;
create index if not exists ops_interactions_account_idx on public.ops_interactions(account_id, created_at desc);
create table if not exists public.ops_access_requests (
  id bigint generated by default as identity primary key,
  boutique_id text not null references public.boutiques(id) on delete cascade,
  requester_id uuid not null references public.platform_users(id) on delete cascade,
  reason text not null,
  status text not null default 'pending' check (status in ('pending','approved','denied','expired','revoked')),
  requested_minutes integer not null default 30 check (requested_minutes between 5 and 240),
  approved_by uuid references public.platform_users(id) on delete set null,
  approved_at timestamptz, expires_at timestamptz, decided_note text,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index if not exists ops_access_requests_queue_idx on public.ops_access_requests(status, created_at desc);
create index if not exists ops_access_requests_requester_idx on public.ops_access_requests(requester_id, status, created_at desc);
insert into public.ops_accounts (name, stage)
select b.nom, 'active' from public.boutiques b
where not exists (select 1 from public.ops_account_boutiques ab where ab.boutique_id=b.id);
insert into public.ops_account_boutiques (account_id, boutique_id)
select a.id,b.id from public.boutiques b join public.ops_accounts a on a.name=b.nom
where not exists (select 1 from public.ops_account_boutiques ab where ab.boutique_id=b.id)
and a.id=(select a2.id from public.ops_accounts a2 where a2.name=b.nom order by a2.created_at,a2.id limit 1)
on conflict (boutique_id) do nothing;
update public.ops_tasks t set account_id=ab.account_id from public.ops_account_boutiques ab where t.account_id is null and t.boutique_id=ab.boutique_id;
update public.ops_tickets t set account_id=ab.account_id, sla_due_at=coalesce(t.sla_due_at,t.created_at+case t.priority when 'urgent' then interval '1 hour' when 'high' then interval '4 hours' when 'normal' then interval '1 day' else interval '2 days' end) from public.ops_account_boutiques ab where t.boutique_id=ab.boutique_id;
update public.ops_interactions i set account_id=ab.account_id from public.ops_account_boutiques ab where i.account_id is null and i.boutique_id=ab.boutique_id;
alter table public.ops_accounts enable row level security;
alter table public.ops_account_boutiques enable row level security;
alter table public.ops_contacts enable row level security;
alter table public.ops_access_requests enable row level security;
drop policy if exists ops_accounts_access on public.ops_accounts;
create policy ops_accounts_access on public.ops_accounts for all to authenticated using ((select private.auth_is_super_admin()) or (select private.auth_is_ops_staff())) with check ((select private.auth_is_super_admin()) or (select private.auth_is_ops_staff()));
drop policy if exists ops_account_boutiques_access on public.ops_account_boutiques;
create policy ops_account_boutiques_access on public.ops_account_boutiques for all to authenticated using ((select private.auth_is_super_admin()) or (select private.auth_is_ops_staff())) with check ((select private.auth_is_super_admin()) or (select private.auth_is_ops_staff()));
drop policy if exists ops_contacts_access on public.ops_contacts;
create policy ops_contacts_access on public.ops_contacts for all to authenticated using ((select private.auth_is_super_admin()) or (select private.auth_is_ops_staff())) with check ((select private.auth_is_super_admin()) or (select private.auth_is_ops_staff()));
drop policy if exists ops_access_requests_read on public.ops_access_requests;
create policy ops_access_requests_read on public.ops_access_requests for select to authenticated using ((select private.auth_is_super_admin()) or requester_id=auth.uid());
drop policy if exists ops_access_requests_create on public.ops_access_requests;
create policy ops_access_requests_create on public.ops_access_requests for insert to authenticated with check ((select private.auth_is_ops_staff()) and requester_id=auth.uid() and status='pending');
drop policy if exists ops_access_requests_admin_update on public.ops_access_requests;
create policy ops_access_requests_admin_update on public.ops_access_requests for update to authenticated using ((select private.auth_is_super_admin())) with check ((select private.auth_is_super_admin()));
grant select,insert,update,delete on public.ops_accounts to authenticated;
grant select,insert,update,delete on public.ops_account_boutiques to authenticated;
grant select,insert,update,delete on public.ops_contacts to authenticated;
grant select,insert,update on public.ops_access_requests to authenticated;
create or replace function private.sync_ops_account_for_new_boutique() returns trigger language plpgsql security definer set search_path=pg_catalog,public,private as $$ declare v_account_id uuid; begin insert into public.ops_accounts(name,stage) values(new.nom,'onboarding') returning id into v_account_id; insert into public.ops_account_boutiques(account_id,boutique_id) values(v_account_id,new.id) on conflict(boutique_id) do nothing; return new; end; $$;
drop trigger if exists trg_ops_account_new_boutique on public.boutiques;
create trigger trg_ops_account_new_boutique after insert on public.boutiques for each row execute function private.sync_ops_account_for_new_boutique();
create or replace function private.apply_ops_ticket_defaults() returns trigger language plpgsql security definer set search_path=pg_catalog,public,private as $$ begin if new.account_id is null then select ab.account_id into new.account_id from public.ops_account_boutiques ab where ab.boutique_id=new.boutique_id; end if; if new.sla_due_at is null then new.sla_due_at:=new.created_at+case new.priority when 'urgent' then interval '1 hour' when 'high' then interval '4 hours' when 'normal' then interval '1 day' else interval '2 days' end; end if; return new; end; $$;
drop trigger if exists trg_ops_ticket_defaults on public.ops_tickets;
create trigger trg_ops_ticket_defaults before insert on public.ops_tickets for each row execute function private.apply_ops_ticket_defaults();
create or replace function private.apply_ops_task_account() returns trigger language plpgsql security definer set search_path=pg_catalog,public,private as $$ begin if new.account_id is null and new.boutique_id is not null then select ab.account_id into new.account_id from public.ops_account_boutiques ab where ab.boutique_id=new.boutique_id; end if; return new; end; $$;
drop trigger if exists trg_ops_task_account on public.ops_tasks;
create trigger trg_ops_task_account before insert on public.ops_tasks for each row execute function private.apply_ops_task_account();
create or replace function private.apply_ops_interaction_account() returns trigger language plpgsql security definer set search_path=pg_catalog,public,private as $$ begin if new.account_id is null and new.boutique_id is not null then select ab.account_id into new.account_id from public.ops_account_boutiques ab where ab.boutique_id=new.boutique_id; end if; return new; end; $$;
drop trigger if exists trg_ops_interaction_account on public.ops_interactions;
create trigger trg_ops_interaction_account before insert on public.ops_interactions for each row execute function private.apply_ops_interaction_account();
