-- AUDIT ONLY. Reconcile the clean replay final state with the current
-- production schema. This file contains structure only; no production rows,
-- migration-journal repair, credentials, or historical secret values.

-- Relations that exist in production but predate the retained migration set.
create table if not exists private.backup_20260814_transfer_finance_charges (
  id bigint,
  boutique_id text,
  label text,
  montant numeric(12,2),
  categorie text,
  charge_date timestamptz,
  operator_id uuid,
  note text,
  created_at timestamptz,
  updated_at timestamptz
);

create table if not exists private.backup_20260814_transfer_finance_functions (
  function_name text not null,
  definition text not null,
  captured_at timestamptz not null default now(),
  constraint backup_20260814_transfer_finance_functions_pkey primary key (function_name)
);

create table if not exists private.invoice_counters (
  boutique_id text not null,
  next_num bigint not null,
  updated_at timestamptz not null default now(),
  constraint invoice_counters_pkey primary key (boutique_id)
);

-- Restore identity-backed sequences that exist in production.
alter table public.boutique_assignments alter column id drop default;
alter table public.boutique_assignments alter column id add generated always as identity;
alter table public.client_credit_refunds alter column id drop default;
alter table public.client_credit_refunds alter column id add generated by default as identity;

-- Columns established by production prehistory but absent from the synthetic base.
alter table public.inventory_lines
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

alter table public.inventory_sessions
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

alter table public.notifications
  add column if not exists source_invoice_id text;

alter table public.platform_users
  add column if not exists group_id text,
  add column if not exists is_compte_mere boolean not null default false,
  add column if not exists suspended_at timestamptz,
  add column if not exists suspended_by uuid,
  add column if not exists suspension_reason text;

-- Drop two synthetic/obsolete columns not present in the current production schema.
alter table public.charges drop column if exists source_transfer_id cascade;
alter table public.stock_entries drop column if exists source cascade;

-- Drop all FK constraints that either originate from or reference the tables whose
-- primary-key shapes were reconstructed incorrectly. They are recreated below from
-- the current production definitions after the canonical PKs are in place.
do $audit$
declare r record;
begin
  for r in
    select ns.nspname, c.relname, con.conname
    from pg_constraint con
    join pg_class c on c.oid = con.conrelid
    join pg_namespace ns on ns.oid = c.relnamespace
    where con.contype = 'f'
      and (
        con.conrelid in (
          select c2.oid from pg_class c2 join pg_namespace n2 on n2.oid=c2.relnamespace
          where n2.nspname in ('public','private')
            and c2.relname in ('app_sessions','charges','clients','invoices','products','stock_entries')
        )
        or con.confrelid in (
          select c3.oid from pg_class c3 join pg_namespace n3 on n3.oid=c3.relnamespace
          where n3.nspname in ('public','private')
            and c3.relname in ('app_sessions','charges','clients','invoices','products','stock_entries')
        )
      )
  loop
    execute format('alter table %I.%I drop constraint %I', r.nspname, r.relname, r.conname);
  end loop;
end
$audit$;

-- Canonical production PK shapes.
alter table private.app_sessions drop constraint if exists app_sessions_pkey;
alter table private.app_sessions add constraint app_sessions_pkey primary key (user_id, boutique_id, session_id);

alter table public.charges drop constraint if exists charges_pkey;
alter table public.charges add constraint charges_pkey primary key (boutique_id, id);

alter table public.clients drop constraint if exists clients_pkey;
alter table public.clients add constraint clients_pkey primary key (boutique_id, id);

alter table public.invoices drop constraint if exists invoices_pkey;
alter table public.invoices add constraint invoices_pkey primary key (boutique_id, id);

alter table public.products drop constraint if exists products_pkey;
alter table public.products add constraint products_pkey primary key (boutique_id, id);

alter table public.stock_entries drop constraint if exists stock_entries_pkey;
alter table public.stock_entries add constraint stock_entries_pkey primary key (boutique_id, id);

-- Temporary replay-only unique indexes are now redundant with the canonical PKs.
drop index if exists public.charges_boutique_id_id_audit_uq;
drop index if exists public.clients_boutique_id_id_audit_uq;
drop index if exists public.invoices_boutique_id_id_audit_uq;
drop index if exists public.products_boutique_id_id_audit_uq;
drop index if exists public.stock_entries_boutique_id_id_audit_uq;

-- Git-only transfer indexes from the obsolete 2026-08-17 fork.
drop index if exists public.idx_stl_tid;
drop index if exists public.idx_st_from;
drop index if exists public.idx_st_to;

-- Canonical FK graph for all tables affected by the PK corrections.
alter table private.app_sessions add constraint app_sessions_boutique_id_fkey foreign key (boutique_id) references public.boutiques(id) on delete cascade;
alter table private.client_advance_allocations add constraint client_advance_allocations_client_fkey foreign key (boutique_id, client_id) references public.clients(boutique_id, id) on delete restrict;
alter table private.client_advance_allocations add constraint client_advance_allocations_invoice_fkey foreign key (boutique_id, invoice_id) references public.invoices(boutique_id, id) on delete restrict;
alter table public.charges add constraint charges_boutique_id_fkey foreign key (boutique_id) references public.boutiques(id) on delete cascade;
alter table public.charges add constraint charges_boutique_id_supplier_id_fkey foreign key (boutique_id, supplier_id) references public.suppliers(boutique_id, id) on delete restrict;
alter table public.charges add constraint charges_boutique_stock_entry_fkey foreign key (boutique_id, stock_entry_id) references public.stock_entries(boutique_id, id) on delete restrict;
alter table public.charges add constraint charges_operator_id_fkey foreign key (operator_id) references public.platform_users(id) on delete set null;
alter table public.charges add constraint charges_transfer_id_fkey foreign key (transfer_id) references public.stock_transfers(id) on delete set null;
alter table public.client_advances add constraint client_advances_client_fk foreign key (boutique_id, client_id) references public.clients(boutique_id, id) on delete restrict;
alter table public.client_advances add constraint client_advances_return_invoice_fk foreign key (boutique_id, return_invoice_id) references public.invoices(boutique_id, id) on delete restrict not valid;
alter table public.client_credit_refunds add constraint client_credit_refunds_client_fk foreign key (boutique_id, client_id) references public.clients(boutique_id, id) on delete restrict;
alter table public.clients add constraint clients_boutique_id_fkey foreign key (boutique_id) references public.boutiques(id) on delete cascade;
alter table public.clients add constraint clients_linked_boutique_id_fkey foreign key (linked_boutique_id) references public.boutiques(id) on delete set null;
alter table public.invoice_lines add constraint invoice_lines_boutique_id_invoice_id_fkey foreign key (boutique_id, invoice_id) references public.invoices(boutique_id, id) on delete cascade;
alter table public.invoice_lines add constraint invoice_lines_boutique_id_product_id_fkey foreign key (boutique_id, product_id) references public.products(boutique_id, id) on delete set null;
alter table public.invoice_payments add constraint invoice_payments_boutique_id_invoice_id_fkey foreign key (boutique_id, invoice_id) references public.invoices(boutique_id, id) on delete cascade;
alter table public.invoices add constraint invoices_boutique_id_client_id_fkey foreign key (boutique_id, client_id) references public.clients(boutique_id, id) on delete set null;
alter table public.invoices add constraint invoices_boutique_id_fkey foreign key (boutique_id) references public.boutiques(id) on delete cascade;
alter table public.invoices add constraint invoices_cancelled_by_fkey foreign key (cancelled_by) references public.platform_users(id) on delete set null;
alter table public.invoices add constraint invoices_operator_id_fkey foreign key (operator_id) references public.platform_users(id) on delete set null;
alter table public.invoices add constraint invoices_return_of_fk foreign key (boutique_id, return_of_invoice_id) references public.invoices(boutique_id, id) on delete restrict not valid;
alter table public.products add constraint products_boutique_id_category_id_fkey foreign key (boutique_id, category_id) references public.categories(boutique_id, id) on delete set null;
alter table public.products add constraint products_boutique_id_fkey foreign key (boutique_id) references public.boutiques(id) on delete cascade;
alter table public.stock_entries add constraint stock_entries_boutique_id_fkey foreign key (boutique_id) references public.boutiques(id) on delete cascade;
alter table public.stock_entries add constraint stock_entries_boutique_id_product_id_fkey foreign key (boutique_id, product_id) references public.products(boutique_id, id) on delete cascade;
alter table public.stock_entries add constraint stock_entries_boutique_id_supplier_id_fkey foreign key (boutique_id, supplier_id) references public.suppliers(boutique_id, id) on delete restrict;
alter table public.stock_entries add constraint stock_entries_operator_id_fkey foreign key (operator_id) references public.platform_users(id) on delete set null;
alter table public.stock_entries add constraint stock_entries_return_invoice_fk foreign key (boutique_id, return_invoice_id) references public.invoices(boutique_id, id) on delete restrict not valid;
alter table public.stock_entries add constraint stock_entries_return_line_fk foreign key (return_invoice_line_id) references public.invoice_lines(id) on delete restrict not valid;
alter table public.stock_entries add constraint stock_entries_source_invoice_fk foreign key (boutique_id, source_invoice_id) references public.invoices(boutique_id, id) on delete restrict not valid;
alter table public.stock_entries add constraint stock_entries_source_line_fk foreign key (source_invoice_line_id) references public.invoice_lines(id) on delete restrict not valid;
alter table public.stock_entries add constraint stock_entries_transfer_id_fkey foreign key (transfer_id) references public.stock_transfers(id) not valid;
alter table public.stock_entries add constraint stock_entries_transfer_line_id_fkey foreign key (transfer_line_id) references public.stock_transfer_lines(id) not valid;
alter table public.stock_transfer_lines add constraint stock_transfer_lines_destination_product_fkey foreign key (destination_boutique_id, destination_product_id) references public.products(boutique_id, id);
alter table public.stock_transfer_lines add constraint stock_transfer_lines_source_boutique_id_source_product_id_fkey foreign key (source_boutique_id, source_product_id) references public.products(boutique_id, id);
alter table public.transfer_charge_payments add constraint transfer_charge_payments_charge_fk foreign key (boutique_id, charge_id) references public.charges(boutique_id, id) not valid;

-- Remaining constraints absent from the replay.
alter table public.boutique_assignments add constraint boutique_assignments_role_check check (role = any (array['owner'::text, 'manager'::text, 'employee'::text]));
alter table public.charges add constraint charges_status_check check (status = any (array['pending'::text, 'partial'::text, 'paid'::text]));
alter table public.client_credit_refunds add constraint client_credit_refunds_amount_check check (amount > 0::numeric);
alter table public.client_credit_refunds add constraint client_credit_refunds_boutique_id_fkey foreign key (boutique_id) references public.boutiques(id) on delete cascade;
alter table public.client_credit_refunds add constraint client_credit_refunds_operator_id_fkey foreign key (operator_id) references public.platform_users(id) on delete restrict;
alter table public.client_credit_refunds add constraint client_credit_refunds_operator_idempotency_key unique (boutique_id, operator_id, idempotency_key);
alter table public.client_credit_refunds add constraint client_credit_refunds_payment_method_check check (payment_method = any (array['Espèces'::text, 'Wave'::text, 'Orange Money'::text, 'Autre'::text]));
alter table public.clients add constraint clients_type_check check (type = any (array['B2B'::text, 'B2C'::text]));
alter table public.export_import_log add constraint manifest_required_keys check (manifest ? 'schema_version'::text and manifest ? 'created_at'::text and manifest ? 'application_version'::text and manifest ? 'boutique_id'::text and manifest ? 'tables'::text and manifest ? 'checksum'::text);
alter table public.inventory_lines add constraint inventory_lines_session_id_fkey foreign key (session_id) references public.inventory_sessions(id) on delete cascade;
alter table public.inventory_sessions add constraint inventory_as_of_not_future check (as_of_at <= (started_at + '00:05:00'::interval)) not valid;
alter table public.inventory_sessions add constraint inventory_sessions_boutique_id_fkey foreign key (boutique_id) references public.boutiques(id) on delete cascade;
alter table public.inventory_sessions add constraint inventory_sessions_scope_type_check check (scope_type = any (array['all'::text, 'category'::text, 'product'::text]));
alter table public.inventory_sessions add constraint inventory_sessions_status_check check (status = any (array['draft'::text, 'completed'::text, 'cancelled'::text]));
alter table public.invoice_lines add constraint invoice_lines_boutique_id_fkey foreign key (boutique_id) references public.boutiques(id) on delete cascade;
alter table public.invoices add constraint invoices_status_check check (status = any (array['payée'::text, 'en_attente'::text, 'annulée'::text, 'retour'::text]));
alter table public.invoices add constraint invoices_type_check check (type = any (array['vente'::text, 'Retour'::text, 'devis'::text, 'commande'::text]));
alter table public.platform_users add constraint platform_users_group_id_fkey foreign key (group_id) references public.groupes(id) on delete set null;
alter table public.platform_users add constraint platform_users_id_fkey foreign key (id) references auth.users(id) on delete cascade;
alter table public.stock_entries add constraint stock_entries_type_check check (type = any (array['achat'::text, 'ajustement'::text, 'retour'::text, 'inventaire'::text]));

-- One foundational helper is needed by the canonical normalized-phone index.
create or replace function private.normalize_phone(p_value text)
returns text
language sql
immutable
set search_path to 'pg_catalog'
as $function$
  select regexp_replace(coalesce(p_value, ''), '\D', '', 'g')
$function$;
revoke all on function private.normalize_phone(text) from public;
grant execute on function private.normalize_phone(text) to postgres;

-- Production-only non-constraint indexes missing from the replay.
create index app_sessions_boutique_id_idx on private.app_sessions using btree (boutique_id);
create index idx_audit_b_date on public.audit_log using btree (boutique_id, created_at desc);
create index idx_audit_log_user on public.audit_log using btree (user_id);
create index idx_ba_boutique on public.boutique_assignments using btree (boutique_id);
create index idx_ba_user on public.boutique_assignments using btree (user_id);
create index boutique_partners_created_by_idx on public.boutique_partners using btree (created_by);
create index boutique_partners_partner_boutique_id_idx on public.boutique_partners using btree (partner_boutique_id);
create index idx_boutique_state_updated_by on public.boutique_state using btree (updated_by);
create index idx_boutiques_owner on public.boutiques using btree (owner_id);
create index idx_caisse_sessions_operator on public.caisse_sessions using btree (operator_id);
create index charges_status_date_idx on public.charges using btree (boutique_id, status, charge_date desc);
create unique index charges_transfer_unique on public.charges using btree (transfer_id) where transfer_id is not null;
create index idx_charges_date on public.charges using btree (boutique_id, charge_date desc);
create index idx_charges_operator on public.charges using btree (operator_id);
create unique index clients_boutique_phone_unique on public.clients using btree (boutique_id, private.normalize_phone(tel)) where length(private.normalize_phone(tel)) >= 8;
create index clients_linked_boutique_id_idx on public.clients using btree (linked_boutique_id) where linked_boutique_id is not null;
create index idx_clients_tel on public.clients using btree (boutique_id, tel);
create index idx_eil_b_date on public.export_import_log using btree (boutique_id, created_at desc);
create index idx_export_import_log_user on public.export_import_log using btree (user_id);
create index idx_invlines_bi on public.invoice_lines using btree (boutique_id, invoice_id);
create index idx_invoice_lines_boutique_product on public.invoice_lines using btree (boutique_id, product_id);
create index invoice_payments_boutique_invoice_idx on public.invoice_payments using btree (boutique_id, invoice_id);
create index invoice_payments_operator_id_idx on public.invoice_payments using btree (operator_id) where operator_id is not null;
create index idx_invoices_b on public.invoices using btree (boutique_id);
create index idx_invoices_client on public.invoices using btree (boutique_id, client_id);
create index idx_invoices_date on public.invoices using btree (boutique_id, invoice_date desc);
create index idx_invoices_operator on public.invoices using btree (operator_id);
create index invoices_return_of_idx on public.invoices using btree (boutique_id, return_of_invoice_id) where return_of_invoice_id is not null;
create unique index notifications_source_invoice_user_sale_uq on public.notifications using btree (boutique_id, source_invoice_id, user_id) where source_invoice_id is not null and category = 'sale'::text;
create index idx_platform_users_group on public.platform_users using btree (group_id);
create index idx_products_b on public.products using btree (boutique_id);
create index idx_products_barcode on public.products using btree (boutique_id, barcode);
create index idx_products_cat on public.products using btree (boutique_id, category_id);
create index idx_stock_bp on public.stock_entries using btree (boutique_id, product_id);
create index idx_stock_date on public.stock_entries using btree (boutique_id, entry_date desc);
create index idx_stock_entries_operator on public.stock_entries using btree (operator_id);
create index stock_transfer_lines_source_product_idx on public.stock_transfer_lines using btree (source_boutique_id, source_product_id);
create index stock_transfer_lines_transfer_idx on public.stock_transfer_lines using btree (transfer_id);
create index stock_transfers_accepted_by_idx on public.stock_transfers using btree (accepted_by) where accepted_by is not null;
create index stock_transfers_created_by_idx on public.stock_transfers using btree (created_by);
create index stock_transfers_from_status_idx on public.stock_transfers using btree (from_boutique_id, status, created_at desc);
create index stock_transfers_to_status_idx on public.stock_transfers using btree (to_boutique_id, status, created_at desc);
create index suppliers_linked_boutique_id_idx on public.suppliers using btree (linked_boutique_id) where linked_boutique_id is not null;

-- Remove the 13 policies that come only from the obsolete 2026-08-17 Git fork.
drop policy if exists ba_owner_delete on public.boutique_assignments;
drop policy if exists ba_owner_insert on public.boutique_assignments;
drop policy if exists ba_owner_update on public.boutique_assignments;
drop policy if exists ba_select_team on public.boutique_assignments;
drop policy if exists ba_superadmin_all on public.boutique_assignments;
drop policy if exists boutiques_superadmin_select on public.boutiques;
drop policy if exists pu_select_coworkers on public.platform_users;
drop policy if exists pu_superadmin_select on public.platform_users;
drop policy if exists stl_insert on public.stock_transfer_lines;
drop policy if exists stl_select on public.stock_transfer_lines;
drop policy if exists st_insert on public.stock_transfers;
drop policy if exists st_select on public.stock_transfers;
drop policy if exists st_update on public.stock_transfers;

-- Restore the 8 current production policies absent from the replay.
create policy "auth_settings: select" on public.auth_settings as permissive for select to authenticated
  using (private.auth_is_assigned_to(boutique_id) or private.auth_is_super_admin());

create policy boutique_assignments_owner_select on public.boutique_assignments as permissive for select to authenticated
  using ((user_id = (select auth.uid()))
    or (select private.auth_is_super_admin())
    or exists (
      select 1 from public.boutiques b
      where b.id = boutique_assignments.boutique_id and b.owner_id = (select auth.uid())
    ));

create policy "boutique_state: select" on public.boutique_state as permissive for select to authenticated
  using ((select private.auth_is_assigned_to(boutique_state.boutique_id))
    or (select private.auth_is_super_admin()));

create policy "boutiques: insert" on public.boutiques as permissive for insert to authenticated
  with check (false);

create policy "boutiques: select" on public.boutiques as permissive for select to authenticated
  using (private.auth_is_assigned_to(id) or private.auth_is_super_admin());

create policy "eil: select" on public.export_import_log as permissive for select to authenticated
  using (private.auth_is_assigned_to(boutique_id) or private.auth_is_super_admin());

create policy "groupes: super admin only" on public.groupes as permissive for all to authenticated
  using ((select private.auth_is_super_admin()))
  with check ((select private.auth_is_super_admin()));

create policy platform_users_select_authenticated on public.platform_users as permissive for select to authenticated
  using ((id = (select auth.uid()))
    or (select private.auth_is_super_admin())
    or exists (
      select 1
      from public.boutique_assignments ba
      join public.boutiques b on b.id = ba.boutique_id
      where ba.user_id = platform_users.id and b.owner_id = (select auth.uid())
    ));
