-- Registered-client returns become account credit; counter sales still refund immediately.
-- This migration also adds auditable FIFO refunds of client credit.

alter table public.invoices add column if not exists return_client_credit_amount numeric(12,2) not null default 0;

do $$ begin
  if not exists (select 1 from pg_constraint where conname='invoices_return_client_credit_amount_check') then
    alter table public.invoices add constraint invoices_return_client_credit_amount_check check (return_client_credit_amount >= 0);
  end if;
end $$;

update public.invoices
set return_client_credit_amount = coalesce(return_credit_restore,0)
where lower(type)='retour' and client_id is not null and return_client_credit_amount=0 and coalesce(return_credit_restore,0)>0;

create table if not exists public.client_credit_refunds (
  id bigint generated by default as identity primary key,
  boutique_id text not null references public.boutiques(id) on delete cascade,
  client_id bigint not null,
  amount numeric(12,2) not null check (amount>0),
  payment_method text not null check (payment_method in ('Espèces','Wave','Orange Money','Autre')),
  refunded_at timestamptz not null default now(),
  recorded_at timestamptz not null default now(),
  operator_id uuid not null references public.platform_users(id) on delete restrict,
  operator_name text not null,
  idempotency_key uuid not null,
  note text,
  constraint client_credit_refunds_client_fk foreign key (boutique_id,client_id) references public.clients(boutique_id,id) on delete restrict,
  constraint client_credit_refunds_operator_idempotency_key unique (boutique_id,operator_id,idempotency_key)
);
create index if not exists client_credit_refunds_boutique_client_idx on public.client_credit_refunds(boutique_id,client_id,refunded_at desc,id desc);

create table if not exists public.client_credit_refund_allocations (
  refund_id bigint not null references public.client_credit_refunds(id) on delete cascade,
  advance_id bigint not null references public.client_advances(id) on delete restrict,
  amount numeric(12,2) not null check (amount>0),
  primary key (refund_id,advance_id)
);
create index if not exists client_credit_refund_allocations_advance_idx on public.client_credit_refund_allocations(advance_id);

alter table public.client_credit_refunds enable row level security;
alter table public.client_credit_refund_allocations enable row level security;

drop policy if exists "client_credit_refunds: select" on public.client_credit_refunds;
create policy "client_credit_refunds: select" on public.client_credit_refunds for select to authenticated using (private.auth_is_assigned_to(boutique_id) or private.auth_is_super_admin());

drop policy if exists "client_credit_refund_allocations: select" on public.client_credit_refund_allocations;
create policy "client_credit_refund_allocations: select" on public.client_credit_refund_allocations for select to authenticated using (exists(select 1 from public.client_credit_refunds r where r.id=refund_id and (private.auth_is_assigned_to(r.boutique_id) or private.auth_is_super_admin())));

revoke all on public.client_credit_refunds from anon,authenticated;
revoke all on public.client_credit_refund_allocations from anon,authenticated;
grant select on public.client_credit_refunds to authenticated;
grant select on public.client_credit_refund_allocations to authenticated;

drop trigger if exists client_credit_refunds_daily_caisse on public.client_credit_refunds;
create trigger client_credit_refunds_daily_caisse before insert on public.client_credit_refunds for each row execute function private.enforce_daily_caisse_on_receipt();

create or replace function public.refund_client_credit_fifo(
  p_boutique_id text,
  p_client_id bigint,
  p_amount numeric,
  p_payment_method text,
  p_idempotency_key uuid,
  p_note text default null
) returns jsonb
language plpgsql
security definer
set search_path='pg_catalog','public','private'
as $$
declare
  v_user uuid:=auth.uid();
  v_operator_name text;
  v_existing jsonb;
  v_amount numeric:=round(coalesce(p_amount,0),2);
  v_available numeric:=0;
  v_remaining numeric;
  v_take numeric;
  v_refund_id bigint;
  v_row public.client_advances%rowtype;
  v_allocations jsonb:='[]'::jsonb;
  v_response jsonb;
begin
  if v_user is null or not private.auth_has_permission(p_boutique_id,'remboursement') then raise exception 'forbidden'; end if;
  if v_amount<=0 then raise exception 'invalid refund amount'; end if;
  if p_payment_method not in ('Espèces','Wave','Orange Money','Autre') then raise exception 'invalid refund payment method'; end if;
  if not exists(select 1 from public.clients where boutique_id=p_boutique_id and id=p_client_id) then raise exception 'client not found'; end if;

  select response into v_existing from private.idempotency_keys where user_id=v_user and operation='refund_client_credit_fifo' and key=p_idempotency_key;
  if v_existing is not null then return v_existing; end if;

  perform 1 from public.client_advances where boutique_id=p_boutique_id and client_id=p_client_id and amount>allocated_amount order by paid_at,id for update;
  select coalesce(sum(amount-allocated_amount),0) into v_available from public.client_advances where boutique_id=p_boutique_id and client_id=p_client_id;
  if v_amount>v_available+0.01 then raise exception 'client credit insufficient'; end if;

  select nom into v_operator_name from public.platform_users where id=v_user;
  v_operator_name:=coalesce(v_operator_name,'Utilisateur');

  insert into public.client_credit_refunds(boutique_id,client_id,amount,payment_method,refunded_at,operator_id,operator_name,idempotency_key,note)
  values(p_boutique_id,p_client_id,v_amount,p_payment_method,now(),v_user,v_operator_name,p_idempotency_key,nullif(btrim(p_note),''))
  returning id into v_refund_id;

  v_remaining:=v_amount;
  for v_row in
    select * from public.client_advances
    where boutique_id=p_boutique_id and client_id=p_client_id and amount>allocated_amount
    order by paid_at,id
    for update
  loop
    exit when v_remaining<=0.005;
    v_take:=least(v_remaining,v_row.amount-v_row.allocated_amount);
    if v_take<=0 then continue; end if;
    update public.client_advances set allocated_amount=round(allocated_amount+v_take,2) where id=v_row.id;
    insert into public.client_credit_refund_allocations(refund_id,advance_id,amount) values(v_refund_id,v_row.id,v_take);
    v_allocations:=v_allocations||jsonb_build_array(jsonb_build_object('advance_id',v_row.id,'amount',v_take));
    v_remaining:=round(v_remaining-v_take,2);
  end loop;
  if v_remaining>0.01 then raise exception 'client credit allocation incomplete'; end if;

  v_response:=jsonb_build_object('refund_id',v_refund_id,'client_id',p_client_id,'amount',v_amount,'payment_method',p_payment_method,'refunded_at',now(),'operator_id',v_user,'operator_name',v_operator_name,'allocations',v_allocations,'remaining_credit',round(v_available-v_amount,2));
  insert into private.idempotency_keys(user_id,operation,key,response) values(v_user,'refund_client_credit_fifo',p_idempotency_key,v_response);
  return v_response;
end $$;

revoke all on function public.refund_client_credit_fifo(text,bigint,numeric,text,uuid,text) from public,anon;
grant execute on function public.refund_client_credit_fifo(text,bigint,numeric,text,uuid,text) to authenticated,service_role;

create or replace function public.return_sale(p_boutique_id text,p_invoice_id text,p_idempotency_key uuid,p_lines jsonb,p_refund_method text default null)
returns jsonb
language plpgsql
security definer
set search_path='pg_catalog','public','private'
as $$
declare
  v_epsilon constant numeric:=0.01;
  v_user uuid:=auth.uid();
  v_operator_name text;
  v_existing jsonb;
  v_original public.invoices%rowtype;
  v_line jsonb;
  v_source public.invoice_lines%rowtype;
  v_qty numeric;
  v_match_count integer;
  v_resolved jsonb:='[]'::jsonb;
  v_already_returned numeric;
  v_available numeric;
  v_base_refund_unit numeric;
  v_return_sell_qty numeric;
  v_return_id text;
  v_credit_num bigint;
  v_total numeric:=0;
  v_response jsonb;
  v_returned_at timestamptz:=now();
  v_refund_method text;
  v_payment_id bigint;
  v_return_line_id bigint;
  v_sale_entry_id bigint;
  v_sale_entry_qty numeric;
  v_fifo_cost numeric;
  v_actual_unit_cost numeric;
  v_paid_total numeric;
  v_prior_refund numeric;
  v_prior_receivable numeric;
  v_prior_client_credit numeric;
  v_remaining_financial numeric;
  v_remaining_unpaid numeric;
  v_remaining_external numeric;
  v_remaining_value numeric;
  v_refund_amount numeric:=0;
  v_receivable_reduction numeric:=0;
  v_client_credit_amount numeric:=0;
  v_advance_id bigint;
  v_advance_key uuid;
begin
  if v_user is null or not private.auth_has_permission(p_boutique_id,'remboursement') then raise exception 'forbidden'; end if;
  select response into v_existing from private.idempotency_keys where user_id=v_user and operation='return_sale' and key=p_idempotency_key;
  if v_existing is not null then return v_existing; end if;

  select * into v_original from public.invoices where boutique_id=p_boutique_id and id=p_invoice_id for update;
  if not found then raise exception 'invoice not found'; end if;
  if lower(coalesce(v_original.type,''))='retour' then raise exception 'cannot return a return'; end if;
  if v_original.status='annulée' then raise exception 'cannot return a cancelled invoice'; end if;
  if v_original.stock_deducted_at is null then raise exception 'sale stock was not committed'; end if;
  if jsonb_typeof(p_lines)<>'array' or jsonb_array_length(p_lines)=0 then raise exception 'lines required'; end if;

  for v_line in select * from jsonb_array_elements(p_lines) loop
    v_qty:=round(coalesce((v_line->>'qty')::numeric,0),3);
    if v_qty<=0 then raise exception 'invalid return quantity'; end if;
    if nullif(v_line->>'sourceLineId','') is not null then
      select * into v_source from public.invoice_lines where id=(v_line->>'sourceLineId')::bigint and boutique_id=p_boutique_id and invoice_id=p_invoice_id;
      if not found then raise exception 'source invoice line not found'; end if;
    else
      select count(*) into v_match_count from public.invoice_lines where boutique_id=p_boutique_id and invoice_id=p_invoice_id and product_id=(v_line->>'productId')::bigint;
      if v_match_count<>1 then raise exception 'sourceLineId required for duplicate product lines'; end if;
      select * into v_source from public.invoice_lines where boutique_id=p_boutique_id and invoice_id=p_invoice_id and product_id=(v_line->>'productId')::bigint limit 1;
    end if;
    v_resolved:=v_resolved||jsonb_build_array(jsonb_build_object('sourceLineId',v_source.id,'qty',v_qty));
  end loop;

  for v_line in
    select jsonb_build_object('sourceLineId',(x->>'sourceLineId')::bigint,'qty',sum((x->>'qty')::numeric)) from jsonb_array_elements(v_resolved) x group by (x->>'sourceLineId')::bigint
  loop
    select * into v_source from public.invoice_lines where id=(v_line->>'sourceLineId')::bigint and boutique_id=p_boutique_id and invoice_id=p_invoice_id;
    v_qty:=round((v_line->>'qty')::numeric,3);
    select coalesce(sum(rl.qty),0) into v_already_returned from public.invoice_lines rl join public.invoices ri on ri.boutique_id=rl.boutique_id and ri.id=rl.invoice_id where ri.boutique_id=p_boutique_id and lower(ri.type)='retour' and ri.return_of_invoice_id=p_invoice_id and rl.source_invoice_line_id=v_source.id;
    v_available:=greatest(0,v_source.qty-v_already_returned);
    if v_qty>v_available+0.0005 then raise exception 'return quantity exceeds remaining quantity for source line %',v_source.id; end if;
    v_base_refund_unit:=case when v_source.qty>0 then ((coalesce(v_source.sell_qty,v_source.qty)*v_source.prix_unit)/v_source.qty) else 0 end;
    v_total:=v_total+v_qty*v_base_refund_unit;
  end loop;
  v_total:=round(v_total,2);
  if v_total<=0 then raise exception 'return amount must be positive'; end if;

  select coalesce(sum(p.amount),0) into v_paid_total from public.invoice_payments p where p.boutique_id=p_boutique_id and p.invoice_id=p_invoice_id;
  if v_paid_total=0 and coalesce(v_original.acompte,0)>0 then v_paid_total:=v_original.acompte; end if;

  select coalesce(sum(return_refund_amount),0),coalesce(sum(return_receivable_reduction),0),coalesce(sum(greatest(return_client_credit_amount,return_credit_restore)),0)
  into v_prior_refund,v_prior_receivable,v_prior_client_credit
  from public.invoices where boutique_id=p_boutique_id and lower(type)='retour' and return_of_invoice_id=p_invoice_id;

  v_remaining_financial:=greatest(0,v_original.montant-v_prior_refund-v_prior_receivable-v_prior_client_credit);
  if v_total>v_remaining_financial+v_epsilon then raise exception 'return amount exceeds remaining financial basis'; end if;

  v_remaining_unpaid:=greatest(0,v_original.montant-v_paid_total-v_prior_receivable);
  v_remaining_value:=v_total;
  v_receivable_reduction:=least(v_remaining_value,v_remaining_unpaid);
  v_remaining_value:=round(v_remaining_value-v_receivable_reduction,2);

  if v_original.client_id is not null then
    v_client_credit_amount:=v_remaining_value;
    v_refund_amount:=0;
    v_refund_method:=null;
  else
    v_remaining_external:=greatest(0,v_paid_total-v_prior_refund);
    if v_remaining_value>v_remaining_external+v_epsilon then raise exception 'return amount exceeds refundable collected amount'; end if;
    v_refund_amount:=v_remaining_value;
    if v_refund_amount>0 then
      v_refund_method:=coalesce(nullif(btrim(p_refund_method),''),nullif(btrim(v_original.payment_method),''),'Autre');
      if v_refund_method not in ('Espèces','Wave','Orange Money','Autre') then raise exception 'invalid refund payment method'; end if;
    end if;
  end if;

  v_credit_num:=private.next_credit_note_number(p_boutique_id);
  v_return_id:='A'||to_char(v_returned_at,'YYMMDD')||'-'||lpad(v_credit_num::text,6,'0');
  select nom into v_operator_name from public.platform_users where id=v_user;
  v_operator_name:=coalesce(v_operator_name,'Utilisateur');

  insert into public.invoices(id,boutique_id,numero,credit_note_number,client_id,client_nom,client_tel,montant,acompte,invoice_date,status,type,payment_method,operator_id,stock_deducted_at,return_of_invoice_id,return_refund_amount,return_receivable_reduction,return_credit_restore,return_client_credit_amount,client_email_snapshot,client_adresse_snapshot,client_ville_snapshot,client_type_snapshot,boutique_nom_snapshot,boutique_ville_snapshot,boutique_adresse_snapshot,boutique_tel_snapshot,boutique_email_snapshot,boutique_logo_snapshot,operator_nom_snapshot,origin)
  values(v_return_id,p_boutique_id,-v_credit_num,v_credit_num,v_original.client_id,v_original.client_nom,v_original.client_tel,v_total,v_refund_amount,v_returned_at,'retour','Retour',v_refund_method,v_user,v_returned_at,p_invoice_id,v_refund_amount,v_receivable_reduction,v_client_credit_amount,v_client_credit_amount,v_original.client_email_snapshot,v_original.client_adresse_snapshot,v_original.client_ville_snapshot,v_original.client_type_snapshot,v_original.boutique_nom_snapshot,v_original.boutique_ville_snapshot,v_original.boutique_adresse_snapshot,v_original.boutique_tel_snapshot,v_original.boutique_email_snapshot,v_original.boutique_logo_snapshot,v_operator_name,v_original.origin);

  if v_refund_amount>0 then
    insert into public.invoice_payments(boutique_id,invoice_id,amount,payment_method,paid_at,operator_id,operator_name,batch_id,source)
    values(p_boutique_id,v_return_id,v_refund_amount,v_refund_method,v_returned_at,v_user,v_operator_name,p_idempotency_key,'invoice') returning id into v_payment_id;
  end if;

  if v_client_credit_amount>0 then
    if v_original.client_id is null then raise exception 'cannot create client credit without registered client'; end if;
    v_advance_key:=md5(p_idempotency_key::text||':return-credit')::uuid;
    insert into public.client_advances(boutique_id,client_id,amount,payment_method,paid_at,recorded_at,operator_id,operator_name,idempotency_key,note,allocated_amount)
    values(p_boutique_id,v_original.client_id,v_client_credit_amount,'Autre',v_returned_at,v_returned_at,v_user,v_operator_name,v_advance_key,'Avoir créé par '||v_return_id||' sur '||p_invoice_id,0) returning id into v_advance_id;
  end if;

  for v_line in
    select jsonb_build_object('sourceLineId',(x->>'sourceLineId')::bigint,'qty',sum((x->>'qty')::numeric)) from jsonb_array_elements(v_resolved) x group by (x->>'sourceLineId')::bigint
  loop
    select * into v_source from public.invoice_lines where id=(v_line->>'sourceLineId')::bigint;
    v_qty:=round((v_line->>'qty')::numeric,3);
    v_return_sell_qty:=case when v_source.sell_unit is null or v_source.sell_qty is null or v_source.qty<=0 then null else v_source.sell_qty*v_qty/v_source.qty end;
    select se.id,se.qty into v_sale_entry_id,v_sale_entry_qty from public.stock_entries se where se.boutique_id=p_boutique_id and se.source_invoice_line_id=v_source.id and se.qty<0 order by se.entry_date,se.id limit 1;
    v_actual_unit_cost:=coalesce(v_source.prix_achat,0);
    if v_sale_entry_id is not null and abs(coalesce(v_sale_entry_qty,0))>0 then
      v_fifo_cost:=private.fifo_outflow_cost(p_boutique_id,v_source.product_id,v_sale_entry_id);
      if v_fifo_cost>0 then v_actual_unit_cost:=v_fifo_cost/abs(v_sale_entry_qty); end if;
    end if;
    insert into public.invoice_lines(boutique_id,invoice_id,product_id,nom,qty,unit,prix_unit,sell_unit,sell_qty,prix_achat,source_invoice_line_id)
    values(p_boutique_id,v_return_id,v_source.product_id,v_source.nom,v_qty,v_source.unit,v_source.prix_unit,v_source.sell_unit,v_return_sell_qty,case when v_actual_unit_cost>0 then round(v_actual_unit_cost,4) else null end,v_source.id) returning id into v_return_line_id;
    update public.products set stock=stock+v_qty where boutique_id=p_boutique_id and id=v_source.product_id;
    if not found then raise exception 'product not found for return line %',v_source.product_id; end if;
    insert into public.stock_entries(id,boutique_id,product_id,type,qty,prix_unit,entry_date,operator_id,note,source_invoice_id,source_invoice_line_id,return_invoice_id,return_invoice_line_id)
    values(nextval('private.stock_entry_id_seq'),p_boutique_id,v_source.product_id,'retour',v_qty,round(coalesce(v_actual_unit_cost,0),2),v_returned_at,v_user,'Retour '||p_invoice_id,p_invoice_id,v_source.id,v_return_id,v_return_line_id);
  end loop;

  v_response:=jsonb_build_object('return_invoice_id',v_return_id,'credit_note_number',v_credit_num,'source_invoice_id',p_invoice_id,'total',v_total,'returned_at',v_returned_at,'registered_client',v_original.client_id is not null,'refund_method',v_refund_method,'refund_amount',v_refund_amount,'receivable_reduction',v_receivable_reduction,'client_credit_amount',v_client_credit_amount,'credit_restore',v_client_credit_amount,'restored_advance_id',v_advance_id,'payment',case when v_payment_id is null then null else jsonb_build_object('id',v_payment_id,'amount',v_refund_amount,'payment_method',v_refund_method,'paid_at',v_returned_at,'operator_id',v_user,'operator_name',v_operator_name,'batch_id',p_idempotency_key,'source','invoice') end);
  insert into private.idempotency_keys(user_id,operation,key,response) values(v_user,'return_sale',p_idempotency_key,v_response);
  return v_response;
end $$;

revoke all on function public.return_sale(text,text,uuid,jsonb,text) from public,anon;
grant execute on function public.return_sale(text,text,uuid,jsonb,text) to authenticated,service_role;
